### ISSUE TITLE
SSLHandshakeException when using Java 1.8.0_51

### ISSUE THREAD

**Issue by Alexander01998** [getsentry/sentry-java#1000]
_Platform:_
- [X]  Java ->
  - Version: 1.8.0_51 (Oracle)
  - sourceCompatibilty: 1.8
  - targetCompatibilty: 1.8

_IDE:_
- [X]  Eclipse

_Build system:_
- [X]  Gradle -> 4.10.3

_Android Gradle Plugin:_
- [X]  No, this is a desktop application.

_Sentry Android Gradle Plugin:_
- [X]  No, this is a desktop application.

_Proguard/R8:_
- [X]  Disabled

_Platform installed with:_
- [X] Gradle

The version of the SDK:
**3.1.0** (also tried 3.1.0-log4j2, 3.1.1, 3.1.1-log4j2)
Using Sentry.io, **not** self-hosted Sentry.

---
I have the following issue:

When using Java 1.8.0_51, any calls to `Sentry.captureException()` fail with the following exception:

```
[16:59:47.077] [net.minecraft.class_2983] [SentryAsyncConnection-0] [STDOUT]: ERROR: Envelope submission failed 
 java.lang.IllegalStateException: Sending the event failed.
java.lang.IllegalStateException: Sending the event failed.
	at io.sentry.transport.AsyncConnection$EnvelopeSender.flush(AsyncConnection.java:258)
	at io.sentry.transport.AsyncConnection$EnvelopeSender.run(AsyncConnection.java:212)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1497)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at io.sentry.transport.HttpTransport.createConnection(HttpTransport.java:245)
	at io.sentry.transport.HttpTransport.send(HttpTransport.java:251)
	at io.sentry.transport.AsyncConnection$EnvelopeSender.flush(AsyncConnection.java:239)
	... 6 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1479)
	... 19 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:145)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
	... 25 more
```

It seems that there is something about `ingest.sentry.io`'s SSL certificate that Java 1.8.0_51 doesn't understand yet. Later versions of Java (like 1.8.0_261) can deal with the certificate just fine, but my users are stuck on v1.8.0_51, so updating Java is sadly not an option.

**Steps to reproduce:**
1. Set up Sentry and try to capture a test exception. Optionally enable debug mode to see what's going on in the logs.
    ```java
    Sentry.init(options -> {
        options.setDsn("https://ID@ID.ingest.sentry.io/ID");// replace this with a valid Sentry.io DSN
        options.setDebug(true);
    });
    Sentry.captureException(new RuntimeException("test"));
    ```
2. Make sure your java version is 1.8.0_51 (later versions like 1.8.0_261 don't have this issue).
3. Launch the jar, watch the log files and your Sentry dashboard.

**Actual result:**
- The test exception won't appear on the Sentry dashboard, but the above exception will show up in your log files if debug mode is enabled.

**Expected result:**
- I expect the test exception to be reported successfully, even when using Java 1.8.0_51.

**Comment by bruno-garcia** [comment]
It is possible you don't have ingest.sentry.io root CA in your local certificate store?
There are some [instructions on how to add it](https://stackoverflow.com/questions/21076179/pkix-path-building-failed-and-unable-to-find-valid-certification-path-to-requ).

**Comment by Alexander01998** [comment]
> It is possible you don't have ingest.sentry.io root CA in your local certificate store?

No, I definitely have it. I have opened my `https://ID@ID.ingest.sentry.io/ID` page in Chrome and verified that it accepts the certificate.

![image](https://user-images.githubusercontent.com/10100202/96502208-c4e62480-1251-11eb-841c-985455cee83c.png)

Like I said, as soon as I switch to Java 1.8.0_261, it accepts the certificate just fine. It's only when I run Sentry using Java 1.8.0_51 that it stops working.

**Comment by bruno-garcia** [comment]
That's your Windows store, Java has its own, doesn't it? The link I shared talks about the Java keystore and adding root CAs into it.

**Comment by bruno-garcia** [comment]
https://support.comodo.com/index.php?/Knowledgebase/Article/View/296/17/are-your-roots-included-in-any-java-release

**Comment by Alexander01998** [comment]
> The link I shared talks about the Java keystore and adding root CAs into it.

Thanks for the advice, but messing with the keystores of my users is not something that I'm OK with, due to the risk of getting false-flagged as a virus and thereby damaging my reputation.

I have been able to fix this issue by using a self-hosted Sentry instance with an [SSL certificate from Cloudflare](https://user-images.githubusercontent.com/10100202/97606036-9fa2a480-1a0f-11eb-9963-b6e7ceb7f942.png) that Java 1.8.0_51 can understand using its default keystores. It's unfortunate because Sentry.io would have been cheaper for me.

If you ever consider replacing Sentry.io's SLL certificate with something more legacy-friendly, please let me know. I would love to switch back to Sentry.io.

**Comment by bruno-garcia** [comment]
@Alexander01998 I'm sorry if this comes too late. But could you try to change your dsn from the `ingest.sentry.io` to use plain `sentry.io`: 

`https://5fd7a6cda8444965bade9ccfd3df9882@sentry.io/1188141`

**Comment by Alexander01998** [comment]
Thanks! I'll try that and let you know the result.

**Comment by Alexander01998** [comment]
@bruno-garcia This works **perfectly**! Thank you so much! 😃
