### ISSUE TITLE
Sentry.captureException results in 400 "invalid event envelope"

### ISSUE THREAD

**Issue by wvdemeer** [getsentry/sentry-java#1004]
_Platform:_
- [x]  Java -> java 14

_IDE:_
- [x]  IntelliJ -> 2020.2

_Build system:_
- [x]  Maven -> 3.6.3

_Android Gradle Plugin:_
- [x]  No

_Sentry Android Gradle Plugin:_
- [x]  No

_Proguard/R8:_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [x] Maven Central

The version of the SDK:
**3.1.1** (I first had this same issue for 3.1.0, then upgraded, but that didn't fix it.)

I'm not using sentry.io, but a local deployment of sentry, with version "**Sentry 20.10.1 78833d9**".
(I first had this same issue for 20.7.2, then upgraded, but that didn't fix it.)

---
I have the following issue:

If I call `Sentry.captureException(someException)`, that doesn't return an error. But sentry doesn't receive the event. And I get these log messages:

```
DEBUG: Capturing event: 9c5a65e29c1e4f588e15d292c4abf270
INFO: Session is null on scope.withSession
ERROR: Request failed, API returned 400
ERROR: {"detail":"invalid event envelope","causes":["invalid item header","EOF while parsing an object at line 1 column 49"]}
```

Any hints on how to debug this further are appreciated.

**Steps to reproduce:**
- call `Sentry.captureException(someException)`

**Actual result:**
- Sentry doesn't receive the event

**Expected result:**
- Sentry receives the event

**Comment by wvdemeer** [comment]
I also tried on `sentry.io`, instead of the local sentry deployment. 
But that results in this:

```
ERROR: Envelope submission failed 
 java.lang.IllegalStateException: Sending the event failed.
java.lang.IllegalStateException: Sending the event failed.
	at io.sentry.transport.AsyncConnection$EnvelopeSender.flush(AsyncConnection.java:258)
	at io.sentry.transport.AsyncConnection$EnvelopeSender.run(AsyncConnection.java:212)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: javax.net.ssl.SSLHandshakeException: No subject alternative DNS name matching o465467.ingest.sentry.io found.
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:325)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:268)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:263)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:645)
	at java.base/sun.security.ssl.CertificateStatus$CertificateStatusConsumer.consume(CertificateStatus.java:295)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:445)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:423)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:182)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:171)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1475)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1381)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:441)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:412)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:171)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:142)
	at io.sentry.transport.HttpTransport.createConnection(HttpTransport.java:245)
	at io.sentry.transport.HttpTransport.send(HttpTransport.java:251)
	at io.sentry.transport.AsyncConnection$EnvelopeSender.flush(AsyncConnection.java:239)
	... 6 more
Caused by: java.security.cert.CertificateException: No subject alternative DNS name matching o465467.ingest.sentry.io found.
	at java.base/sun.security.util.HostnameChecker.matchDNS(HostnameChecker.java:212)
	at java.base/sun.security.util.HostnameChecker.match(HostnameChecker.java:103)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:452)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:426)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:238)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:629)
	... 22 more
```
(`o465467.ingest.sentry.io` is the hostname part of the DSN)

And that's clearly a seperate issue...

**Comment by marandaneto** [comment]
@wvdemeer thanks for raising this, do you mind doing just `Sentry.captureMessage("test")` and copy-paste the logs? I'm wondering if it's any related to #1000

**Comment by wvdemeer** [comment]
I tried `Sentry.captureMessage("test")` for both sentry.io and my local sentry deployment.
No change, in both cases still the exact same errors. 

I also tried to put `Sentry.captureMessage("test")` directly after `Sentry.init(...)`, just to be sure. But the result is the same again.

For the sentry.io case, I successfully circumvented host name checking with:
```
        Sentry.init(options -> {
            options.setDsn("https://redacted@o465467.ingest.sentry.io/redacted");
            options.setHostnameVerifier(NoopHostnameVerifier.INSTANCE);
            options.setDebug(true);
            options.setDiagnosticLevel(SentryLevel.DEBUG);
        });
        Sentry.captureMessage("test");
```

If I do that, I get the same as on my local Sentry deploy!
```
DEBUG: Capturing event: 5048e3d95d544f58b05fce48764d262f
INFO: Session is null on scope.withSession
ERROR: Request failed, API returned 400
ERROR: {"detail":"invalid event envelope","causes":["invalid item header","EOF while parsing an object at line 1 column 49"]}
```

**Comment by bruno-garcia** [comment]
> No subject alternative DNS name matching o465467.ingest.sentry.io found.

This sounds like a TLS issue, like looking for the subdomain in the SAN of the cert your have hosted.

Do you have the root certificate authority that issued the certificate in your CA store?
What version of Java is this running in? My guess is that it's Java 1.8 in an older version, is that the case?

**Comment by bruno-garcia** [comment]
> If I do that, I get the same as on my local Sentry deploy!

Sounds like your Sentry doesn't support Envelope endpoints.

The changelog states:

> Note for Sentry On Premise users
This version uses the envelope endpoint. If you are using an on-premise installation it requires Sentry version >= v20.6.0 to work. If you are using sentry.io nothing will change and no action is needed.

Please upgrade your on-prem Sentry and try again

**Comment by wvdemeer** [comment]
### SSL bug

Ok, I dug deeper. And the SSL thing is solved! Apparently, I added this code 2 years ago, to work around a server side bug (of a server I had no control over):
```
System.setProperty("jsse.enableSNIExtension", "false");
```
That's obviously bad, as it affects all connections. After removing it, the sentry SSL connection works again! (Can't believe this never triggered any other connection bugs, as the application connects to a lot of servers.)


### `"invalid event envelope"` bug
The on premises install is "**Sentry 20.10.1 78833d9**", so that should be new enough. With the SSL bug fixed, I get the `"invalid event envelope"` bug on *sentry.io* as well now.

**BUT** I tried making a minimal viable demonstration of the bug... and I couldn't! It just works on any small project I try. So something (probably a dependency) in my application causes the problem. I'm going to investigate (digging into `mvn dependency:tree -Dverbose`), and I'll report here for completeness if I find it the actual cause. 

But in any case: this doesn't appear to be a sentry bug!

**Comment by wvdemeer** [comment]
Ok, I got it. Sentry depends on gson 2.8.5 (only 1 dependency, nice!) but my `pom.xml` also had a dep on gson 2.3.1
That never complains, but causes `"invalid event envelope"` when sentry tries to send a message at runtime. :frowning_face:

I learned a lesson: make a "minimal viable demonstration" sooner.
(I already knew java dependencies are hell.)

Thanks for the help!

**Comment by marandaneto** [comment]
> Ok, I got it. Sentry depends on gson 2.8.5 (only 1 dependency, nice!) but my `pom.xml` also had a dep on gson 2.3.1
> That never complains, but causes `"invalid event envelope"` when sentry tries to send a message at runtime. ☹️
> 
> I learned a lesson: make a "minimal viable demonstration" sooner.
> (I already knew java dependencies are hell.)
> 
> Thanks for the help!

@wvdemeer thanks for the finding, this is also valuable to us, we didn't know that Gson 2.3.1 + Java 14 would cause issues, damn.
yeah dependencies cost is part of our philosophy https://develop.sentry.dev/sdk/philosophy/#dependencies-cost
some SDKs don't have any but sometimes is just inevitable, we don't want to reinvent the well for JSON serialization and prefer to focus on other stuff.
Did it work by upgrading your Gson?

thanks for the feedback.

**Comment by wvdemeer** [comment]
Yes, it works if I change my dependency to gson 2.8.5 instead.

I've also been able to make my "minimal viable demonstration" fail by using this pom:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>minimal-sentry-bugdemo</artifactId>
    <version>1.0-SNAPSHOT</version>

    <dependencies>
        <dependency>
            <groupId>io.sentry</groupId>
            <artifactId>sentry</artifactId>
            <version>3.1.1</version>
        </dependency>

        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.3.1</version>
        </dependency>
    </dependencies>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.8.0</version>
                    <configuration>
                        <source>14</source>
                        <target>14</target>
                        <showWarnings>true</showWarnings>
                        <showDeprecation>true</showDeprecation>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
```

And this main:
```
package org.example;
import io.sentry.Sentry;
import io.sentry.SentryLevel;
public class SentryBug {
    public static void main(String[] args) {
        Sentry.init(options -> {
            options.setDsn("https://redacted@o465467.ingest.sentry.io/redacted");
            options.setDebug(true);
            options.setDiagnosticLevel(SentryLevel.DEBUG);
        });
        Sentry.captureMessage("test");
    }
}
```

That fails with:
```
INFO: Initializing SDK with DSN: 'https://redacted@o465467.ingest.sentry.io/redacted'
INFO: No outbox dir path is defined in options.
INFO: GlobalHubMode: 'false'
DEBUG: UncaughtExceptionHandlerIntegration enabled: true
DEBUG: UncaughtExceptionHandlerIntegration installed.
DEBUG: Capturing event: e25d7ff2d2544e40ad5d99e148db4a04
INFO: Session is null on scope.withSession
INFO: Closing SentryClient.
DEBUG: Shutting down
ERROR: Request failed, API returned 400
ERROR: {"detail":"invalid event envelope","causes":["invalid item header","EOF while parsing an object at line 1 column 49"]}
```

(dsn details have been redacted)

Remove the gson dep from that `pom.xml`, and it works.

**Comment by marandaneto** [comment]
thanks for the feedback

**Comment by caseyoneill** [comment]
Wow. This got me too and I never would have figured it out without this post. Is there a better way to log issues like this envelope error without enabling debug?
