### ISSUE TITLE
Seeing exception at runtime

### ISSUE THREAD

**Issue by chhavi-peloton** [getsentry/sentry-java#1199]
Hi,

I am trying to migrate from 1.7 to 3.21 in my Kotlin gradle project. I followed your docs to make the required API changes. I am now seeing the following error during runtime:

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/gson/GsonBuilder
	at io.sentry.EnvelopeReader.<init>(EnvelopeReader.java:22)
	at io.sentry.SentryOptions.<init>(SentryOptions.java:82)
	at io.sentry.Sentry.init(Sentry.java:122)
	at io.sentry.Sentry.init(Sentry.java:110)
	at io.sentry.log4j2.SentryAppender.start(SentryAppender.java:100)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:304)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:622)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:695)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:712)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:267)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:155)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:597)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:583)
	at base.com.peloton.Server.<init>(Server.kt:36)
	at com.peloton.leaderboard.main.Runner$Companion.main(Runner.kt:79)
	at com.peloton.leaderboard.main.Runner.main(Runner.kt)
Caused by: java.lang.ClassNotFoundException: com.google.gson.GsonBuilder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
```
	
Any ideas why I might be seeing this?

**Comment by bruno-garcia** [comment]
What version of Gson are you using? Sentry depends on Gson. It came up in a different form recently so wondering if related: https://github.com/getsentry/sentry-java/issues/1004#issuecomment-715131485

**Comment by marandaneto** [comment]
@chhavi-peloton did you manage to fix it? what was it?

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
