### ISSUE TITLE
Flaky test: `ApacheHttpClientTransportTest`

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-java#1261]
Seems `ApacheHttpClientTransportTest` is flaky:

```
io.sentry.transport.apache.ApacheHttpClientTransportTest > flush waits till all requests are finished FAILED
    org.mockito.exceptions.verification.TooLittleActualInvocations: 
    reusableCountLatch.decrement();
    Wanted 3 times:
    -> at io.sentry.transport.ReusableCountLatch.decrement(ReusableCountLatch.java:89)
    But was 2 times:
    -> at io.sentry.transport.apache.ApacheHttpClientTransport$1.completed(ApacheHttpClientTransport.java:111)
    -> at io.sentry.transport.apache.ApacheHttpClientTransport$1.completed(ApacheHttpClientTransport.java:111)
        at io.sentry.transport.ReusableCountLatch.decrement(ReusableCountLatch.java:89)
        at io.sentry.transport.apache.ApacheHttpClientTransportTest.flush waits till all requests are finished(ApacheHttpClientTransportTest.kt:127)
```

**Comment by marandaneto** [comment]
yes https://github.com/getsentry/sentry-java/pull/1238#issuecomment-779077081
