### ISSUE TITLE
NullPointerException for exceptions generated by android ndk c++ code

### ISSUE THREAD

**Issue by fzyzcjy** [getsentry/sentry-java#1353]
_Platform:_
- [x]  Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version?
- [ ]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version?
- [ ]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [ ]  NDK -> If yes, which NDK/CMake version?
- [ ]  React-Native -> If yes, which version?
- [ ]  Timber -> If yes, which version?
- [ ]  Log4j2 -> If yes, which version?
- [ ]  Logback -> If yes, which version?
- [ ]  Spring -> If yes, which version?

_IDE:_
- [ ]  Android Studio -> If yes, which version?
- [x]  IntelliJ -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Build system:_
- [x]  Gradle -> If yes, which version?
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [ ]  Maven -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [x]  Yes -> If yes, which version?
- [ ]  No

_Sentry Android Gradle Plugin:_
- [x]  Yes -> If yes, which version?
- [ ]  No

_Proguard/R8:_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [ ] JCenter
- [ ] Bintray
- [x] Maven Central
- [ ] Manually

The version of the SDK:
**3.x.x**

---
I have the following issue:

Thanks for the lib! I try to capture an exception manually in android ndk (c++) code like this:

```
        sentry_value_t exc = sentry_value_new_object();
        sentry_value_set_by_key(exc, "type", sentry_value_new_string("Exception"));
        sentry_value_set_by_key(exc, "value", sentry_value_new_string("myerror"));

        sentry_value_t event = sentry_value_new_event();
        sentry_value_set_by_key(event, "exception", exc);
        sentry_capture_event(event);
```

but then error occurs:

```
2021-03-26 08:34:15.561 20920-21009/com.cjy.yplusplus E/Sentry: Error while capturing event with id: f8940f9a7dda40dc4fd1f11070fe1d22
    java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
        at io.sentry.SentryEvent.isCrashed(SentryEvent.java:346)
        at io.sentry.SentryClient.lambda$updateSessionData$0$SentryClient(SentryClient.java:268)
        at io.sentry.-$$Lambda$SentryClient$95WLIRfJlDw7w3H0oQsRkrt03kA.accept(Unknown Source:6)
        at io.sentry.Scope.withSession(Scope.java:598)
        at io.sentry.SentryClient.updateSessionData(SentryClient.java:264)
        at io.sentry.SentryClient.captureEvent(SentryClient.java:81)
        at io.sentry.Hub.captureEvent(Hub.java:82)
        at io.sentry.Sentry.captureEvent(Sentry.java:254)
        at io.sentry.HubAdapter.captureEvent(HubAdapter.java:27)
        at io.sentry.OutboxSender.processEnvelope(OutboxSender.java:141)
        at io.sentry.OutboxSender.processFile(OutboxSender.java:68)
        at io.sentry.OutboxSender.processEnvelopeFile(OutboxSender.java:101)
        at io.sentry.android.core.EnvelopeFileObserver.onEvent(EnvelopeFileObserver.java:59)
        at android.os.FileObserver$ObserverThread.onEvent(FileObserver.java:163)
        at android.os.FileObserver$ObserverThread.observe(Native Method)
        at android.os.FileObserver$ObserverThread.run(FileObserver.java:113)
```

**EDIT:**

I tried to write this hacky code. Is it correct?

```
        // SentryException
        sentry_value_t exc = sentry_value_new_object();
        sentry_value_set_by_key(exc, "type", sentry_value_new_string("Exception"));
        sentry_value_set_by_key(exc, "value", sentry_value_new_string(oss.str().c_str()));

        // List<SentryException> values;
        sentry_value_t values_list = sentry_value_new_list();
        sentry_value_append(values_list, exc);

        // SentryValues<SentryException> exception;
        sentry_value_t exception_obj = sentry_value_new_object();
        sentry_value_set_by_key(exception_obj, "values", values_list);

        // SentryEvent event;
        sentry_value_t event = sentry_value_new_event();
        sentry_value_set_by_key(event, "exception", exception_obj);
        sentry_capture_event(event);
```

**Comment by marandaneto** [comment]
dup of https://github.com/getsentry/sentry-java/issues/1354

**Comment by fzyzcjy** [comment]
@marandaneto Thanks. I cross-posted because I do not know which repository should I send this issue to.

**Comment by marandaneto** [comment]
@fzyzcjy no worries, please stick to one of them, I'll get to them anyway :)
fwiw, if C/C++ code, https://github.com/getsentry/sentry-native
ObC/Swift -> https://github.com/getsentry/sentry-cocoa
Android/Java, this one
Dart/Flutter, https://github.com/getsentry/sentry-dart
