### ISSUE TITLE
Spring Boot: error creating the bean named "sentryOptionsConfiguration" because "io.sentry.SentryOptions$TracesSamplerCallback" is not present.

### ISSUE THREAD

**Issue by kevintweber** [getsentry/sentry-java#1369]
_Platform:_
- [ ]  Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version?
- [ X]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version?  11.0.10
- [ ]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [ ]  NDK -> If yes, which NDK/CMake version?
- [ ]  React-Native -> If yes, which version?
- [ ]  Timber -> If yes, which version?
- [ ]  Log4j2 -> If yes, which version?
- [ ]  Logback -> If yes, which version?
- [ X]  Spring -> If yes, which version? Spring Boot 2.4.4

_IDE:_
- [ ]  Android Studio -> If yes, which version?
- [ X]  IntelliJ -> If yes, which version? latest Ultimate
- [ ]  Other -> If yes, which one?

_Build system:_
- [ ]  Gradle -> If yes, which version?
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [X ]  Maven -> If yes, which version?  3.6.3
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [ ]  No

_Sentry Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [ ]  No

_Proguard/R8:_
- [ ]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [ ] JCenter
- [ ] Bintray
- [ X] Maven Central
- [ ] Manually

The version of the SDK:
**4.3.0**

---
I have the following issue:

There is an error creating the bean named "sentryOptionsConfiguration" because "io.sentry.SentryOptions$TracesSamplerCallback" is not present.

```
[hlx-phaser-mr] DEBUG c.h.phasermr.HlxPhaserMrApplication - Running with Spring Boot v2.4.4, Spring v5.3.5
[hlx-phaser-mr] INFO  c.h.phasermr.HlxPhaserMrApplication - No active profile set, falling back to default profiles: default
[hlx-phaser-mr] INFO  o.s.j.d.e.EmbeddedDatabaseFactory - Starting embedded database: url='jdbc:h2:mem:a84cceab-0c9a-4737-a1af-acea53fbf332;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false', username='sa'
[hlx-phaser-mr] WARN  o.s.b.c.c.a.DefaultBatchConfigurer - No transaction manager was provided, using a DataSourceTransactionManager
[hlx-phaser-mr] INFO  o.s.b.c.r.s.JobRepositoryFactoryBean - No database type set, using meta data indicating: H2
[hlx-phaser-mr] INFO  o.s.b.c.l.support.SimpleJobLauncher - No TaskExecutor has been set, defaulting to synchronous executor.
[hlx-phaser-mr] WARN  o.s.c.a.AnnotationConfigApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sentryOptionsConfiguration' defined in class path resource [io/sentry/spring/boot/SentryAutoConfiguration$HubConfiguration.class]: Unexpected exception during bean creation; nested exception is java.lang.TypeNotPresentException: Type io.sentry.SentryOptions$TracesSamplerCallback not present
[hlx-phaser-mr] INFO  o.s.j.d.e.EmbeddedDatabaseFactory - Shutting down embedded database: url='jdbc:h2:mem:a84cceab-0c9a-4737-a1af-acea53fbf332;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false'
[hlx-phaser-mr] INFO  o.s.b.a.l.ConditionEvaluationReportLoggingListener - 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[hlx-phaser-mr] ERROR o.s.boot.SpringApplication - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sentryOptionsConfiguration' defined in class path resource [io/sentry/spring/boot/SentryAutoConfiguration$HubConfiguration.class]: Unexpected exception during bean creation; nested exception is java.lang.TypeNotPresentException: Type io.sentry.SentryOptions$TracesSamplerCallback not present
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:537)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:769)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1313)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302)
	at com.hlx.phasermr.HlxPhaserMrApplication.main(HlxPhaserMrApplication.java:12)
Caused by: java.lang.TypeNotPresentException: Type io.sentry.SentryOptions$TracesSamplerCallback not present
	at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117)
	at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
	at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at java.base/sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68)
	at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138)
	at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at java.base/sun.reflect.generics.repository.ConstructorRepository.computeParameterTypes(ConstructorRepository.java:111)
	at java.base/sun.reflect.generics.repository.ConstructorRepository.getParameterTypes(ConstructorRepository.java:87)
	at java.base/java.lang.reflect.Executable.getGenericParameterTypes(Executable.java:279)
	at java.base/java.lang.reflect.Method.getGenericParameterTypes(Method.java:330)
	at org.springframework.core.MethodParameter.getGenericParameterType(MethodParameter.java:513)
	at org.springframework.core.MethodParameter.getNestedParameterType(MethodParameter.java:553)
	at org.springframework.beans.factory.config.DependencyDescriptor.getDependencyType(DependencyDescriptor.java:411)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory$DependencyObjectProvider.<init>(DefaultListableBeanFactory.java:1969)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1291)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:541)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	... 14 common frames omitted
Caused by: java.lang.ClassNotFoundException: io.sentry.SentryOptions$TracesSamplerCallback
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
	... 35 common frames omitted

Process finished with exit code 1
```

I am using the following properties:
```
sentry:
  dsn: https://4b64...
  enable-tracing: false
```

When I downgrade Sentry to v3.2.0, the issue goes away.  Clearly this has something to do with the performance monitoring despite having actively disabled it.

**Steps to reproduce:**
- Execute the program

**Actual result:**
- Startup error.  See logs above.

**Expected result:**
- Application executes

**Comment by marandaneto** [comment]
@kevintweber thanks for reporting.

did you check if you need to change something from v3 to v4? See https://docs.sentry.io/platforms/java/migration/
also, please run once more with `debug: true` and copy-paste Sentry's logs, thanks.

**Comment by maciejwalkowiak** [comment]
@kevintweber since you are getting`ClassNotFoundException` it seems that the Sentry dependencies versions you declared are not aligned. Can you make sure that you all Sentry dependencies use the same version?

When using Spring Boot integration you only need to declare one dependency:

```xml
<dependency>
    <groupId>io.sentry</groupId>
    <artifactId>sentry-spring-boot-starter</artifactId>
    <version>4.3.0</version>
</dependency>
```

In case you use also Logback:

```xml
<dependency>
    <groupId>io.sentry</groupId>
    <artifactId>sentry-logback</artifactId>
    <version>4.3.0</version>
</dependency>
```

In case your setup is more complex than that, please use `mvn dependency:tree | grep sentry` and make sure each dependency has version `4.3.0`.

**Comment by marandaneto** [comment]
@kevintweber any feedback? thanks

**Comment by kevintweber** [comment]
Sorry for the delayed response.

In fact, the dependencies were not aligned.  I had a jar for common classes that had io.sentry:sentry:3.2.0 declared in it.

Thanks for your help.
