### ISSUE TITLE
Spring Native - startup failure

### ISSUE THREAD

**Issue by maciejwalkowiak** [getsentry/sentry-java#1373]
When Sentry Spring Boot Starter is used with Spring Native, application fails to start with exception:
```
java.lang.IllegalStateException: Error processing condition on io.sentry.spring.boot.SentryAutoConfiguration$HubConfiguration$SentryPerformanceAspectsConfiguration
        at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:60) ~[org.springframework.samples.petclinic.PetClinicApplication:2.4.4]
        at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:108) ~[na:na]
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader$TrackedConditionEvaluator.shouldSkip(ConfigurationClassBeanDefinitionReader.java:489) ~[na:na]
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader$TrackedConditionEvaluator.shouldSkip(ConfigurationClassBeanDefinitionReader.java:478) ~[na:na]
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader$TrackedConditionEvaluator.shouldSkip(ConfigurationClassBeanDefinitionReader.java:478) ~[na:na]
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:140) ~[na:na]
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:129) ~[na:na]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:343) ~[org.springframework.samples.petclinic.PetClinicApplication:5.3.5]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:247) ~[org.springframework.samples.petclinic.PetClinicApplication:5.3.5]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311) ~[na:na]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564) ~[na:na]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[na:na]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:769) [org.springframework.samples.petclinic.PetClinicApplication:2.4.4]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761) [org.springframework.samples.petclinic.PetClinicApplication:2.4.4]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426) [org.springframework.samples.petclinic.PetClinicApplication:2.4.4]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) [org.springframework.samples.petclinic.PetClinicApplication:2.4.4]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1313) [org.springframework.samples.petclinic.PetClinicApplication:2.4.4]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) [org.springframework.samples.petclinic.PetClinicApplication:2.4.4]
        at org.springframework.samples.petclinic.PetClinicApplication.main(PetClinicApplication.java:33) [org.springframework.samples.petclinic.PetClinicApplication:na]
Caused by: java.lang.IllegalStateException: java.io.FileNotFoundException: class path resource [io/sentry/spring/boot/SentryTracingCondition$SentryTracesSamplerBeanCondition.class] cannot be opened because it does not exist
        at org.springframework.boot.autoconfigure.condition.AbstractNestedCondition$MemberConditions.getMetadata(AbstractNestedCondition.java:149) ~[na:na]
        at org.springframework.boot.autoconfigure.condition.AbstractNestedCondition$MemberConditions.getMemberConditions(AbstractNestedCondition.java:121) ~[na:na]
        at org.springframework.boot.autoconfigure.condition.AbstractNestedCondition$MemberConditions.<init>(AbstractNestedCondition.java:114) ~[na:na]
        at org.springframework.boot.autoconfigure.condition.AbstractNestedCondition.getMatchOutcome(AbstractNestedCondition.java:62) ~[org.springframework.samples.petclinic.PetClinicApplication:2.4.4]
        at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47) ~[org.springframework.samples.petclinic.PetClinicApplication:2.4.4]
        ... 20 common frames omitted
Caused by: java.io.FileNotFoundException: class path resource [io/sentry/spring/boot/SentryTracingCondition$SentryTracesSamplerBeanCondition.class] cannot be opened because it does not exist
        at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:187) ~[na:na]
        at org.springframework.core.type.classreading.SimpleMetadataReader.getClassReader(SimpleMetadataReader.java:55) ~[na:na]
        at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:49) ~[na:na]
        at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:103) ~[na:na]
        at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:81) ~[na:na]
        at org.springframework.boot.autoconfigure.condition.AbstractNestedCondition$MemberConditions.getMetadata(AbstractNestedCondition.java:146) ~[na:na]
        ... 24 common frames omitted
```

**Comment by adinauer** [comment]
We will wait for spring-native support in Spring 6.0.
