### ISSUE TITLE
Failed to decode zlib payload

### ISSUE THREAD

**Issue by Reedyuk** [getsentry/sentry-java#1400]
_Platform:_
- [ * ]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version? 1.8

_IDE:_
- [ * ]  IntelliJ -> If yes, which version? 2020.3

_Build system:_
- [ * ]  Gradle -> If yes, which version?

_Android Gradle Plugin:_
- [ * ]  No

_Sentry Android Gradle Plugin:_
- [ * ]  No

_Proguard/R8:_
- [ * ]  Enabled

_Platform installed with:_
- [ * ] JCenter

The version of the SDK:
1.7.30

---
I have the following issue: 
I have been getting error reports within sentry about sentry failing to send a report.

The description goes here:
I have had a few users get this error:

```
java.net.SocketTimeoutException: connect timed out
    at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
    at java.net.Socket.connect(Socket.java:609)
    at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:289)
    at sun.net.NetworkClient.doConnect(NetworkClient.java:177)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
    at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
    at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:168)
    at io.sentry.connection.HttpConnection.doSend(HttpConnection.java:168)
    at io.sentry.connection.AbstractConnection.send(AbstractConnection.java:88)
    at io.sentry.connection.AsyncConnection$EventSubmitter.run(AsyncConnection.java:187)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:834)
io.sentry.connection.ConnectionException: {"detail":"failed to read request body","causes":["failed to decode zlib payload","corrupt deflate stream"]}
    at io.sentry.connection.HttpConnection.doSend(HttpConnection.java:216)
    at io.sentry.connection.AbstractConnection.send(AbstractConnection.java:88)
    at io.sentry.connection.AsyncConnection$EventSubmitter.run(AsyncConnection.java:187)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:834)
```

**Expected result:**
- I wouldn't expect to see these in sentry.

**Comment by marandaneto** [comment]
@Reedyuk thanks for reporting, the Java SDK 1.7.x is deprecated, have you considered upgrading to the latest version?

**Comment by Reedyuk** [comment]
I would like to, but i think it would take a sizeable refactor. I will aim to do this in the future, but for now, is there a quick fix to stop this being reported?

**Comment by marandaneto** [comment]
@Reedyuk the Java SDK 1.7.x isn't maintained anymore, even if it's a bug (which I'm not even sure), we won't be able to release a fix, please upgrade it and if you find any new issues, please report them :) thanks.
