### ISSUE TITLE
event is null - during tests only

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1576]
many tests are triggering `event is null`
eg `does not send events for handled exceptions`

they don't fail because it's within a `await` condition and it may trigger after the test is finished.
the issue is probably within the `checkEvent` and or `checkTransaction` assertion test that may be called multiple times within a test

java.lang.AssertionError: event is null
	at io.sentry.test.AssertionsKt$checkEvent$1.invoke(assertions.kt:22)
	at io.sentry.test.AssertionsKt$checkEvent$1.invoke(assertions.kt)
	at io.sentry.test.AssertionsKt$checkEvent$$inlined$check$1.matches(Verification.kt:256)
	at org.mockito.internal.invocation.TypeSafeMatching.apply(TypeSafeMatching.java:24)
	at org.mockito.internal.invocation.MatcherApplicationStrategy.forEachMatcherAndArgument(MatcherApplicationStrategy.java:84)
	at org.mockito.internal.invocation.InvocationMatcher.argumentsMatch(InvocationMatcher.java:156)
	at org.mockito.internal.invocation.InvocationMatcher.matches(InvocationMatcher.java:82)
	at org.mockito.internal.invocation.InvocationsFinder$RemoveNotMatching.isOut(InvocationsFinder.java:169)
	at org.mockito.internal.invocation.InvocationsFinder$RemoveNotMatching.isOut(InvocationsFinder.java:161)
	at org.mockito.internal.util.collections.ListUtil.filter(ListUtil.java:21)
	at org.mockito.internal.invocation.InvocationsFinder.findInvocations(InvocationsFinder.java:23)
	at org.mockito.internal.verification.checkers.NumberOfInvocationsChecker.checkNumberOfInvocations(NumberOfInvocationsChecker.java:34)
	at org.mockito.internal.verification.Times.verify(Times.java:39)
	at org.mockito.internal.verification.MockAwareVerificationMode.verify(MockAwareVerificationMode.java:29)
	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:71)
	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:33)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:82)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:56)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptAbstract(MockMethodInterceptor.java:157)
	at org.mockito.codegen.ITransport$MockitoMock$424708305.send(Unknown Source)
	at io.sentry.spring.mvc.SentrySpringIntegrationTest$does not send events for handled exceptions$1.run(SentrySpringIntegrationTest.kt:162)
	at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:222)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:209)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.AssertionError: event is null
	at io.sentry.test.AssertionsKt$checkEvent$1.invoke(assertions.kt:22)
	at io.sentry.test.AssertionsKt$checkEvent$1.invoke(assertions.kt)
	at io.sentry.test.AssertionsKt$checkEvent$$inlined$check$1.matches(Verification.kt:256)
	at org.mockito.internal.invocation.TypeSafeMatching.apply(TypeSafeMatching.java:24)
	at org.mockito.internal.invocation.MatcherApplicationStrategy.forEachMatcherAndArgument(MatcherApplicationStrategy.java:84)
	at org.mockito.internal.invocation.InvocationMatcher.argumentsMatch(InvocationMatcher.java:156)
	at org.mockito.internal.invocation.InvocationMatcher.matches(InvocationMatcher.java:82)
	at org.mockito.internal.invocation.InvocationsFinder$RemoveNotMatching.isOut(InvocationsFinder.java:169)
	at org.mockito.internal.invocation.InvocationsFinder$RemoveNotMatching.isOut(InvocationsFinder.java:161)
	at org.mockito.internal.util.collections.ListUtil.filter(ListUtil.java:21)
	at org.mockito.internal.invocation.InvocationsFinder.findInvocations(InvocationsFinder.java:23)
	at org.mockito.internal.verification.checkers.NumberOfInvocationsChecker.checkNumberOfInvocations(NumberOfInvocationsChecker.java:34)
	at org.mockito.internal.verification.Times.verify(Times.java:39)
	at org.mockito.internal.verification.MockAwareVerificationMode.verify(MockAwareVerificationMode.java:29)
	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:71)
	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:33)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:82)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:56)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptAbstract(MockMethodInterceptor.java:157)
	at org.mockito.codegen.ITransport$MockitoMock$424708305.send(Unknown Source)
	at io.sentry.spring.mvc.SentrySpringIntegrationTest$does not send events for handled exceptions$1.run(SentrySpringIntegrationTest.kt:162)
	at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:222)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:209)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by marandaneto** [comment]
@maciejwalkowiak can you take a look at this? our tests are green but maybe they should not due to this issue

**Comment by maciejwalkowiak** [comment]
Executing test prints errors because `transport#send` is called multiple times, and `check` method from mockito-kotlin calls `printStackTrace()` on assertion error. I don't see how any of these test can be a false posivite, but I agree that having red output in case of successful test is sub-optimal. There are few alternatives, each one with pros & cons:

```kotlin
@Test
fun `attaches transaction name to events`() {
    val restTemplate = TestRestTemplate().withBasicAuth("user", "password")

    restTemplate.getForEntity("http://localhost:$port/throws", String::class.java)

    // verify that `transport.send(...)` was called with an `event` object as an argument having `transaction` set to `GET /throws`.
}
```

The alternatives are:

1. `check` from Mockito-Kotlin or higher level abstraction `checkEvent`:

```kotlin
@Test
fun `attaches transaction name to events`() {
    val restTemplate = TestRestTemplate().withBasicAuth("user", "password")

    restTemplate.getForEntity("http://localhost:$port/throws", String::class.java)

    verify(transport).send(checkEvent {
        assertThat(it.transaction).isEqualTo("GET /throws")
    }, anyOrNull())
}
```

- verifies all invocations of `transport#send`
- prints out to the console all failures
- succeeds if any of invocation is successful
- when test fails, the output contains very detailed information about failure (message from failed assertion)

2. ArgumentCaptor

```kotlin
@Test
fun `attaches transaction name to events`() {
    val restTemplate = TestRestTemplate().withBasicAuth("user", "password")

    restTemplate.getForEntity("http://localhost:$port/throws", String::class.java)

    argumentCaptor<SentryEnvelope>().apply {
        verify(transport, times(2)).send(capture(), anyOrNull())
        assertEvent(firstValue) {
            assertThat(it.transaction).isEqualTo("GET /throws")
        }
    }
}
```
- more boilerplate
- test is more fragile as the invocation order matters
- outputs errors only if the test fails

3. `argThat`

```kotlin
@Test
fun `attaches transaction name to events`() {
    val restTemplate = TestRestTemplate().withBasicAuth("user", "password")

    restTemplate.getForEntity("http://localhost:$port/throws", String::class.java)
    
    verify(transport).send(argThat {
        val event = this.getEvent()
        event != null && event.transaction == "GET /throzws"
    }, anyOrNull())
}
```

with following extension function visible in tests:

```kotlin
fun SentryEnvelope.getEvent(): SentryEvent? {
    val options = SentryOptions().apply {
        setSerializer(GsonSerializer(SentryOptions()))
    }
    return this.items.first().getEvent(options.serializer)
}
```

- verifies all invocations of `transport#send`
- does not print out any failures
- succeeds if any of invocation is successful
- when test fails, the output does not contain detailed information about failure (we don't know which condition is not met if there is more than one condition)

---

I am pretty sure there are other, potentially better ways that I haven't thought about. I am open for suggestions.

**Comment by marandaneto** [comment]
the problem of option 3) is that invocation order matters, due to `this.items.first()`.

I'm wondering if it makes sense to be sure that `transport.send(x)` is called only once by disabling the untested feature.

eg, if you want to test that `TestRestTemplate` captures a transaction, why is it transport being called twice? if it's because it also does a `captureEvent`, is there a way to test in isolation? eg disable transaction when testing `TestRestTemplate` throws and capture an event.

eg disable `captureEvent` feature when testing that `TestRestTemplate` captures a transaction.

so you will need 2 tests for both use cases, but `transport.send(x)` will be called only once, and the test approach does need to be changed, but rather making the tests more specific, does that make sense?

@bruno-garcia opinions?

**Comment by maciejwalkowiak** [comment]
> eg, if you want to test that TestRestTemplate captures a transaction, why is it transport being called twice?

Which method exactly is it? Not every test method is expected to trigger `transport.send` more than once, but in some cases the test tests the scenario where event is triggered within a transaction. 

Since this is an integration test, I am not sure how far we should go with isolating scenarios. It gives confidence that everything works together as expected. Will think about it.

**Comment by marandaneto** [comment]
@maciejwalkowiak in that case maybe we don't use `checkEvent` but rather parse the envelope and assert manually, based on what we know about the envelope (if it has multiple items or not), if `transport.send` has multiple calls or not, its more boilerplate, indeed.
