### ISSUE TITLE
Error not logging to Sentry Dashboard from Java Unit Test File 

### ISSUE THREAD

**Issue by btanmayee** [getsentry/sentry-java#1590]
Hello,

I have an issue with error not logging on Sentry's dashboard from my Java Unit test file.
I got below logs
INFO: No outbox dir path is defined in options.
INFO: GlobalHubMode: 'false'
DEBUG: UncaughtExceptionHandlerIntegration enabled: true
DEBUG: UncaughtExceptionHandlerIntegration installed.
DEBUG: ShutdownHookIntegration installed.
DEBUG: Capturing event: d609b3aa130e4ad7969bfc5325e020c4
INFO: Session is null on scope.withSession
ERROR: Envelope submission failed 
 java.lang.IllegalStateException: Sending the event failed.
java.lang.IllegalStateException: Sending the event failed.
	at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.flush(AsyncHttpTransport.java:229)
	at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.run(AsyncHttpTransport.java:183)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1497)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at io.sentry.transport.HttpConnection.createConnection(HttpConnection.java:145)
	at io.sentry.transport.HttpConnection.send(HttpConnection.java:150)
	at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.flush(AsyncHttpTransport.java:210)
	... 6 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1479)
	... 19 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:145)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
	... 25 more

From the earlier post, I check :- 
1. if certificate is valid.
2. Java version is 1.8
3. Tried to remove .ingest and just put sentry.io
But still issue exists.

And my code looks like as:- 
public void testSentry()  {
    Sentry.init(options -> {
      options.setDsn("dsndetails");
      options.setTracesSampleRate(1.0);
      options.setDebug(true);
      options.setEnableExternalConfiguration(true);
      options.setEnableUncaughtExceptionHandler(true);
    });
    try {
      throw new Exception("This is a test.");
    } catch (Exception e) {
      Sentry.captureException(e);
    }

**Comment by maciejwalkowiak** [comment]
Hello! There can be many reasons not directly related to Sentry. Have you tried solutions that pop-up when you search for `sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`?

Some hints from similar issues reported here:
- which exactly version of Java are you using? Java 1.8.0_261+ should accept the certificate
- use following format for DSN: `https://5fd7a6cda8444965bade9ccfd3df9882@sentry.io/1188141`

**Comment by btanmayee** [comment]
Hello,

Thank you for reply.

Java version is 1.8.0_211 and tried using @sentry.ip from one of the post but didn't work.
So, certificate can be the issue as java version is not 1.8.0_261+ ?

**Comment by maciejwalkowiak** [comment]
Seems, so. With older version you would need to add Sentry certificate to keystore.

**Comment by btanmayee** [comment]
Hello,

Thank you. It is working now, it was my local set up java version, when upgraded to latest java version "1.8.0_291", I was able to see logs errors/messages in Sentry.

Thank you for your help.
