### ISSUE TITLE
tracing functionality's SentryId.fromStringSentryId() throws IAE, causing 500 Internal Server error

### ISSUE THREAD

**Issue by hanswesterbeek** [getsentry/sentry-java#1604]
_Platform:_
- [x ]  Java -> jdk 11
- [x ]  Spring -> Spring Boot 2.4.5

- [x ]  Maven -> 3.6

_Platform installed with:_
- [ x] Maven Central

The version of the SDK:
**5.0.1**

---
I have the following issue:

```
2021-07-15 10:36:30,969 WARN  org.eclipse.jetty.server.HttpChannel     - /customer-service/foo/32454
java.lang.IllegalArgumentException: String representation of SentryId has either 32 (UUID no dashes) or 36 characters long (completed UUID). Received: 00
    at io.sentry.protocol.SentryId.fromStringSentryId(SentryId.java:57)
    at io.sentry.protocol.SentryId.<init>(SentryId.java:24)
    at io.sentry.SentryTraceHeader.<init>(SentryTraceHeader.java:34)
    at io.sentry.spring.tracing.SentryTracingFilter.startTransaction(SentryTracingFilter.java:105)
    at io.sentry.spring.tracing.SentryTracingFilter.doFilterInternal(SentryTracingFilter.java:67)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)
```
I recently enabled tracing and then the above exception started to occur.

A client of my webservice uses sentry-python sdk v 0.11.4 and seems to be sending weird contents in the `sentry-trace` header. I've asked them to upgrade. That may solve the immediate issue but still the implementation here still seems vulnerable.

**Steps to reproduce:**
- Make a request with weird content in the `sentry-trace` header.

**Actual result:**
- 500 internal server error, business code is not invoked since execution fails in `SentryTracingFilter`.

**Expected result:**
- Sentry should give up on the tracing if the contents of `sentry-trace` header are invalid, and must not throw `IllegalArgumentException`, allowing regular business-processing to continue.

**Comment by maciejwalkowiak** [comment]
Thanks for reporting @hanswesterbeek
