### ISSUE TITLE
Spring Boot War Application not starting after integrating Sentry

### ISSUE THREAD

**Issue by deependrasolanky** [getsentry/sentry-java#1677]
_Platform:_
- [x]  Spring

_IDE:_
- [X]  IntelliJ 

_Build system:_
- [x]  Maven

The version of the SDK:
**5.1.1**

---
I have the following issue:

**Steps to reproduce:**
- Spring Boot Application works fine in development on local system. But application is not being started after deploying  as War file on Tomcat 8.5

**Actual result:**
- Application not started.  **org.apache.catalina.core.StandardContext.filterStart Exception starting filter [sentryUserFilter]**

**Expected result:**
- Application should start and exceptions should be captured by Sentry.

**Comment by marandaneto** [comment]
@deependrasolanky thanks for reporting, can you post the error stack trace? and what's the version of the Spring Boot? thanks

**Comment by deependrasolanky** [comment]
> @deependrasolanky thanks for reporting, can you post the error stack trace? and what's the version of the Spring Boot? thanks

Thank you for your response. 
**Spring Boot Version 2.5.4**
Error Stack Trace
```
24-Aug-2021 12:51:14.906 SEVERE [localhost-startStop-21] org.apache.catalina.core.StandardContext.filterStart Exception starting filter [sentryUserFilter]
	java.lang.AbstractMethodError
		at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:282)
		at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:110)
		at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4608)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5258)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:755)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:729)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:695)
		at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1016)
		at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1903)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
```

**Comment by luizfp** [comment]
Similar problem here!

Application .war is successfully deployed but all requests fail.

Also using 5.1.1 and tomcat 8.

**Comment by marandaneto** [comment]
@maciejwalkowiak can you check this out? thanks
