### ISSUE TITLE
Sentry Migration Issue 1.7.30 To 5.1.1 it Unable to Start Tomcat Server if i change Sentry Version 5.1.1

### ISSUE THREAD

**Issue by mjd3253** [getsentry/sentry-java#1678]
_Platform:_

- [ ]  Java -> 11
- [ ]  Logback -> io.sentry:sentry-spring-boot-starter:5.1.1
- [ ]  Sentry -> io.sentry:sentry-logback:5.1.1
- [ ]  Spring Boot -> 1.4

_IDE:_
- [ ]  IntelliJ -> 2021.2

_Build system:_
- [ ]  Gradle -> 6

---
I have the following issue:

java.lang.IllegalStateException: Error processing condition on io.sentry.spring.boot.SentryAutoConfiguration$HubConfiguration$SentryWebMvcConfiguration.sentryTracingFilter
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:64) ~[spring-boot-autoconfigure-1.5.20.RELEASE.jar:1.5.20.RELEASE]
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:102) ~[spring-context-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinitionReader.java:179) ~[spring-context-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:140) ~[spring-context-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:116) ~[spring-context-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:320) ~[spring-context-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:228) ~[spring-context-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:272) ~[spring-context-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:92) ~[spring-context-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:687) ~[spring-context-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:524) ~[spring-context-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:124) ~[spring-boot-1.5.20.RELEASE.jar:1.5.20.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) ~[spring-boot-1.5.20.RELEASE.jar:1.5.20.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) ~[spring-boot-1.5.20.RELEASE.jar:1.5.20.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) ~[spring-boot-1.5.20.RELEASE.jar:1.5.20.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) ~[spring-boot-1.5.20.RELEASE.jar:1.5.20.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) ~[spring-boot-1.5.20.RELEASE.jar:1.5.20.RELEASE]
	at com.trackimo.server.TrackimoServerApplication.main(TrackimoServerApplication.java:35) ~[main/:na]
Caused by: java.lang.reflect.MalformedParameterizedTypeException: null
	at java.base/sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.validateConstructorArguments(ParameterizedTypeImpl.java:59) ~[na:na]
	at java.base/sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.<init>(ParameterizedTypeImpl.java:52) ~[na:na]
	at java.base/sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.make(ParameterizedTypeImpl.java:93) ~[na:na]
	at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeParameterizedType(CoreReflectionFactory.java:105) ~[na:na]
	at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:140) ~[na:na]
	at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49) ~[na:na]
	at java.base/sun.reflect.generics.repository.MethodRepository.computeReturnType(MethodRepository.java:75) ~[na:na]
	at java.base/sun.reflect.generics.repository.MethodRepository.getReturnType(MethodRepository.java:66) ~[na:na]
	at java.base/java.lang.reflect.Method.getGenericReturnType(Method.java:292) ~[na:na]
	at org.springframework.core.MethodParameter.getGenericParameterType(MethodParameter.java:389) ~[spring-core-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at org.springframework.core.SerializableTypeWrapper$MethodParameterTypeProvider.getType(SerializableTypeWrapper.java:338) ~[spring-core-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at org.springframework.core.SerializableTypeWrapper.forTypeProvider(SerializableTypeWrapper.java:146) ~[spring-core-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at org.springframework.core.ResolvableType.forType(ResolvableType.java:1346) ~[spring-core-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at org.springframework.core.ResolvableType.forMethodParameter(ResolvableType.java:1249) ~[spring-core-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at org.springframework.core.ResolvableType.forMethodParameter(ResolvableType.java:1217) ~[spring-core-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at org.springframework.core.ResolvableType.forMethodReturnType(ResolvableType.java:1160) ~[spring-core-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryMethod(AbstractAutowireCapableBeanFactory.java:759) ~[spring-beans-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:638) ~[spring-beans-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:607) ~[spring-beans-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1496) ~[spring-beans-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1018) ~[spring-beans-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry.addBeanTypeForNonAliasDefinition(BeanTypeRegistry.java:222) ~[spring-boot-autoconfigure-1.5.20.RELEASE.jar:1.5.20.RELEASE]
	at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry.addBeanTypeForNonAliasDefinition(BeanTypeRegistry.java:198) ~[spring-boot-autoconfigure-1.5.20.RELEASE.jar:1.5.20.RELEASE]
	at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry.addBeanType(BeanTypeRegistry.java:191) ~[spring-boot-autoconfigure-1.5.20.RELEASE.jar:1.5.20.RELEASE]
	at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry.updateTypesIfNecessary(BeanTypeRegistry.java:178) ~[spring-boot-autoconfigure-1.5.20.RELEASE.jar:1.5.20.RELEASE]
	at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry.getNamesForType(BeanTypeRegistry.java:114) ~[spring-boot-autoconfigure-1.5.20.RELEASE.jar:1.5.20.RELEASE]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.collectBeanNamesForType(OnBeanCondition.java:186) ~[spring-boot-autoconfigure-1.5.20.RELEASE.jar:1.5.20.RELEASE]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getBeanNamesForType(OnBeanCondition.java:172) ~[spring-boot-autoconfigure-1.5.20.RELEASE.jar:1.5.20.RELEASE]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchingBeans(OnBeanCondition.java:140) ~[spring-boot-autoconfigure-1.5.20.RELEASE.jar:1.5.20.RELEASE]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchOutcome(OnBeanCondition.java:79) ~[spring-boot-autoconfigure-1.5.20.RELEASE.jar:1.5.20.RELEASE]
	at org.springframework.boot.autoconfigure.condition.AbstractNestedCondition$MemberOutcomes.getConditionOutcome(AbstractNestedCondition.java:194) ~[spring-boot-autoconfigure-1.5.20.RELEASE.jar:1.5.20.RELEASE]
	at org.springframework.boot.autoconfigure.condition.AbstractNestedCondition$MemberOutcomes.<init>(AbstractNestedCondition.java:187) ~[spring-boot-autoconfigure-1.5.20.RELEASE.jar:1.5.20.RELEASE]
	at org.springframework.boot.autoconfigure.condition.AbstractNestedCondition$MemberConditions.getMatchOutcomes(AbstractNestedCondition.java:165) ~[spring-boot-autoconfigure-1.5.20.RELEASE.jar:1.5.20.RELEASE]
	at org.springframework.boot.autoconfigure.condition.AbstractNestedCondition$MemberMatchOutcomes.<init>(AbstractNestedCondition.java:80) ~[spring-boot-autoconfigure-1.5.20.RELEASE.jar:1.5.20.RELEASE]
	at org.springframework.boot.autoconfigure.condition.AbstractNestedCondition.getMatchOutcome(AbstractNestedCondition.java:64) ~[spring-boot-autoconfigure-1.5.20.RELEASE.jar:1.5.20.RELEASE]
	at org.springframework.boot.autoconfigure.condition.AnyNestedCondition.getMatchOutcome(AnyNestedCondition.java:57) ~[spring-boot-autoconfigure-1.5.20.RELEASE.jar:1.5.20.RELEASE]
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47) ~[spring-boot-autoconfigure-1.5.20.RELEASE.jar:1.5.20.RELEASE]
	... 17 common frames omitted

2021-08-24 18:41:12.164  INFO 23861 --- [           main] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@1ba359bd: startup date [Tue Aug 24 18:41:10 IST 2021]; root of context hierarchy
2021-08-24 18:41:12.165  WARN 23861 --- [           main] o.s.boot.SpringApplication               : Unable to close ApplicationContext

java.lang.reflect.MalformedParameterizedTypeException: null
	at java.base/sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.validateConstructorArguments(ParameterizedTypeImpl.java:59) ~[na:na]
	at java.base/sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.<init>(ParameterizedTypeImpl.java:52) ~[na:na]
	at java.base/sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.make(ParameterizedTypeImpl.java:93) ~[na:na]
	at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeParameterizedType(CoreReflectionFactory.java:105) ~[na:na]
	at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:140) ~[na:na]
	at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49) ~[na:na]
	at java.base/sun.reflect.generics.repository.MethodRepository.computeReturnType(MethodRepository.java:75) ~[na:na]
	at java.base/sun.reflect.generics.repository.MethodRepository.getReturnType(MethodRepository.java:66) ~[na:na]
	at java.base/java.lang.reflect.Method.getGenericReturnType(Method.java:292) ~[na:na]
	at org.springframework.core.MethodParameter.getGenericParameterType(MethodParameter.java:389) ~[spring-core-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at org.springframework.core.SerializableTypeWrapper$MethodParameterTypeProvider.getType(SerializableTypeWrapper.java:338) ~[spring-core-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at org.springframework.core.SerializableTypeWrapper.forTypeProvider(SerializableTypeWrapper.java:146) ~[spring-core-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at org.springframework.core.ResolvableType.forType(ResolvableType.java:1346) ~[spring-core-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at org.springframework.core.ResolvableType.forMethodParameter(ResolvableType.java:1249) ~[spring-core-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at org.springframework.core.ResolvableType.forMethodParameter(ResolvableType.java:1217) ~[spring-core-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at org.springframework.core.ResolvableType.forMethodReturnType(ResolvableType.java:1160) ~[spring-core-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryMethod(AbstractAutowireCapableBeanFactory.java:759) ~[spring-beans-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:638) ~[spring-beans-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:607) ~[spring-beans-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1496) ~[spring-beans-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:425) ~[spring-beans-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:395) ~[spring-beans-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:515) ~[spring-beans-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:508) ~[spring-beans-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBeansOfType(AbstractApplicationContext.java:1190) ~[spring-context-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.springframework.boot.SpringApplication.getExitCodeFromMappedException(SpringApplication.java:818) ~[spring-boot-1.5.20.RELEASE.jar:1.5.20.RELEASE]
	at org.springframework.boot.SpringApplication.getExitCodeFromException(SpringApplication.java:804) ~[spring-boot-1.5.20.RELEASE.jar:1.5.20.RELEASE]
	at org.springframework.boot.SpringApplication.handleExitCode(SpringApplication.java:790) ~[spring-boot-1.5.20.RELEASE.jar:1.5.20.RELEASE]
	at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:744) ~[spring-boot-1.5.20.RELEASE.jar:1.5.20.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) ~[spring-boot-1.5.20.RELEASE.jar:1.5.20.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) ~[spring-boot-1.5.20.RELEASE.jar:1.5.20.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) ~[spring-boot-1.5.20.RELEASE.jar:1.5.20.RELEASE]
	at com.trackimo.server.TrackimoServerApplication.main(TrackimoServerApplication.java:35) ~[main/:na]

The description goes here ...
right now i migrate sentry version 1.7.30 to 5.1.1 but it complaining error like about  and it stopped tomcat server 
i m unable to understand it spring boot version issue. 

**Steps to reproduce:**
- Migrate Sentry Version 1.7.3 To 5.1.1

**Actual result:**
-  Error processing condition on Error

**Expected result:**
- Should run

**Comment by marandaneto** [comment]
the minimal version of the supported Spring Boot is 2.1 and above, see https://docs.sentry.io/platforms/java/guides/spring-boot/
please either upgrade your Spring Boot version or keep using the old version of the Sentry Java SDK
