### ISSUE TITLE
Sentry init is causing ANRs in our Android app

### ISSUE THREAD

**Issue by dlew** [getsentry/sentry-java#1862]
_Platform:_
- [ x ]  Android -> compileSdkVersion/targetSdkVersion == 31
- [ x ]  Kotlin -> Kotlin 1.5.31, jvmTarget 1.8
- [ x ]  Timber -> 5.0.1

_Build system:_
- [ X ]  Gradle -> 7.3.3

_Android Gradle Plugin:_
- [ x ]  Yes -> 7.0.3

_Proguard/R8:_
- [ x ]  Enabled

_Platform installed with:_
- [ x ] Maven Central

The version of the SDK:
**5.4.3**

---
I have the following issue:

We've been running Crashlytics ANR detection and our highest ANR comes from Sentry's initialization. The stack trace looks like this:

```
main (timed waiting): tid=1 systid=28116
       at sun.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2109)
       at java.util.concurrent.ThreadPoolExecutor.awaitTermination(ThreadPoolExecutor.java:1486)
       at io.sentry.transport.AsyncHttpTransport.close(AsyncHttpTransport.java:121)
       at io.sentry.SentryClient.close(SentryClient.java:580)
       at io.sentry.Hub.close(Hub.java:279)
       at io.sentry.Sentry.init(Sentry.java:181)
       at io.sentry.Sentry.init(Sentry.java:117)
       at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:71)
       at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:52)
       at com.trello.feature.sentry.ActualSentry.initialize(ActualSentry.kt:17)
       at com.trello.app.TrelloApplication.initialize(TrelloApplication.kt:139)
       at com.trello.app.TrelloApplication.onCreate(TrelloApplication.kt:76)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1208)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7006)
       at android.app.ActivityThread.access$1800(ActivityThread.java:274)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2104)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:233)
       at android.app.ActivityThread.main(ActivityThread.java:8030)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

**Steps to reproduce:**
- Use manual initialization (`SentryAndroid.init(context)`) on startup in `Application.onCreate()`.

**Actual result:**
- ANRs.

**Expected result:**
- No ANRs from init.

**Comment by marandaneto** [comment]
@dlew since you are initing the SDK manually, have you disabled the automatic init.? https://docs.sentry.io/platforms/android/configuration/manual-init/

> at io.sentry.Hub.close(Hub.java:279)

The SDK is closing itself and awaiting its resources to be cleared up.

**Comment by dlew** [comment]
Ah, that is indeed the problem! I no longer see us closing `Hub.close()` when I disable automatic init. Thanks for the pointer!

**Comment by robertocapah** [comment]
hey @dlew can you please explain more details. I already put in Manifest file 
`<meta-data android:name="io.sentry.auto-init" android:value="false" />`. I assume that I already disable auto-init sentry
but the ANR from crashlytic report remain the same.

**Comment by dlew** [comment]
@robertocapah I don't have much to add - all we did was add that to the manifest and it fixed our problem. You may have a different problem than we encountered.

Two random ideas you could try...

- You could check [the manifest merger](https://developer.android.com/studio/build/manage-manifests#inspect_the_merged_manifest_and_find_conflicts) to see if maybe you've got some hijinks re-adding auto-init back to your manifest.

- You could throw a debugger onto `SentryAndroid.init()` to see if it's called more than once and where that's happening.
