### ISSUE TITLE
Java SDK is using not exported components of com.google.gson

### ISSUE THREAD

**Issue by BamButz** [getsentry/sentry-java#1869]
_Platform:_
- [ ]  Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version?
- [x]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version? 17
- [ ]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [ ]  NDK -> If yes, which NDK/CMake version?
- [ ]  React-Native -> If yes, which version?
- [ ]  Timber -> If yes, which version?
- [ ]  Log4j2 -> If yes, which version?
- [ ]  Logback -> If yes, which version?
- [ ]  Spring -> If yes, which version?

_IDE:_
- [ ]  Android Studio -> If yes, which version?
- [x]  IntelliJ -> If yes, which version? 2021.3.1
- [ ]  Other -> If yes, which one?

_Build system:_
- [x]  Gradle -> If yes, which version? 7.3.3
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [ ]  Maven -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [x]  No

_Sentry Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [x]  No

_Proguard/R8:_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [ ] JCenter
- [ ] Bintray
- [x] Maven Central
- [ ] Manually

The version of the SDK:
**5.5.2**

---
I have the following issue:

The Java SDK is using internal (with modules active not accessible) components of com.google.gson and which is why the exception posted below is thrown.
I recommend to remove the usage of the internal component (com.google.gson.internal.Excluder)

**Steps to reproduce:**
- Create new project with a module-info.java included
- Include sentry and run the example

``` java
Sentry.init(options -> {
            options.setDsn("https://xxx@xxx/xxx");
            // Set tracesSampleRate to 1.0 to capture 100% of transactions for performance monitoring.
            // We recommend adjusting this value in production.
            options.setTracesSampleRate(1.0);
            // When first trying Sentry it's good to see what the SDK is doing:
            options.setDebug(true);
        });

        try {
            throw new Exception("This is a test.");
        } catch (Exception e) {
            Sentry.captureException(e);
        }
```

**Actual result:**
```
java.lang.IllegalAccessError: class io.sentry.UnknownPropertiesTypeAdapterFactory$UnknownPropertiesTypeAdapter (in module sentry) cannot access class com.google.gson.internal.Excluder (in module com.google.gson) because module com.google.gson does not export com.google.gson.internal to module sentry
	at sentry@5.5.1/io.sentry.UnknownPropertiesTypeAdapterFactory$UnknownPropertiesTypeAdapter.getPropertyNames(UnknownPropertiesTypeAdapterFactory.java:91)
	at sentry@5.5.1/io.sentry.UnknownPropertiesTypeAdapterFactory$UnknownPropertiesTypeAdapter.create(UnknownPropertiesTypeAdapterFactory.java:76)
Failed to create envelope item. Dropping it.

	at sentry@5.5.1/io.sentry.UnknownPropertiesTypeAdapterFactory$UnknownPropertiesTypeAdapter.access$000(UnknownPropertiesTypeAdapterFactory.java:58)
	at sentry@5.5.1/io.sentry.UnknownPropertiesTypeAdapterFactory.create(UnknownPropertiesTypeAdapterFactory.java:51)
	at com.google.gson@2.8.9/com.google.gson.Gson.getAdapter(Gson.java:489)
	at com.google.gson@2.8.9/com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)
	at com.google.gson@2.8.9/com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)
	at com.google.gson@2.8.9/com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
	at com.google.gson@2.8.9/com.google.gson.Gson.getDelegateAdapter(Gson.java:572)
	at sentry@5.5.1/io.sentry.UnknownPropertiesTypeAdapterFactory.create(UnknownPropertiesTypeAdapterFactory.java:44)
	at com.google.gson@2.8.9/com.google.gson.Gson.getAdapter(Gson.java:489)
	at com.google.gson@2.8.9/com.google.gson.Gson.toJson(Gson.java:727)
	at com.google.gson@2.8.9/com.google.gson.Gson.toJson(Gson.java:714)
	at com.google.gson@2.8.9/com.google.gson.Gson.toJson(Gson.java:669)
	at com.google.gson@2.8.9/com.google.gson.Gson.toJson(Gson.java:649)
	at sentry@5.5.1/io.sentry.GsonSerializer.serialize(GsonSerializer.java:143)
	at sentry@5.5.1/io.sentry.SentryEnvelopeItem.lambda$fromEvent$3(SentryEnvelopeItem.java:109)
	at sentry@5.5.1/io.sentry.SentryEnvelopeItem$CachedItem.getBytes(SentryEnvelopeItem.java:256)
	at sentry@5.5.1/io.sentry.SentryEnvelopeItem.lambda$fromEvent$5(SentryEnvelopeItem.java:122)
	at sentry@5.5.1/io.sentry.SentryEnvelopeItem.getData(SentryEnvelopeItem.java:56)
	at sentry@5.5.1/io.sentry.GsonSerializer.serialize(GsonSerializer.java:173)
	at sentry@5.5.1/io.sentry.transport.HttpConnection.send(HttpConnection.java:155)
	at sentry@5.5.1/io.sentry.transport.AsyncHttpTransport$EnvelopeSender.flush(AsyncHttpTransport.java:210)
	at sentry@5.5.1/io.sentry.transport.AsyncHttpTransport$EnvelopeSender.run(AsyncHttpTransport.java:183)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Expected result:**
- To send the captured exception

**Comment by romtsn** [comment]
The problem is that the `gson` dependency got resolved to 2.8.9 in your build, although we are relying on version 2.8.5 - if you don't care about  which gson version you're using, I'd recommend to force it to 2.8.5, because we are going to get rid of gson in the future major version. 

You can also try our `6.0.0-alpha.1` release, which doesn't depend on gson anymore, hence the issue should be gone.

**Comment by BamButz** [comment]
Ah okay, I wasn't aware that the 6.0.0 dependency will be removed. Thanks for the information, then I'll close the issue.

**Comment by bruno-garcia** [comment]
We're also keen to get feedback on 6.0.0 as we close in to making it GA.
