### ISSUE TITLE
How does isInApp work?

### ISSUE THREAD

**Issue by theindexer** [getsentry/sentry-java#1879]
In the StackTraceFactory, [isInApp](https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/SentryStackTraceFactory.java#L76) appears that it should return false for everything if you haven't set any includes or excludes. Looking at the python version, I see that it inverts everything to "inApp" if nothing is set to inApp so maybe something similar happens somewhere down the line here?
Anyway, does adding any inAppExcludes have any effect? Looking at the code, if it doesn't match an exclude it still returns false. So the only way to get any different behavior at all is to specify inAppIncludes, which has the effect of excluding everything outside of it.

This reading of the code is supported by the traces that show up in my sentry instance, which exhibit no different behavior with or without inAppExcludes but start excluding with prejudice once I add inAppIncludes for anything in the stack frame.

My desired behavior is that everything is allowed by default, but log4j frames (and ideally my frame with hub.captureEvent coming from within my application code) stop showing up when calling `logger.error("send to sentry");` and I thought that inAppExcludes would accomplish that but it doesn't seem to be the case.

Am I misunderstanding how this works and do you have any suggestions?
Thanks!

**Comment by marandaneto** [comment]
> In the StackTraceFactory, isInApp appears that it should return false for everything if you haven't set any includes or excludes

That's correct.

> I see that it inverts everything to "inApp" if nothing is set to inApp so maybe something similar happens somewhere down the line here?

I don't think so, the difference is that at least on Android, we're able to add the App's package as inAppIncludes by default.
If you look at our samples, https://github.com/getsentry/sentry-java/blob/main/sentry-samples/sentry-samples-console/src/main/java/io/sentry/samples/console/Main.java#L63-L68
We're always adding the App's package as inAppIncludes, since we can't detect it automatically.

> Anyway, does adding any inAppExcludes have any effect? Looking at the code, if it doesn't match an exclude it still returns false. So the only way to get any different behavior at all is to specify inAppIncludes, which has the effect of excluding everything outside of it.

That makes sense, inAppExcludes only has effect when there's a inAppIncludes at least.

> My desired behavior is that everything is allowed by default, but log4j frames (and ideally my frame with hub.captureEvent coming from within my application code) stop showing up when calling logger.error("send to sentry"); and I thought that inAppExcludes would accomplish that but it doesn't seem to be the case.

I'm not sure that I understand the use case, can you elaborate? give package names examples which is supposed to be inApp or not?
Maybe all you need to do is to add your package's name as inAppIncludes and exclude what you don't want with inAppExcludes

**Comment by theindexer** [comment]
Ah, for context this is not an Android app.

> That makes sense, inAppExcludes only has an effect when there's an inAppIncludes at least.
The documentation states that inAppIncludes overrides inAppExcludes. From that, I don't think it's intuitive that you have to provide inAppIncludes to make inAppExcludes work. Also, it still feels like inAppExcludes doesn't have any effect regardless.
The first two tests of inAppExcludes https://github.com/getsentry/sentry-java/blob/main/sentry/src/test/java/io/sentry/SentryStackTraceFactoryTest.kt#L59 both exhibit the same behavior - "inApp should be false if prefix matches it", "inApp should be false if prefix doesnt matches it". You could just remove the inAppExcludes logic and still pass these tests.

> I'm not sure that I understand the use case, can you elaborate? give package names examples which is supposed to be inApp or not?
Maybe all you need to do is to add your package's name as inAppIncludes and exclude what you don't want with inAppExcludes

I have the following stack trace in sentry.
```
    at com.x.MySentry.createEvent(MySentry.java:195)
    at com.x.MySentry.append(MySentry.java:131)
    at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)
    at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
    at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
    at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
    at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:542)
    at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:500)
    at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:483)
    at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
    at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)
    at org.apache.logging.log4j.core.Logger.log(Logger.java:161)
    at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205)
    at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159)
    at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142)
    at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2017)
    at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1983)
    at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:740)
    at com.x.somepackage.impl.SomeImplementation.errorLoggingMethod(SomeImplementation.java:168)
    ...more in app code...
```
Ideally the trace would start at the second-to-last line with `errorLoggingMethod`, and not include the log4j internals or my Sentry appender. I can add `com.x` to `inAppIncludes` but then there's no way to filter out `com.x.MySentry`. The actual package organization is much broader and nestier and including everything except sentry wouldn't be practical.
As an okay solution, I can just add `com.x` to `inAppIncludes` but then I have to track down the other random packages that are technically "in app" that are laying around. I guess that's ok, but the [docs](https://docs.sentry.io/platforms/java/configuration/options/#in-app-exclude) didn't make that clear to me.

Thanks for the quick reply!

**Comment by marandaneto** [comment]
@theindexer gotcha, thanks for the info.

The docs state:

> The application package is automatically marked as inApp

And that's true when possible (e.g. Android apps) but not for Java Apps, maybe the docs should mention that.
You can also mutate the whole event including the `inApp` flag (only from the frames you want) using the `beforeSend` callback https://docs.sentry.io/platforms/java/configuration/filtering/#filtering-error-events or even EventProcessors

Since Java/Android has the concept of packages, it can be detected automatically or added with a one-liner, being `inApp=false` by default makes more sense, so it works as intended.

Actually, it was `inApp=true` by default previously and people always needed to add a bunch of `inAppExcludes` so it made more sense to reverse it.

Thanks for the feedback.

**Comment by theindexer** [comment]
I'll look into the callback/processor situation, sounds perfect. Thanks again! Also, I messed up the formatting of my above one and accidentally quoted new text I wrote. Still kinda thinking that `inAppExcludes` is a deprecated attribute at this point but my actual issue is resolved.

**Comment by theindexer** [comment]
> [@theindexer](https://github.com/theindexer) what solution did you go with in the end for this?

@stwr667 I don't job at the place that prompted me to post this anymore so I can't check. My guess is I went with mutating the event in `beforeSend` as it sounds vaguely familiar. Or I gave up. As much as it bothers me to have useless stack trace lines and I'm convinced devs would be more likely to read them if they were all relevant, I don't actually have any data to back that up 🙃. A dev can dream...

**Comment by stwr667** [comment]
Ok thanks @theindexer. I got it working just now using `options.setBeforeSend`. Here's the code for future travellers who want to remove the ~10 superfluous lines of Log4J Appender logging. 90% of it's null-checking! 😆 

```java
private static void removeSuperfluousLinesFromStacktrace(final @NotNull SentryEvent event) {
    if (event.getThreads() == null) {
        return;
    }

    event.getThreads().forEach(thread -> {
        if (thread.getStacktrace() == null || thread.getStacktrace().getFrames() == null) {
            return;
        }

        thread.getStacktrace().getFrames().removeIf(frame ->
                frame.getModule() != null && frame.getModule().contains("org.apache.logging")
        );
    });
}
```

![Image](https://github.com/user-attachments/assets/5d1eeeb2-e30e-4e8b-9dcd-e05232d1893b)
