### ISSUE TITLE
Envelope submission failed (The transport failed to send the envelope with response code 403)

### ISSUE THREAD

**Issue by keikoang** [getsentry/sentry-java#1999]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

7.0.4

### Proguard

Enabled

### Version

5.7.3

### Steps to Reproduce

1. I followed the Android guidelines from [here](https://docs.sentry.io/platforms/android/). 
2. I'm on the latest Sentry Android version (5.7.3) and on Sentry server 21.1.0 (as can be seen from dashboard) 
![image](https://user-images.githubusercontent.com/49680260/164231946-fa0e3f0f-680a-4407-8761-bb4a34f43fc0.png)
2. I tried BOTH manual configuration and also configuration via _AndroidManifest.xml_. From the screenshot below, you can see how it is configured at the moment: 
![image](https://user-images.githubusercontent.com/49680260/164232646-38fd823a-8388-400f-b391-42bb431be7d9.png)

![image](https://user-images.githubusercontent.com/49680260/164232606-f9f17d39-4fa9-4ea7-9762-ae3658e3a659.png)
3. Try throwing simple exception and it is not shown on Sentry dashboard
![image](https://user-images.githubusercontent.com/49680260/164234485-c5b6135a-0783-46e2-a181-b9a80457d150.png)

4. Got these error messages every time after trying to initialize the SDK, when calling all Sentry capture functions (which resulted to the actual errors not being shown on Sentry dashboard):
```
2022-04-20 14:16:09.444 29030-29857/APPNAME D/Sentry: Request failed, API returned 403
2022-04-20 14:16:09.447 29030-29857/APPNAME D/Sentry: <html>
    <head><title>403 Forbidden</title></head>
    <body>
    <center><h1>403 Forbidden</h1></center>
    <hr><center>nginx/1.19.10</center>
    </body>
    </html>
2022-04-20 14:16:09.447 29030-29857/APPNAME D/Sentry: The transport failed to send the envelope with response code 403
2022-04-20 14:16:09.447 29030-29857/APPNAME E/Sentry: Envelope submission failed
    java.lang.IllegalStateException: The transport failed to send the envelope with response code 403
        at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.flush(AsyncHttpTransport.java:220)
        at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.run(AsyncHttpTransport.java:183)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

### Expected Result

Sentry Id is created after capturing events and exceptions, so we expect them to show up on Sentry dashboard.

### Actual Result

Sentry errors are not shown on dashboard due to errors we got. Full logs can be seen here:
```
2022-04-20 14:57:24.943 31264-31383/APPNAME E/Sentry: Envelope submission failed
2022-04-20 14:57:24.943 31264-31383/APPNAME E/Sentry: Envelope submission failed
2022-04-20 14:57:26.530 29553-29553/APPNAME D/Sentry: io.sentry.auto-init read: false
2022-04-20 14:57:26.530 29553-29553/APPNAME I/Sentry: Retrieving auto-init from AndroidManifest.xml
2022-04-20 14:57:26.628 29553-29553/APPNAME D/Sentry: io.sentry.debug.level read: debug
2022-04-20 14:57:26.629 29553-29553/APPNAME D/Sentry: io.sentry.anr.enable read: true
2022-04-20 14:57:26.629 29553-29553/APPNAME D/Sentry: io.sentry.session-tracking.enable read: true
2022-04-20 14:57:26.629 29553-29553/APPNAME D/Sentry: io.sentry.auto-session-tracking.enable read: true
2022-04-20 14:57:26.629 29553-29553/APPNAME D/Sentry: io.sentry.sample-rate read: -1.0
2022-04-20 14:57:26.629 29553-29553/APPNAME D/Sentry: io.sentry.anr.report-debug read: false
2022-04-20 14:57:26.629 29553-29553/APPNAME D/Sentry: io.sentry.anr.timeout-interval-millis read: 5000
2022-04-20 14:57:26.629 29553-29553/APPNAME D/Sentry: io.sentry.dsn read: XXX
2022-04-20 14:57:26.629 29553-29553/APPNAME D/Sentry: io.sentry.ndk.enable read: true
2022-04-20 14:57:26.629 29553-29553/APPNAMED/Sentry: io.sentry.ndk.scope-sync.enable read: false
2022-04-20 14:57:26.629 29553-29553/APPNAME D/Sentry: io.sentry.release read: null
2022-04-20 14:57:26.629 29553-29553/APPNAME D/Sentry: io.sentry.environment read: null
2022-04-20 14:57:26.629 29553-29553/APPNAME D/Sentry: io.sentry.session-tracking.timeout-interval-millis read: 30000
2022-04-20 14:57:26.629 29553-29553/APPNAME D/Sentry: io.sentry.breadcrumbs.activity-lifecycle read: true
2022-04-20 14:57:26.629 29553-29553APPNAME D/Sentry: io.sentry.breadcrumbs.app-lifecycle read: true
2022-04-20 14:57:26.629 29553-29553/APPNAME D/Sentry: io.sentry.breadcrumbs.system-events read: true
2022-04-20 14:57:26.630 29553-29553/APPNAME D/Sentry: io.sentry.breadcrumbs.app-components read: true
2022-04-20 14:57:26.630 29553-29553/APPNAME D/Sentry: io.sentry.breadcrumbs.user-interaction read: true
2022-04-20 14:57:26.630 29553-29553/APPNAME D/Sentry: io.sentry.uncaught-exception-handler.enable read: true
2022-04-20 14:57:26.630 29553-29553/APPNAME D/Sentry: io.sentry.attach-threads read: false
2022-04-20 14:57:26.630 29553-29553/APPNAME D/Sentry: io.sentry.traces.sample-rate read: -1.0
2022-04-20 14:57:26.630 29553-29553/APPNAME D/Sentry: io.sentry.traces.trace-sampling read: false
2022-04-20 14:57:26.630 29553-29553/APPNAME D/Sentry: io.sentry.traces.activity.enable read: true
2022-04-20 14:57:26.630 29553-29553/APPNAME D/Sentry: io.sentry.traces.activity.auto-finish.enable read: true
2022-04-20 14:57:26.630 29553-29553/APPNAME D/Sentry: io.sentry.traces.tracing-origins read: null
2022-04-20 14:57:26.630 29553-29553/APPNAME D/Sentry: io.sentry.proguard-uuid read: null
2022-04-20 14:57:26.630 29553-29553/APPNAME I/Sentry: Retrieving configuration from AndroidManifest.xml
2022-04-20 14:57:26.635 29553-29553/APPNAME I/Sentry: sentry-debug-meta.properties file was not found.
2022-04-20 14:57:26.637 29553-29553/APPNAME I/Sentry: Initializing SDK with DSN: XXX
2022-04-20 14:57:26.637 29553-31785APPNAME D/Sentry: SU isn't found on this Device.
2022-04-20 14:57:26.637 29553-29553/APPNAME I/Sentry: GlobalHubMode: 'true'
2022-04-20 14:57:26.641 29553-29553/APPNAME D/Sentry: UncaughtExceptionHandlerIntegration enabled: true
2022-04-20 14:57:26.641 29553-29553/APPNAME D/Sentry: default UncaughtExceptionHandler class='com.google.firebase.crashlytics.internal.common.CrashlyticsUncaughtExceptionHandler'
2022-04-20 14:57:26.641 29553-29553/APPNAME D/Sentry: UncaughtExceptionHandlerIntegration installed.
2022-04-20 14:57:26.641 29553-29553/APPNAME D/Sentry: ShutdownHookIntegration installed.
2022-04-20 14:57:26.642 29553-29553/APPNAME D/Sentry: SendCachedEventFireAndForgetIntegration installed.
2022-04-20 14:57:26.642 29553-29553/APPNAME D/Sentry: NdkIntegration enabled: true
2022-04-20 14:57:26.642 29553-31787/APPNAME D/Sentry: Started processing cached files from /XXX/cache/sentry
2022-04-20 14:57:26.642 29553-31787/APPNAME D/Sentry: Processing dir. /XXX/cache/sentry
2022-04-20 14:57:26.642 29553-29553/APPNAME I/sentry-native: using database path "/XXX/cache/sentry/.sentry-native"
2022-04-20 14:57:26.642 29553-31787/APPNAME D/Sentry: Processing 0 items from cache dir /XXX/cache/sentry
2022-04-20 14:57:26.642 29553-29553/APPNAME D/sentry-native: starting backend
2022-04-20 14:57:26.642 29553-31787/APPNAME D/Sentry: File /XXX/cache/sentry/outbox is not a File.
2022-04-20 14:57:26.642 29553-31787APPNAME D/Sentry: File /XXX/cache/sentry/.sentry-native is not a File.
2022-04-20 14:57:26.642 29553-31787/APPNAME D/Sentry: Finished processing cached files from /XXX/cache/sentry
2022-04-20 14:57:26.643 29553-29553/APPNAME D/Sentry: NdkIntegration installed.
2022-04-20 14:57:26.643 29553-29553/APPNAME D/Sentry: Registering EnvelopeFileObserverIntegration for path: /XXX/cache/sentry/outbox
2022-04-20 14:57:26.643 29553-29553/APPNAME D/Sentry: EnvelopeFileObserverIntegration installed.
2022-04-20 14:57:26.643 29553-29553/APPNAME D/Sentry: SendCachedEventFireAndForgetIntegration installed.
2022-04-20 14:57:26.643 29553-31787APPNAME D/Sentry: Started processing cached files from /XXX/cache/sentry/outbox
2022-04-20 14:57:26.643 29553-29553/APPNAME D/Sentry: AnrIntegration enabled: false
2022-04-20 14:57:26.643 29553-31787/APPNAME D/Sentry: Processing dir. /XXX/cache/sentry/outbox
2022-04-20 14:57:26.643 29553-29553/APPNAME D/Sentry: enableSessionTracking enabled: true
2022-04-20 14:57:26.643 29553-29553/APPNAME D/Sentry: enableAppLifecycleBreadcrumbs enabled: true
2022-04-20 14:57:26.644 29553-31787/APPNAME D/Sentry: Processing 0 items from cache dir /XXX/cache/sentry/outbox
2022-04-20 14:57:26.644 29553-31787/APPNAME D/Sentry: Finished processing cached files from /XXX/cache/sentry/outbox
2022-04-20 14:57:26.644 29553-29553/APPNAME D/Sentry: AppLifecycleIntegration installed.
2022-04-20 14:57:26.644 29553-29553/APPNAME D/Sentry: ActivityLifecycleIntegration enabled: true
2022-04-20 14:57:26.644 29553-29553/APPNAME D/Sentry: ActivityLifecycleIntegration installed.
2022-04-20 14:57:26.644 29553-29553/APPNAME D/Sentry: UserInteractionIntegration enabled: true
2022-04-20 14:57:26.644 29553-29553/APPNAME D/Sentry: UserInteractionIntegration installed.
2022-04-20 14:57:26.644 29553-29553APPNAME D/Sentry: AppComponentsBreadcrumbsIntegration enabled: true
2022-04-20 14:57:26.644 29553-29553/APPNAME D/Sentry: AppComponentsBreadcrumbsIntegration installed.
2022-04-20 14:57:26.644 29553-29553/APPNAME D/Sentry: SystemEventsBreadcrumbsIntegration enabled: true
2022-04-20 14:57:26.645 29553-29553/APPNAMED/Sentry: SystemEventsBreadcrumbsIntegration installed.
2022-04-20 14:57:26.645 29553-29553/APPNAME D/Sentry: enableSystemEventsBreadcrumbs enabled: true
2022-04-20 14:57:26.648 29553-29553/APPNAME I/Sentry: TYPE_AMBIENT_TEMPERATURE is not available.
2022-04-20 14:57:26.648 29553-29553/APPNAME D/Sentry: enableSystemEventBreadcrumbs enabled: true
2022-04-20 14:57:26.649 29553-29553/APPNAME D/Sentry: Capturing event: a2c2d3f1759d4fe0be4e4e4727920f2f
2022-04-20 14:57:26.653 29553-29553APPNAME I/Sentry: Not possible to read external files directory
2022-04-20 14:57:26.654 29553-29553/APPNAME I/Sentry: Session is null on scope.withSession
2022-04-20 14:57:26.655 29553-31790/APPNAME D/Sentry: Adding Envelope to offline storage: /XXX/cache/sentry/XXX.envelope
2022-04-20 14:57:26.676 29553-31790/APPNAME D/Sentry: Serializing object: {SOMEOBJECT}
2022-04-20 14:57:26.826 29553-31790/APPNAME D/Sentry: Request failed, API returned 403
2022-04-20 14:57:26.835 29553-31790/APPNAME D/Sentry: <html>
    <head><title>403 Forbidden</title></head>
    <body>
    <center><h1>403 Forbidden</h1></center>
    <hr><center>nginx/1.19.10</center>
    </body>
    </html>
2022-04-20 14:57:26.836 29553-31790/APPNAME D/Sentry: The transport failed to send the envelope with response code 403
2022-04-20 14:57:26.836 29553-31790/APPNAME E/Sentry: Envelope submission failed
    java.lang.IllegalStateException: The transport failed to send the envelope with response code 403
        at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.flush(AsyncHttpTransport.java:220)
        at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.run(AsyncHttpTransport.java:183)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
2022-04-20 14:57:26.838 29553-31790/APPNAME D/Sentry: Serializing object: {SOMEOBJECT}
2022-04-20 14:57:26.844 29553-31790/APPNAME D/Sentry: Adding Envelope to offline storage: /XXX/cache/sentry/XXX.envelope
2022-04-20 14:57:26.913 29553-31790/APPNAME D/Sentry: Request failed, API returned 403
2022-04-20 14:57:26.916 29553-31790/APPNAME D/Sentry: <html>
    <head><title>403 Forbidden</title></head>
    <body>
    <center><h1>403 Forbidden</h1></center>
    <hr><center>nginx/1.19.10</center>
    </body>
    </html>
2022-04-20 14:57:26.917 29553-31790/APPNAME D/Sentry: The transport failed to send the envelope with response code 403
2022-04-20 14:57:26.918 29553-31790/APPNAME E/Sentry: Envelope submission failed
    java.lang.IllegalStateException: The transport failed to send the envelope with response code 403
        at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.flush(AsyncHttpTransport.java:220)
        at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.run(AsyncHttpTransport.java:183)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)

```

**Comment by marandaneto** [comment]
@keikoang that's likely an issue with your self-hosted Sentry, I'd rather move this question to https://github.com/getsentry/self-hosted since it returns 403, it's not an SDK issue.
