### ISSUE TITLE
Can't deserialize SentryOptions from json using jackson blackbird on Openjdk17

### ISSUE THREAD

**Issue by georgespalding** [getsentry/sentry-java#2086]
### Integration

sentry-logback

### Java Version

17

### Version

6.0.0

### Steps to Reproduce

1. Set up a gradle project with dependencies: 

- `com.fasterxml.jackson.core:jackson-databind:2.13.3`
- `io.sentry:sentry-logback:6.0.0`
- JUnit5

3. Create a regular JUnit 5 test, like so:

```
import static org.junit.jupiter.api.Assertions.assertEquals;
import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.module.blackbird.BlackbirdModule;
import io.sentry.SentryOptions;
import java.io.IOException;
import org.junit.jupiter.api.Test;

class SentryOptionsTest {

  private static final String json = "{\"dsn\": \"something\",\"environment\": \"unit-test\"}";
  private static final ObjectMapper mapper =
      new ObjectMapper()
          .registerModule(new BlackbirdModule())
          .enable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);

  @Test
  void testDeserialize() throws IOException {
    final SentryOptions options = mapper.readValue(json, SentryOptions.class);
    assertEquals("something", options.getDsn());
    assertEquals("unit-test", options.getEnvironment());
  }
}
```

4. Run the test.

### Expected Result

The test should succeed and print `A-Ok`.

### Actual Result

```
java.lang.RuntimeException: java.lang.IllegalAccessException: module java.base does not open javax.net.ssl to unnamed module @ae45eb6

	at com.fasterxml.jackson.module.blackbird.deser.BBDeserializerModifier.updateBuilder(BBDeserializerModifier.java:73)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:286)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:150)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:415)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:350)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findNonContextualValueDeserializer(DeserializationContext.java:632)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:539)
	at com.fasterxml.jackson.module.blackbird.deser.SuperSonicBeanDeserializer.resolve(SuperSonicBeanDeserializer.java:79)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:294)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:642)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4805)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4675)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3597)
	at SentryOptionsTest.testDeserialize(SentryOptionsTest.java:22)
...
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
...
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
...
Caused by: java.lang.IllegalAccessException: module java.base does not open javax.net.ssl to unnamed module @ae45eb6
	at java.base/java.lang.invoke.MethodHandles.privateLookupIn(MethodHandles.java:259)
	at com.fasterxml.jackson.module.blackbird.util.ReflectionHack$Java9Up.lambda$privateLookupIn$0(ReflectionHack.java:53)
	at com.fasterxml.jackson.module.blackbird.util.Unchecked.lambda$supplier$1(Unchecked.java:41)
	at com.fasterxml.jackson.module.blackbird.util.ReflectionHack$Java9Up.privateLookupIn(ReflectionHack.java:53)
	at com.fasterxml.jackson.module.blackbird.util.ReflectionHack.privateLookupIn(ReflectionHack.java:25)
	at com.fasterxml.jackson.module.blackbird.deser.BBDeserializerModifier.updateBuilder(BBDeserializerModifier.java:71)
	... 88 more
```
(This can be mitigated by adding `--add-opens java.base/javax.net.ssl=ALL-UNNAMED` to the java opts but it would be preferable if the `SentryOptions` class was a POJO)

**Comment by maciejwalkowiak** [comment]
`SentryOptions` has not been designed with JSON serialization in mind, but you may be able to serialize https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/ExternalOptions.java instead and then use it like this:

```java
var externalOptions = ...; // deserialize
var ops = new SentryOptions();
ops.merge(externalOptions);
```

**Comment by georgespalding** [comment]
Yeah I figured as much. I just created a _very_ slimmed down version:
```
  record SentryOptionsConfig(String dsn, String environment
      // Add more options as needed
      ) {
    public SentryOptions build() {
      SentryOptions options = new SentryOptions();
      options.setDsn(dsn);
      options.setEnvironment(environment);
      return options;
    }
  }
```

I'm not blocked on this, but it'd be nice to use the method you suggested above.
It makes more sense to keep the copying of properties from `ExternalOptions` to `SentryOptions` in the library itself, than users trying to keep up as the properties evolve.

**Comment by adinauer** [comment]
@georgespalding can you please share a little bit more information on your use case so we can discuss what other options might be available?

**Comment by adinauer** [comment]
Thanks for the detailed response @georgespalding, I've opened #2088 to relax visibility.
