### ISSUE TITLE
ERROR: The transport failed to send the envelope with response code 403 

### ISSUE THREAD

**Issue by JoyJeck** [getsentry/sentry-java#2098]
### Integration

sentry-spring-boot-starter

### Java Version

8

### Version

9.1.2

### Steps to Reproduce

ERROR: The transport failed to send the envelope with response code 403
ERROR: Envelope submission failed 
 java.lang.IllegalStateException: The transport failed to send the envelope with response code 403
java.lang.IllegalStateException: The transport failed to send the envelope with response code 403
	at io.sentry.transport.AsyncConnection$EnvelopeSender.flush(AsyncConnection.java:249)
	at io.sentry.transport.AsyncConnection$EnvelopeSender.run(AsyncConnection.java:212)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

### Expected Result

success

### Actual Result

ERROR: The transport failed to send the envelope with response code 403
ERROR: Envelope submission failed 
 java.lang.IllegalStateException: The transport failed to send the envelope with response code 403
java.lang.IllegalStateException: The transport failed to send the envelope with response code 403
	at io.sentry.transport.AsyncConnection$EnvelopeSender.flush(AsyncConnection.java:249)
	at io.sentry.transport.AsyncConnection$EnvelopeSender.run(AsyncConnection.java:212)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by adinauer** [comment]
@JoyJeck was this a newly created project? If so can you please give this another try? We were having an issue where newly created projects needed about an hour before events could be received consistently.

I assume this happened today?

**Comment by adinauer** [comment]
We're closing this for now, if you have any news, feel free to reopen.
