### ISSUE TITLE
Flaky SentryTracerTest

### ISSUE THREAD

**Issue by adinauer** [getsentry/sentry-java#2143]
### Description

```
io.sentry.SentryTracerTest > when idle transaction with children, finishes the transaction after the idle timeout FAILED
    Wanted but not invoked:
    hub.captureTransaction(
        <any>,
        <any>,
        <any>,
        <any>
    );
    -> at io.sentry.Hub.captureTransaction(Hub.java:606)
    However, there were exactly 5 interactions with this mock:
    hub.bindClient(
        Mock for ISentryClient, hashCode: 908635948
    );
    -> at io.sentry.SentryTracerTest$Fixture.<init>(SentryTracerTest.kt:33)
    hub.isEnabled();
    -> at io.sentry.Hub.bindClient(Hub.java:559)
    hub.getOptions();
    -> at io.sentry.SentryTracer.finish(SentryTracer.java:298)
    hub.configureScope(
        io.sentry.SentryTracer$$Lambda$206/0x000000080044f440@73dac022
    );
    -> at io.sentry.SentryTracer.finish(SentryTracer.java:331)
    hub.isEnabled();
    -> at io.sentry.Hub.configureScope(Hub.java:542)
        at app//io.sentry.Hub.captureTransaction(Hub.java:606)
        at app//io.sentry.SentryTracerTest.when idle transaction with children, finishes the transaction after the idle timeout(SentryTracerTest.kt:623)
```

**Comment by adinauer** [comment]
Seems to be happening roughly once per week.
