### ISSUE TITLE
ANR in DefaultAndroidEventProcessor.getExternalFilesDirs due to disk I/O

### ISSUE THREAD

**Issue by vibin** [getsentry/sentry-java#2223]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

7.0.4

### Proguard

Enabled

### Version

5.7.4

### Steps to Reproduce

Track an exception using `Sentry.captureException(throwable)` API

### Expected Result

Exception should be tracked without any ANR

### Actual Result

ANR thrown: 1218 times, affecting 496 users in last 7 days:

```
main (native): tid=1 systid=28493 
#00 pc 0xc5728 libc.so 
#01 pc 0x25078 libjavacore.so 
       at libcore.io.Linux.access(Linux.java)
       at libcore.io.ForwardingOs.access(ForwardingOs.java:72)
       at libcore.io.BlockGuardOs.access(BlockGuardOs.java:73)
       at libcore.io.ForwardingOs.access(ForwardingOs.java:72)
       at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:8138)
       at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:281)
       at java.io.File.exists(File.java:815)
       at android.app.ContextImpl.ensureExternalDirsExistOrFilter(ContextImpl.java:2983)
       at android.app.ContextImpl.getExternalFilesDirs(ContextImpl.java:782)
       at android.content.ContextWrapper.getExternalFilesDirs(ContextWrapper.java:288)
       at io.sentry.android.core.DefaultAndroidEventProcessor.getExternalFilesDirs(DefaultAndroidEventProcessor.java:644)
       at io.sentry.android.core.DefaultAndroidEventProcessor.getExternalStorageDep(DefaultAndroidEventProcessor.java:655)
       at io.sentry.android.core.DefaultAndroidEventProcessor.getExternalStorageStat(DefaultAndroidEventProcessor.java:630)
       at io.sentry.android.core.DefaultAndroidEventProcessor.setDeviceIO(DefaultAndroidEventProcessor.java:367)
       at io.sentry.android.core.DefaultAndroidEventProcessor.getDevice(DefaultAndroidEventProcessor.java:285)
       at io.sentry.android.core.DefaultAndroidEventProcessor.setDevice(DefaultAndroidEventProcessor.java:173)
       at io.sentry.android.core.DefaultAndroidEventProcessor.setCommons(DefaultAndroidEventProcessor.java:140)
       at io.sentry.android.core.DefaultAndroidEventProcessor.process(DefaultAndroidEventProcessor.java:130)
       at io.sentry.SentryClient.processEvent(SentryClient.java:255)
       at io.sentry.SentryClient.captureEvent(SentryClient.java:101)
       at io.sentry.Hub.captureException(Hub.java:169)
       at io.sentry.IHub.captureException(IHub.java:99)
       at io.sentry.Hub.captureException(Hub.java)
       at io.sentry.Sentry.captureException(Sentry.java:296)
       at redacted.core.CrashReporter.recordException(CrashReporter.kt:61)
       at redacted.main.NonFatalReportingTree.log(NonFatalReportingTree.kt:30)
       at timber.log.Timber$Tree.prepareLog(Timber.kt:168)
       at timber.log.Timber$Tree.e(Timber.kt:106)
       at timber.log.Timber$Forest.e(Timber.kt:347)
       at redacted.widget.RecentlyViewedWidgetVm$Companion.deal(WidgetVms.kt:425)
       at redacted.widget.RecentlyViewedWidgetVm.<init>(WidgetVms.kt:401)
       at redacted.widget.HorizScrollerWidgetGroupVm.<init>(WidgetGroupVms.kt:181)
       at redacted.widget.WidgetGroupVm$Companion.createViewModels(WidgetGroupVms.kt:99)
       at redacted.widget.WidgetGroupsZipperKt.zipWithViewModels(WidgetGroupsZipper.kt:30)
       at redacted.widget.WidgetGroupsZipperKt.zipWithViewModels$default(WidgetGroupsZipper.kt:12)
       at redacted.catalog.ForYouVm.onForYouResponse(ForYouVm.kt:593)
       at redacted.catalog.ForYouVm.fetchForYou$lambda-5(ForYouVm.kt:237)
       at redacted.catalog.ForYouVm.$r8$lambda$DLY4sKyCIBTdihc2uoZUq79ZqOM(ForYouVm.kt)
       at redacted.catalog.ForYouVm$$InternalSyntheticLambda$2$3aa7bb47f79df85df50b7f7782ad9fd91a0c91d84e458f75dbeeecc2d05d5336$2.apply(ForYouVm.java)
       at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:57)
       at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
       at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:260)
       at android.app.ActivityThread.main(ActivityThread.java:8269)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
```

**Comment by adinauer** [comment]
Hello @vibin, in newer releases we have added an option to opt out of collecting certain info that may cause ANR. It is called `setCollectAdditionalContext(false)` and is available from `6.1.1`. Here's a troubleshooting guide on the topic https://docs.sentry.io/platforms/android/troubleshooting/#sentry-android-sdk-causes-anr including an example of how to set it via `AndroidManifest.xml`.

This seems to be a duplicate of #2095.

I hope this helps.

**Comment by vibin** [comment]
Thanks @adinauer! This flag seems useful, but we could also init Sentry on a background thread. 
Let me evaluate both the approaches here.

**Comment by philipphofmann** [comment]
> but we could also init Sentry on a background thread.

@vibin, just keep in mind that you run into the risk of not capturing startup crashes. It's a trade-off when going for that.
