### ISSUE TITLE
ApplicationNotResponding during a SentryAndroid.init()

### ISSUE THREAD

**Issue by JorisBodin** [getsentry/sentry-java#2229]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

7.5.1

### Proguard

Enabled

### Version

6.4.1

### Steps to Reproduce

No idea, but we have received several times (on 2 devices) issues on sentry (?!) that the exception `io.sentry.android.core.ApplicationNotResponding: Application Not Responding for at least 5000 ms.` during a SentryAndroid.init()

Show the code: https://github.com/Infomaniak/android-kDrive/blob/38102b85f0f9b13d3f665a09f5d9d9e268c2f381/app/src/main/java/com/infomaniak/drive/ApplicationMain.kt#L108

### Expected Result

No ApplicationNotResponding 😄 

### Actual Result

    io.sentry.android.core.ApplicationNotResponding: Application Not Responding for at least 5000 ms.
        at com.infomaniak.drive.ApplicationMain.onCreate(ApplicationMain.kt:108)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1229)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6763)
        at android.app.ActivityThread.access$1500(ActivityThread.java:256)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7872)
        at java.lang.reflect.Method.invoke(Method.java)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
        
https://sentry.infomaniak.com/share/issue/564a3fd34a074cafaaf03797df248ddb/ 

<img width="975" alt="image" src="https://user-images.githubusercontent.com/2796439/187878841-4822e398-8451-4346-87b4-6b011dd2af2a.png">

**Comment by adinauer** [comment]
Hello @JorisBodin seems like you're using auto init in addition to manually calling `SentryAndroid.init`. Can you please disable auto init as described here https://docs.sentry.io/platforms/android/configuration/manual-init/ and test again?

**Comment by JorisBodin** [comment]
@adinauer thank you for the answer

I didn't know there was an auto-init. I had followed the quick starter guide when creating an application in sentry. Obviously it has been updated since.
We'll remove the auto-init and see if we get that kind of message again. But I don't think so. The auto-init explained why we got this issue.
Because if sentry crashes at initialization we can't know about it

**Comment by adinauer** [comment]
Closing this, feel free to reopen if you need more help.
