### ISSUE TITLE
Sentry: Failed to execute FrameMetricsAggregator.remove

### ISSUE THREAD

**Issue by HafijurRahmanEjaro** [getsentry/sentry-java#2292]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

6.5

### Proguard

Enabled

### Version

6.5.0

### Steps to Reproduce

1. As soon as the app is open 
2. While the application (Root class) runs

### Expected Result

What is the cause of this exception?
Sentry: Failed to execute FrameMetricsAggregator.remove

### Actual Result

**Sentry: Failed to execute FrameMetricsAggregator.remove**
    java.lang.IllegalArgumentException: attempt to remove OnFrameMetricsAvailableListener that was never added
        at android.view.View.removeFrameMetricsListener(View.java:7408)
        at android.view.Window.removeOnFrameMetricsAvailableListener(Window.java:942)
        at androidx.core.app.FrameMetricsAggregator$FrameMetricsApi24Impl.remove(FrameMetricsAggregator.java:433)
        at androidx.core.app.FrameMetricsAggregator.remove(FrameMetricsAggregator.java:243)
        at io.sentry.android.core.ActivityFramesTracker.lambda$setMetrics$1$ActivityFramesTracker(ActivityFramesTracker.java:144)
        at io.sentry.android.core.-$$Lambda$ActivityFramesTracker$AZohn7hWx9OMGW_pxBKuLALz4ho.run(Unknown Source:4)
        at io.sentry.android.core.ActivityFramesTracker.runSafelyOnUiThread(ActivityFramesTracker.java:212)
        at io.sentry.android.core.ActivityFramesTracker.setMetrics(ActivityFramesTracker.java:143)
        at io.sentry.android.core.ActivityLifecycleIntegration.lambda$startTracing$0$ActivityLifecycleIntegration(ActivityLifecycleIntegration.java:171)
        at io.sentry.android.core.-$$Lambda$ActivityLifecycleIntegration$wxvJQE2ef988IyjjUaJfTHFedKQ.execute(Unknown Source:6)
        at io.sentry.SentryTracer.finish(SentryTracer.java:351)
        at io.sentry.android.core.ActivityLifecycleIntegration.finishTransaction(ActivityLifecycleIntegration.java:266)
        at io.sentry.android.core.ActivityLifecycleIntegration.stopTracing(ActivityLifecycleIntegration.java:249)
        at io.sentry.android.core.ActivityLifecycleIntegration.onActivityDestroyed(ActivityLifecycleIntegration.java:371)
        at android.app.Application.dispatchActivityDestroyed(Application.java:562)
        at android.app.Activity.dispatchActivityDestroyed(Activity.java:1536)
        at android.app.Activity.onDestroy(Activity.java:2723)
        at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:329)
        at androidx.appcompat.app.AppCompatActivity.onDestroy(AppCompatActivity.java:278)
        at android.app.Activity.performDestroy(Activity.java:8327)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1344)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5223)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5269)
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2108)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7948)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by adinauer** [comment]
This would be the PR where we changed the behaviour: https://github.com/getsentry/sentry-java/pull/2282

**Comment by markushi** [comment]
As discussed internally we'll remove the logging again with a future release, as it might be confusing for anyone using the SDK.

**Comment by HafijurRahmanEjaro** [comment]
> Hello @HafijurRahmanEjaro I assume you see this exception in the Sentry logs but it doesn't cause a crash, correct? If that's the case we've added a new log statement for this exception which was previously ignored.

The application is not crashing only showing the exception on logcat.

**Comment by HafijurRahmanEjaro** [comment]
But I have experienced that when I'm initializing the sentry then that issue shows. like:
```
SentryAndroid.init(this,options -> {
                    options.setEnvironment(HRUrlFactory.isModeDevelopment()? "development" : "production");
                    options.setDebug(true);
                });
```

when I removed that initialization of code then no exception showing

**Comment by markushi** [comment]
@HafijurRahmanEjaro thanks for getting back to us! Seeing the exception when calling `.setDebug(true)` is fine, as the Exception is properly handled within the Sentry SDK and the SDK will work properly even if you see the exception in the logs.
As mentioned earlier, we'll improve the logging to make this less confusing in future.
