### ISSUE TITLE
DiskReadViolation in AndroidTransactionProfiler

### ISSUE THREAD

**Issue by prashanOS** [getsentry/sentry-java#2317]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

7.3.1

### Proguard

Enabled

### Version

6.5.0

### Steps to Reproduce

Enable StrictMode.
Enable Profiling.
Launch app.

### Expected Result

No StrictMode violations.

### Actual Result
```
Non-fatal Exception: android.os.strictmode.DiskReadViolation
       at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1556)
       at libcore.io.BlockGuardOs.access(BlockGuardOs.java:69)
       at libcore.io.ForwardingOs.access(ForwardingOs.java:73)
       at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:7884)
       at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:281)
       at java.io.File.exists(File.java:815)
       at io.sentry.android.core.AndroidTransactionProfiler.onTransactionStart(AndroidTransactionProfiler.java:118)
       at io.sentry.Hub.createTransaction(Hub.java:730)
       at io.sentry.Hub.startTransaction(Hub.java:665)
       at io.sentry.HubAdapter.e(HubAdapter.java:4)
       at io.sentry.android.core.ActivityLifecycleIntegration.startTracing(ActivityLifecycleIntegration.java:191)
       at io.sentry.android.core.ActivityLifecycleIntegration.onActivityCreated(ActivityLifecycleIntegration.java:283)
       at android.app.Application.dispatchActivityCreated(Application.java:392)
       at android.app.Activity.dispatchActivityCreated(Activity.java:1228)
       at android.app.Activity.onCreate(Activity.java:1505)
       at androidx.core.app.ComponentActivity.onCreate(ComponentActivity.java:88)
       at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:363)
       at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:217)
       at com.tubitv.fragmentoperator.activity.FoActivity.onCreate(FoActivity.kt:16)
       at io.opensea.context.MainActivity.onCreate(MainActivity.kt:27)
       at android.app.Activity.performCreate(Activity.java:7957)
       at android.app.Activity.performCreate(Activity.java:7946)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
       at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:2)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3530)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3707)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2220)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8016)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
```

**Comment by prashanOS** [comment]
If you all don't have integration tests set up with StrictMode on, would highly recommend setting them up so that you can catch these issues!

**Comment by romtsn** [comment]
@stefanosiano can you take a look at this? I guess there's no way for us to off-load this from the main thread, right?

**Comment by stefanosiano** [comment]
the [fix](https://github.com/getsentry/sentry-java/pull/2342) made it into master
