### ISSUE TITLE
Cannot remove default integrations, i.e. `TempSensorBreadcrumbsIntegration`

### ISSUE THREAD

**Issue by fzyzcjy** [getsentry/sentry-java#2355]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

latest

### Proguard

Enabled

### Version

latest

### Steps to Reproduce

Hi, I have to remove `TempSensorBreadcrumbsIntegration` integration, because otherwise app is rejected by stores since it reads privacy data. However, I have not seen a way to remove it (there is no things as removeIntegration etc).

### Expected Result

-

### Actual Result

-

**Comment by romtsn** [comment]
I think you can simply do
```kotlin
SentryAndroid.init(context) { options ->
  options.integrations.removeIf { it is TempSensorBreadcrumbsIntegration }
}
```

Also, I'm curious which stores are rejecting the app? Is it Google Play or some others? We might need to remove it from default integrations then

**Comment by fzyzcjy** [comment]
I will have a try, thanks! (Not checked it yet so not sure whether integrations is mutable or not)

> Also, I'm curious which stores are rejecting the app? Is it Google Play or some others? We might need to remove it from default integrations then

Others, indeed tencent store, which seem to have >1 billion target users (where google play is banned)

**Comment by romtsn** [comment]
yep, it's mutable.

Chinese stores are very restrictive, we have a few issues opened about reading too much data 🙈 Maybe we need to think of a chinese flavour of the SDK without all those sensitive default integrations/data collectors, if there's a demand. I might open an issue to collect feedback 👍 

Gonna close this one, since it should be resolved by using remove/removeIf.

**Comment by marandaneto** [comment]
Dupe of https://github.com/getsentry/sentry-dart/issues/1129
@fzyzcjy next time I'd ask you to open an issue on a single repo otherwise you trigger multiple teams for the very same issue, thanks for understanding.

**Comment by fzyzcjy** [comment]
@marandaneto Get it, sorry for that. Originally I thought this is Android while that is Flutter...

By the way, the two issues have different answers that are both helpful and needed to be combined indeed :)

**Comment by marandaneto** [comment]
> @marandaneto Get it, sorry for that. Originally I thought this is Android while that is Flutter...
> 
> By the way, the two issues have different answers that are both helpful and needed to be combined indeed :)

That's what I meant by:

> remove the SystemEventsBreadcrumbsIntegration from the integrations list manually on the Android SDK.

Here it is the very same answer, but with a code snippet =P

**Comment by fzyzcjy** [comment]
@marandaneto You are right =P

P.S. My mind seemed to be wrong to Android before, because IIRC the dart integrations are not removeable (use something like UnmodifiableListView the last time I check it) and I wrongly thought it was Android

**Comment by marandaneto** [comment]
> @marandaneto You are right =P
> 
> P.S. My mind seemed to be wrong to Android before, because IIRC the dart integrations are not removeable (use something like UnmodifiableListView the last time I check it) and I wrongly thought it was Android

You can mutate the Flutter integrations as well.
`SentryOptions#removeIntegration(integration)`

**Comment by fzyzcjy** [comment]
Totally agree. Not sure why I was so stupid when checking it :)

**Comment by fzyzcjy** [comment]
> I think you can simply do
> 
> ```kotlin
> SentryAndroid.init(context) { options ->
>   options.integrations.removeIf { it is TempSensorBreadcrumbsIntegration }
> }
> ```
> 
> Also, I'm curious which stores are rejecting the app? Is it Google Play or some others? We might need to remove it from default integrations then

Well, there is error on some devices:

```
E/AndroidRuntime(18564): Caused by: java.lang.UnsupportedOperationException
E/AndroidRuntime(18564): 	at java.util.concurrent.CopyOnWriteArrayList$CowIterator.remove(CopyOnWriteArrayList.java:814)
E/AndroidRuntime(18564): 	at java.util.Collection.removeIf(Collection.java:402)
```

**Comment by romtsn** [comment]
oh 🙈 `removeIf` is probably using `iterator` under the hood, which is not allowed for CopyOnWriteArrayList. Then the code would be slightly different to make it work:
```kotlin
SentryAndroid.init(context) { options ->
  val tempSensorIntegration = options.integrations.indexOfFirst { it is TempSensorBreadcrumbsIntegration }
  options.integrations.removeAt(tempSensorIntegration)
}
```

**Comment by fzyzcjy** [comment]
I used `removeAll` by builtin kotlin and it worked well. removeIf seems to have bug because it is not supported in android <24 (while ok for >=24)

**Comment by fzyzcjy** [comment]
@marandaneto Well the fix only lasts for 4 days... https://github.com/getsentry/sentry-java/issues/2821

**Comment by marandaneto** [comment]
Oh no, definitely a regression, @romtsn @markushi ^

**Comment by stefanosiano** [comment]
Hey @fzyzcjy this issue was fixed in the release `6.25.1`.
Feel free to reopen this issue in case something goes wrong

**Comment by fzyzcjy** [comment]
@stefanosiano Looks great, thank you!
