### ISSUE TITLE
Failing app-metrics check on PR

### ISSUE THREAD

**Issue by adinauer** [getsentry/sentry-java#2463]
### Description

I've had a failing `app-metrics` check on a PR. Retry didn't help.

```
Trying to download previous artifact 'app-sdk-metrics-results' for branch 'fix/set-source-when-setting-transaction-name'
Downloading artifact https://api.github.com/repos/getsentry/sentry-java/actions/artifacts/458657327/zip and extracting to out/results
Error: Exception in thread "main" org.kohsuke.github.HttpException: {"message":"Artifact has expired","documentation_url":"https://docs.github.com/rest/reference/actions#download-an-artifact"}
	at org.kohsuke.github.GitHubConnectorResponseErrorHandler$1.onError(GitHubConnectorResponseErrorHandler.java:56)
	at org.kohsuke.github.GitHubClient.detectKnownErrors(GitHubClient.java:424)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:386)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:355)
	at org.kohsuke.github.Requester.fetchStream(Requester.java:117)
	at org.kohsuke.github.GHArtifact.download(GHArtifact.java:119)
	at GitHub$Companion.downloadPreviousArtifact(GitHub.kt:88)
	at ResultProcessor.main(ResultProcessor.kt:27)
	at ResultProcessorKt.main(ResultProcessor.kt:6)
	at ResultProcessorKt.main(ResultProcessor.kt)
```

Run: https://github.com/getsentry/sentry-java/actions/runs/3882619625/jobs/6623577413
PR: https://github.com/getsentry/sentry-java/pull/2405

**Comment by adinauer** [comment]
@vaind do you happen to know the cause / how to fix this problem?

**Comment by vaind** [comment]
Artifacts should be retained for 90 days [by default](https://docs.github.com/en/organizations/managing-organization-settings/configuring-the-retention-period-for-github-actions-artifacts-and-logs-in-your-organization) but it looks like this one is only retained for 30 days: https://api.github.com/repos/getsentry/sentry-java/actions/artifacts/458657327
```
  "created_at": "2022-12-01T14:08:38Z",
  "updated_at": "2022-12-01T14:08:41Z",
  "expires_at": "2022-12-31T14:08:32Z",
 ```
 
 In any case, the metrics action should recognize that and not fail. I'll make the change: https://github.com/getsentry/action-app-sdk-overhead-metrics/issues/5
 
 How pressing is this? Is the PR blocked and can't be merged because of the failing job?

**Comment by adinauer** [comment]
Would you say I can go ahead and merge anyways?

**Comment by vaind** [comment]
> Would you say I can go ahead and merge anyways?

Yes, I don't see why not.

**Comment by adinauer** [comment]
OK great, then no rush from my side.
