### ISSUE TITLE
Sentry-android fails with Android Gradle Plugin 7.4.0

### ISSUE THREAD

**Issue by chao2zhang** [getsentry/sentry-java#2470]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

7.4.0

### Proguard

Enabled

### Version

6.11.0

### Steps to Reproduce

Our codebase has enabled productFlavors, it appears that Sentry-android gradle plugin is compatible with the newly released AGP 7.4.0

### Expected Result

Build commands should succeed

### Actual Result

```
* What went wrong:
Execution failed for task ':...:mergeBetaDrawerReleaseAssets'.
> .../build/generated/assets/sentry/betaDrawerRelease/sentry-debug-meta.properties    .../build/generated/assets/sentry/betaDrawerRelease/sentry-debug-meta.properties: Error: Duplicate resources

* Try:
> Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':...:mergeBetaDrawerReleaseAssets'.

Caused by: .../build/generated/assets/sentry/betaDrawerRelease/sentry-debug-meta.properties    .../build/generated/assets/sentry/betaDrawerRelease/sentry-debug-meta.properties: Error: Duplicate resources
        at com.android.ide.common.resources.DataSet.checkItems(DataSet.java:512)
        at com.android.ide.common.resources.DataSet.loadFromFiles(DataSet.java:273)
        at com.android.ide.common.resources.DataSet.loadFromFiles(DataSet.java:243)
        at com.android.build.gradle.tasks.MergeSourceSetFolders.doFullTaskAction(MergeSourceSetFolders.kt:153)
```

**Comment by chao2zhang** [comment]
Looks like the issue is actually `sentry-android-gradle-plugin:3.4.0`. Will try updating this https://github.com/getsentry/sentry-android-gradle-plugin/releases/tag/3.4.0
