### ISSUE TITLE
Crash on App start - NoSuchFieldError SQLiteStatement

### ISSUE THREAD

**Issue by SaharWeissman** [getsentry/sentry-java#2510]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

7.2.2

### Proguard

Disabled

### Version

6.13.0

### Steps to Reproduce

this issue seems to happen after upgrading androidx room version to 2.5.0.

steps to reproduce:
1. have a project with androidx room v2.5.0  + sentry sdk v6.13.0  + sentry gradle plugin v3.4.0 configured in project
2. run app

its important to state that running the app with older version of room (2.4.3) works fine. 

also saw an existing issue in google's issue tracker related to it:

https://issuetracker.google.com/issues/265824784

which basically points to the ‘androidx.sqlite’ being pinpointed to an older version which is incompatible with room's new version.

### Expected Result

App starts && runs without crash :) 

### Actual Result

app crashes with the following stacktrace:

```
FATAL EXCEPTION: WM.task-1
Process: com.dapulse.dapulse.dev, PID: 32467
java.lang.NoSuchFieldError: No instance field mDelegate of type Landroid/database/sqlite/SQLiteStatement; in class Landroidx/sqlite/db/framework/FrameworkSQLiteStatement; or its superclasses (declaration of 'androidx.sqlite.db.framework.FrameworkSQLiteStatement' appears in /data/app/~~MupF880tLQ5_XYGH_VyHPQ==/com.dapulse.dapulse.dev-jC5mKt2lo_q6eUZTWescHw==/base.apk!classes20.dex)
                                                                              	at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeUpdateDelete(Unknown Source:0)
                                                                              	at androidx.work.impl.model.WorkSpecDao_Impl.markWorkSpecScheduled(WorkSpecDao_Impl.java:343)
                                                                              	at androidx.work.impl.background.systemjob.SystemJobScheduler.reconcileJobs(SystemJobScheduler.java:336)
                                                                              	at androidx.work.impl.utils.ForceStopRunnable.cleanUp(ForceStopRunnable.java:249)
                                                                              	at androidx.work.impl.utils.ForceStopRunnable.forceStopRunnable(ForceStopRunnable.java:215)
                                                                              	at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:110)
                                                                              	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
                                                                              	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                              	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                              	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by romtsn** [comment]
hi, thanks for the report. We are aware on the issue and already working on a fix. Please track it here https://github.com/getsentry/sentry-android-gradle-plugin/issues/434. Cheers!
