### ISSUE TITLE
Spring Boot and Log4j2 NoClassDefFoundError

### ISSUE THREAD

**Issue by grount** [getsentry/sentry-java#2714]
### Integration

sentry

### Java Version

11

### Version

6.5.0

### Steps to Reproduce

1. The following dependencies are added to `pom.xml`
```xml
    <!-- Sentry -->
    <dependency>
      <groupId>io.sentry</groupId>
      <artifactId>sentry-spring-boot-starter</artifactId>
      <version>6.5.0</version>
    </dependency>
    <dependency>
      <groupId>io.sentry</groupId>
      <artifactId>sentry-log4j2</artifactId>
      <version>6.19.0</version>
    </dependency>
    <!-- end -->
```
2. `log4j2.xml` configuration:
```xml
<Configuration packages="org.apache.logging.log4j.core,io.sentry.log4j2">
    <Appenders>
         <Async .../>
        <Sentry name="Sentry"/>
    </Appenders>
    <Loggers>
        <Root level="INFO">
            <AppenderRef ref="Sentry"/>
            <AppenderRef ref="ASYNC"/>
        </Root>
    </Loggers>
<Configuration/>
```

### Expected Result

Application is able to start

### Actual Result

```
Exception in thread "main" java.lang.NoClassDefFoundError: io/sentry/SentryIntegrationPackageStorage
	at io.sentry.log4j2.SentryAppender.addPackageAndIntegrationInfo(SentryAppender.java:280)
	at io.sentry.log4j2.SentryAppender.start(SentryAppender.java:142)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:309)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:626)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:699)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:716)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:270)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:155)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:599)
	at com.intuit.sales.custexp.checkout.CheckoutServiceApplication.<clinit>(ServiceApplication.java:40)
Caused by: java.lang.ClassNotFoundException: io.sentry.SentryIntegrationPackageStorage
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
```

**Comment by adinauer** [comment]
Hello @grount you're using different versions of the SDK for the Spring Integration and the Log4j2 integration. Can you please try using the same version for both?

**Comment by grount** [comment]
@adinauer that seems to do the trick, thanks for the quick response.
Maybe some documentation can be enhanced?
