### ISSUE TITLE
Add option to disable `RootChecker`

### ISSUE THREAD

**Issue by fzyzcjy** [getsentry/sentry-java#2718]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

latest

### Proguard

Enabled

### Version

latest

### Steps to Reproduce

Some app stores say that "the app is obtaining root permission" which looks quite like my app is very bad. However, after checking stacktrace, it is just:

```
[02:47:20.604]:     at java.lang.Runtime.exec(Runtime.java:721)
[02:47:20.605]:     at java.lang.Runtime.exec(Runtime.java:577)
[02:47:20.605]:     at io.sentry.android.core.internal.util.RootChecker.checkSUExist(RootChecker.java:135)
[02:47:20.605]:     at io.sentry.android.core.internal.util.RootChecker.isDeviceRooted(RootChecker.java:90)
[02:47:20.605]:     at io.sentry.android.core.DefaultAndroidEventProcessor.loadContextData(DefaultAndroidEventProcessor.java:105)
[02:47:20.605]:     at io.sentry.android.core.DefaultAndroidEventProcessor.lambda$new$0(DefaultAndroidEventProcessor.java:97)
[02:47:20.605]:     at io.sentry.android.core.DefaultAndroidEventProcessor.lambda$new$0$DefaultAndroidEventProcessor(DefaultAndroidEventProcessor.java:0)
[02:47:20.605]:     at io.sentry.android.core.-$$Lambda$DefaultAndroidEventProcessor$NYQ5qA7CeWYLjnxHfVDRm7bpPQ0.call(-.java:2)
[02:47:20.605]:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[02:47:20.605]:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
[02:47:20.605]:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
[02:47:20.605]:     at java.lang.Thread.run(Thread.java:764)
```

So as you can see, it is the `RootChecker.isDeviceRooted` that triggers this warning.

Therefore, I need to disable the root checker. However, after looking at source code, it seems that I have to disable the *whole* `DefaultAndroidEventProcessor`, while indeed I only want to disable one line in it - the root checker:

https://github.com/getsentry/sentry-java/blob/e9bec6ec2c5092673e12b21b008c3abf8e3cccc1/sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java#L105

Another related issue is that, the app stores is reporting "the app is reading installed app list". But indeed the stack is:

```
[04:42:42.314]:     at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:171)
[04:42:42.314]:     at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:149)
[04:42:42.314]:     at io.sentry.android.core.internal.util.RootChecker.checkRootPackages(RootChecker.java:163)
[04:42:42.314]:     at io.sentry.android.core.internal.util.RootChecker.isDeviceRooted(RootChecker.java:90)
[04:42:42.314]:     at io.sentry.android.core.DefaultAndroidEventProcessor.loadContextData(DefaultAndroidEventProcessor.java:105)
[04:42:42.314]:     at io.sentry.android.core.DefaultAndroidEventProcessor.lambda$new$0(DefaultAndroidEventProcessor.java:97)
[04:42:42.314]:     at io.sentry.android.core.DefaultAndroidEventProcessor.lambda$new$0$DefaultAndroidEventProcessor(DefaultAndroidEventProcessor.java:0)
[04:42:42.314]:     at io.sentry.android.core.-$$Lambda$DefaultAndroidEventProcessor$NYQ5qA7CeWYLjnxHfVDRm7bpPQ0.call(-.java:2)
[04:42:42.314]:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[04:42:42.314]:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
[04:42:42.314]:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
[04:42:42.314]:     at java.lang.Thread.run(Thread.java:764)
```

### Expected Result

-

### Actual Result

-

**Comment by romtsn** [comment]
hi @fzyzcjy, as I understood a new flag in SentryOptions that disables RootChecker at runtime would be enough for you, correct? The stores won't flag the app, even if the RootChecker class is still present in the final apk/bundle, but not used?

**Comment by fzyzcjy** [comment]
@romtsn Yes I think so. As long as the function is not executed, the store will be happy.
