### ISSUE TITLE
ConnectivityManager$TooManyRequestsException when calling init

### ISSUE THREAD

**Issue by kyze8439690** [getsentry/sentry-java#2739]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

8.0.0

### Proguard

Enabled

### Version

6.17.0

### Steps to Reproduce

Can not reproduce, crash on production environment.

### Expected Result

Not to crash

### Actual Result

Caused by android.net.ConnectivityManager$TooManyRequestsException:
       at android.net.ConnectivityManager.convertServiceException(ConnectivityManager.java:3771)
       at android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:3960)
       at android.net.ConnectivityManager.registerDefaultNetworkCallbackForUid(ConnectivityManager.java:4489)
       at android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4456)
       at android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4430)
       at io.sentry.android.core.internal.util.ConnectivityChecker.registerNetworkCallback(ConnectivityChecker.java:231)
       at io.sentry.android.core.NetworkBreadcrumbsIntegration.register(NetworkBreadcrumbsIntegration.java:72)
       at io.sentry.Sentry.init(Sentry.java:224)
       at io.sentry.Sentry.init(Sentry.java:142)
       at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:89)
       at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:70)

**Comment by romtsn** [comment]
This has been fixed in version 6.18.0 (relevant PR https://github.com/getsentry/sentry-java/pull/2653). Please update to the newer version and let us know if the issue still pops up. Thank you!
