### ISSUE TITLE
java.lang.NoSuchMethodError: No static method join(Ljava/lang/CharSequence;Ljava/lang/Iterable;)Ljava/lang/String; in class Ljava/lang/String; or its super classes (declaration of 'java.lang.String' appears in /system/framework/core-oj.jar)

### ISSUE THREAD

**Issue by MJHou** [getsentry/sentry-java#2774]
### Problem Statement

	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:1)
	at j.j.j.j.a.intercept(EncryptInterceptor.java:1)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:1)
	at com.package.data.api.c.intercept(HeaderInterceptor.java:33)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:1)
	at j.j.j.j.b.intercept(HttpCacheInterceptor.java:3)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:1)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:13)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:2)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:3)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

**Comment by romtsn** [comment]
@MJHou thanks for reporting, but why do you think this is caused by our SDK? There are no sentry frames in the stacktrace

**Comment by MJHou** [comment]
@romtsn Last time the information was incomplete, this is the most complete
Thread Name: 'OkHttp Dispatcher'
Back traces starts.
java.lang.NoSuchMethodError: No static method join(Ljava/lang/CharSequence;Ljava/lang/Iterable;)Ljava/lang/String; in class Ljava/lang/String; or its super classes (declaration of 'java.lang.String' appears in /system/framework/core-oj.jar)
	at io.sentry.a1.a(Baggage.java:5)
	at io.sentry.b1.a(BaggageHeader.java:2)
	at io.sentry.i5.a(SentryTracer.java:57)
	at io.sentry.l5.a(Span.java:10)
	at com.msxf.android.module.apm.SentryOkHttpInterceptor.intercept(SentryOkHttpInterceptor.kt:12)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:1)
	at package.intercept(RSAInterceptor.java:12)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:1)
	at j.j.j.j.a.intercept(EncryptInterceptor.java:1)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:1)
	at com.msxf.ayh.data.api.c.intercept(HeaderInterceptor.java:33)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:1)
	at j.j.j.j.b.intercept(HttpCacheInterceptor.java:3)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:1)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:13)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:2)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:3)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
Back traces ends.

**Comment by adinauer** [comment]
Hello @MJHou looks like we're using `String.join` in `Baggage` which doesn't seem to be available until API Level `26` (https://developer.android.com/reference/java/lang/String#join(java.lang.CharSequence,%20java.lang.CharSequence[])).

We can provide a fix for it.

**Comment by MJHou** [comment]
Is a new version provided？Approximately when can I use it @romtsn

**Comment by romtsn** [comment]
> Is a new version provided？Approximately when can I use it @romtsn

No, we still have to fix it and ship it. Either today or next week it should be available.

**Comment by adinauer** [comment]
Working on it right now. Will PR later today.
