### ISSUE TITLE
NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/FileProvider 

### ISSUE THREAD

**Issue by hu441444238xin** [getsentry/sentry-java#2798]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

7.0.4

### Proguard

Enabled

### Version

6.17.0

### Steps to Reproduce

2023-06-26 20:14:55.486 9441-9441/com.xintiaotime.yoy E/CrashReport: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/FileProvider;
        at com.tencent.open.utils.m.a(ProGuard:1501)
        at com.tencent.connect.share.QQShare.d(ProGuard:498)
        at com.tencent.connect.share.QQShare.c(ProGuard:439)
        at com.tencent.connect.share.QQShare.b(ProGuard:362)
        at com.tencent.connect.share.QQShare.shareToQQ(ProGuard:233)
        at com.tencent.tauth.Tencent.shareToQQ(ProGuard:648)
        at com.skyduck.tpls.provider.qq.TPLSQQProvider.shareImageToQQ(TPLSQQProvider.java:752)
        at com.skyduck.tpls.provider.qq.TPLSQQProvider.share(TPLSQQProvider.java:627)
        at com.skyduck.tpls.provider.qq.TPLSQQProvider.share(TPLSQQProvider.java:617)
        at com.skyduck.tpls.SimpleThirdPartiesLoginShareSdk.share(SimpleThirdPartiesLoginShareSdk.java:285)
        at com.xintiaotime.yoy.ui.profession.view.ShareDialog.startShareImageAction(ShareDialog.java:386)
        at com.xintiaotime.yoy.ui.profession.view.ShareDialog.onClick(ShareDialog.java:217)
        at android.view.View.performClick(View.java:7380)
        at android.view.View.performClickInternal(View.java:7342)
        at android.view.View.access$3900(View.java:824)
        at android.view.View$PerformClick.run(View.java:28262)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:238)
        at android.app.ActivityThread.main(ActivityThread.java:7827)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.FileProvider" on path: DexPathList[[zip file "/data/app/com.xintiaotime.yoy-FGArlftuf_RlXdyxkbsQXA==/base.apk"],nativeLibraryDirectories=[/data/app/com.xintiaotime.yoy-FGArlftuf_RlXdyxkbsQXA==/lib/arm64, /data/app/com.xintiaotime.yoy-FGArlftuf_RlXdyxkbsQXA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.tencent.open.utils.m.a(ProGuard:1501) 
        at com.tencent.connect.share.QQShare.d(ProGuard:498) 
        at com.tencent.connect.share.QQShare.c(ProGuard:439) 
        at com.tencent.connect.share.QQShare.b(ProGuard:362) 
        at com.tencent.connect.share.QQShare.shareToQQ(ProGuard:233) 
        at com.tencent.tauth.Tencent.shareToQQ(ProGuard:648) 
        at com.skyduck.tpls.provider.qq.TPLSQQProvider.shareImageToQQ(TPLSQQProvider.java:752) 
        at com.skyduck.tpls.provider.qq.TPLSQQProvider.share(TPLSQQProvider.java:627) 
        at com.skyduck.tpls.provider.qq.TPLSQQProvider.share(TPLSQQProvider.java:617) 
        at com.skyduck.tpls.SimpleThirdPartiesLoginShareSdk.share(SimpleThirdPartiesLoginShareSdk.java:285) 
        at com.xintiaotime.yoy.ui.profession.view.ShareDialog.startShareImageAction(ShareDialog.java:386) 
        at com.xintiaotime.yoy.ui.profession.view.ShareDialog.onClick(ShareDialog.java:217) 
        at android.view.View.performClick(View.java:7380) 
        at android.view.View.performClickInternal(View.java:7342) 
        at android.view.View.access$3900(View.java:824) 
        at android.view.View$PerformClick.run(View.java:28262) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:238) 
        at android.app.ActivityThread.main(ActivityThread.java:7827) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995) 

### Expected Result

Access did not crash

### Actual Result

my application, do star qq share, crash~!

**Comment by romtsn** [comment]
hi @hu441444238xin why do you think the crash is caused by our SDK? There's no `io.sentry` stackframes in the stacktrace and also we don't really use `android.support.v4.content.FileProvider` in the SDK, so I don't see how this is related to our SDK.

**Comment by hu441444238xin** [comment]
Connect and crash, remove and not crash.



发自我的iPhone


------------------ Original ------------------
From: Roman Zavarnitsyn ***@***.***&gt;
Date: Wed,Jun 28,2023 10:03 PM
To: getsentry/sentry-java ***@***.***&gt;
Cc: feiwang ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [getsentry/sentry-java] NoClassDefFoundError: Failed resolutionof: Landroid/support/v4/content/FileProvider  (Issue #2798)





 
hi @hu441444238xin why do you think the crash is caused by our SDK? There's no io.sentry stackframes in the stacktrace and also we don't really use android.support.v4.content.FileProvider in the SDK, so I don't see how this is related to our SDK.

**Comment by hu441444238xin** [comment]
Share qq social scenarios and it crashes.
 
For example sharing posts. Use share to qq social scenario.
 
Crash must occur




发自我的iPhone


------------------ Original ------------------
From: Roman Zavarnitsyn ***@***.***&gt;
Date: Thu,Jun 29,2023 3:40 PM
To: 441448238 ***@***.***&gt;
Subject: Re: [getsentry/sentry-java] NoClassDefFoundError: Failed resolutionof: Landroid/support/v4/content/FileProvider  (Issue #2798)





 
@hu441444238xin what device and Android version does this happen on? Can you provide a reproducible sample?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;
 
 	
 	 		 			从QQ邮箱发来的超大附件 	
 	 		 				 					 						 							 						 					
 					 						 							PicoPico_2.5.4.5.apk 							 (170.3MB, 2023年7月31日 1:16) 						 						 							进入下载页面 							：https://wx.mail.qq.com/ftn/download?func=3&k=cecb5d634fc52979fcb816636332666329719c6961326663141b5e5b07050251080215510404564e05065c524c50510503195c5a070b555457035a5359537263615d5b0c315b050c6e0616564f0648561f554808752106c4978603e892acab8ad81f220421f9078d20&key=cecb5d634fc52979fcb816636332666329719c6961326663141b5e5b07050251080215510404564e05065c524c50510503195c5a070b555457035a5359537263615d5b0c315b050c6e0616564f0648561f554808752106c4978603e892acab8ad81f220421f9078d20&code=148ca2fc&from=

**Comment by romtsn** [comment]
I have no idea what is QQShare I'm sorry. Please provide a reproducible sample

**Comment by hu441444238xin** [comment]
Wait for me, give you a video of the full path from opening the app to, well, having problems.



发自我的iPhone


------------------ Original ------------------
From: Roman Zavarnitsyn ***@***.***&gt;
Date: Sat,Jul 1,2023 1:59 AM
To: 441448238 ***@***.***&gt;
Subject: Re: [getsentry/sentry-java] NoClassDefFoundError: Failed resolutionof: Landroid/support/v4/content/FileProvider  (Issue #2798)





 
I have no idea what is QQShare I'm sorry. Please provide a reproducible sample

**Comment by markushi** [comment]
Closing this due to inactivity, @hu441444238xin please leave a comment on this issue in case you can provide a repro.
