### ISSUE TITLE
Crash for composable preview due to lack of DSN declaration in manifest 

### ISSUE THREAD

**Issue by hangduykhiem** [getsentry/sentry-java#2904]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

7.4.0

### Proguard

Disabled

### Version

6.28.0

### Steps to Reproduce

- Install Sentry with Gradle
- Add DNS into Application Manifest
- Write a simple compose preview, for example

```kotlin
@Composable
fun Greeting(name: String, modifier: Modifier = Modifier) {
    Text(
        text = "Hello $name!",
        modifier = modifier
    )
}

@Preview(showBackground = true)
@Composable
fun GreetingPreview() {
    MyApplicationTheme {
        Greeting("Android")
    }
}
```

- Run this compose preview **on the device**, and **not** in the preview panel on Android Studio.

### Expected Result

The preview runs normally and we can test our composables on a real device.

### Actual Result

The PreviewActivity crashes with the following log

```
08-24 11:17:29.226  2992  2992 E AndroidRuntime: java.lang.RuntimeException: Unable to get provider io.sentry.android.core.SentryInitProvider: java.lang.IllegalArgumentException: DSN is required. Use empty string to disable SDK.
08-24 11:17:29.226  2992  2992 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:8328)
08-24 11:17:29.226  2992  2992 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7828)
08-24 11:17:29.226  2992  2992 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7577)
08-24 11:17:29.226  2992  2992 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
08-24 11:17:29.226  2992  2992 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2400)
08-24 11:17:29.226  2992  2992 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-24 11:17:29.226  2992  2992 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
08-24 11:17:29.226  2992  2992 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
08-24 11:17:29.226  2992  2992 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8757)
08-24 11:17:29.226  2992  2992 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-24 11:17:29.226  2992  2992 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
08-24 11:17:29.226  2992  2992 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
08-24 11:17:29.226  2992  2992 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: DSN is required. Use empty string to disable SDK.
08-24 11:17:29.226  2992  2992 E AndroidRuntime: 	at io.sentry.Sentry.initConfigurations(Sentry.java:291)
08-24 11:17:29.226  2992  2992 E AndroidRuntime: 	at io.sentry.Sentry.init(Sentry.java:210)
08-24 11:17:29.226  2992  2992 E AndroidRuntime: 	at io.sentry.Sentry.init(Sentry.java:147)
08-24 11:17:29.226  2992  2992 E AndroidRuntime: 	at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:89)
08-24 11:17:29.226  2992  2992 E AndroidRuntime: 	at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:58)
08-24 11:17:29.226  2992  2992 E AndroidRuntime: 	at io.sentry.android.core.SentryInitProvider.onCreate(SentryInitProvider.java:25)
08-24 11:17:29.226  2992  2992 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2522)
08-24 11:17:29.226  2992  2992 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2492)
08-24 11:17:29.226  2992  2992 E AndroidRuntime: 	at io.sentry.android.core.SentryInitProvider.attachInfo(SentryInitProvider.java:43)
08-24 11:17:29.226  2992  2992 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:8323)
```

By reading the log, it's quite obvious that the DNS is not declared in the manifest. However, we cannot override the PreviewActivity manifest, which is provided by `compose-ui-tooling` dependency. Whatever DNS declared in the main `Manifest.xml` is not read and applied to this manifest.

This seriously hampers our usage of Sentry, since our process requires running composable preview in the device to ensure our quality.

**Comment by hangduykhiem** [comment]
I tried to reproduce this by creating a new project and adding the dependencies, but it didn't crash. So something must be wrong in our configuration. 🤔

**Comment by markushi** [comment]
@hangduykhiem Thanks for reaching out! This definitely sounds odd, looks like the preview seems to trigger an Activity init, which itself triggers the creation of all content providers, including our `SentryInitProvider`. 
Did you have any chance to find the root cause?

**Comment by romtsn** [comment]
> Whatever DNS declared in the main Manifest.xml is not read and applied to this manifest.

That should not be the case, the manifests are merged into a single one when building an apk/aab, so the DSN should end up in the merged manifest

**Comment by romtsn** [comment]
@hangduykhiem please let us know if you were able to gather more details or reproduce the issue on a fresh project. For now we're going to close this, but feel free to comment here if you find out more. Thank you!

**Comment by savvasenok** [comment]
> > Whatever DNS declared in the main Manifest.xml is not read and applied to this manifest.
> 
> That should not be the case, the manifests are merged into a single one when building an apk/aab, so the DSN should end up in the merged manifest of the final apk

I am not using KMP project, however a stepped upon the same problem, when i am trying to launch Compose Previews on a device. The DSN is provided in the `Application#onCreate`

**Comment by moffpage** [comment]
Having same issue, I also personally know a guy who's stuck with the same problem

**Comment by markushi** [comment]
Thanks for the feedback everyone, we'll take a look into this!

**Comment by markushi** [comment]
@moffpage @savvasenok could you share how / where you initialize the Sentry SDK? It seems like the preview code triggers the SDK init, causing the issue you're seeing.

**Comment by savvasenok** [comment]
@markushi for me it is in the `Application#onCreate()` method:
``` kotlin
override fun onCreate() {
    SentryAndroid.init(this) { options -> ... }
}
```

I am not sure how Compose on-device previews work exactly, but the breakpoints were not working. So i suppose (and may be very wrong), that compose uses some other `Application` object for previews, which does not initialize Sentry

**Comment by moffpage** [comment]
@markushi I also initialize Sentry in Application's onCreate method, although we have a condition that BuildConfig.CRASH_REPORTS_ENABLED flag should return true, it does in defaultConfig (the property is set to true in the config)

**Comment by drostowsky-givelify** [comment]
In our Android app, the repro started when we started to use Sentry API in our code. Previously, we only included the dependency in our build.gradle

```
implementation(libs.sentry)
```

which worked perfectly on its own. No Sentry API used and we got some of the Sentry monitoring benefits.

Things went south with Compose the instant we wanted to explicitly use `Sentry.captureException` and `Sentry.addBreadbrumb` as we wanted to collect a bit of custom data in Sentry. Once we used it programmatically, then the Compose Previews crashed same as reported.

We are currently resorting to a workaround
```
releaseImplementation(libs.sentry)
```
This ensures Sentry is only present in the code for our release builds to the Play Store. For day-to-day debug work, we then have a Kotlin interface 'SentryApi' we created. It is implemented in our release source set using the real Sentry API, but then just empty stubs for the implementation in our debug source set. Viola, Compose Previews worked again.

**Comment by stefanosiano** [comment]
@savvasenok @moffpage Do you manually call any Sentry API in the composable functions?

**Comment by moffpage** [comment]
No

**Comment by markushi** [comment]
Thanks everyone for reporting! I was finally able to reproduce the issue, but only for library (=non-app) modules, which depend on the Sentry SDK.

In this case I could resolve the issue by providing an empty DSN within the _library_ module's
 `<lib-name>/src/main/AndroidManifest.xml`
```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <application>
        <meta-data
            android:name="io.sentry.dsn"
            android:value="" />
    </application>
</manifest>
```

<img width="1058" alt="Image" src="https://github.com/user-attachments/assets/5f89a288-26fc-4b58-afab-8c323a102df6" />


This change may causes an issue within your app, as manifest merging will fail if you have a DSN defined, so you can utilize the tools namespace to indicate the apps manifest entry should replace the empty library one. `app/src/main/AndroidManifest.xml`

```xml
<meta-data
    android:name="io.sentry.dsn"
    android:value="https://foo@bar.ingest.de.sentry.io/1234"
    tools:node="replace" />
```

Can someone confirm the above workaround is working for them as well? In the meantime we're looking into more convenient ways of avoiding this issue.

**Comment by markushi** [comment]
Good news everyone, a [fix](https://github.com/getsentry/sentry-java/pull/4324) has landed on `main` and will be shipped with the next version of our SDK, removing the need for any workarounds.
