### ISSUE TITLE
The application crashes with StrictMode error after sentry initialization on android api 31, 32, 33.

### ISSUE THREAD

**Issue by AntonVoronkin** [getsentry/sentry-java#2905]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

7.4.1

### Proguard

Enabled

### Version

6.27.0

### Steps to Reproduce

**The application crashes with StrictMode error after sentry initialization on android api 31, 32, 33.**
**StrictMode** policy for detect the SQL leaked, the closable objects leaked and detecting network operations.

Apparently, the issue is related to "android.appcompat:appcompat-resources:1.4.2 and android.appcompat:appcompat:1.4.2" entries present in the sentry-external-modules.txt file.

Sentry plugin version: 3.11.1; sentry version: 6.27.0 (6.28.0 dont' fix this problem); targetAndroidSdkVersion 31; minAndroidSdkVersion 24

Error example: 

```
StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                                                                    	at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1987)
                                                                                                    	at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:336)
                                                                                                    	at sun.nio.ch.FileChannelImpl.finalize(FileChannelImpl.java:175)
                                                                                                    	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:319)
                                                                                                    	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:306)
                                                                                                    	at java.lang.Daemons$Daemon.run(Daemons.java:140)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: java.lang.Throwable: Explicit termination method 'close' not called
                                                                                                    	at dalvik.system.CloseGuard.openWithCallSite(CloseGuard.java:288)
                                                                                                    	at dalvik.system.CloseGuard.open(CloseGuard.java:257)
                                                                                                    	at sun.nio.ch.FileChannelImpl.<init>(FileChannelImpl.java:110)
                                                                                                    	at sun.nio.ch.FileChannelImpl.open(FileChannelImpl.java:120)
                                                                                                    	at java.io.FileInputStream.getChannel(FileInputStream.java:475)
                                                                                                    	at androidx.core.graphics.TypefaceCompatUtil.mmap(TypefaceCompatUtil.java:115)
                                                                                                    	at androidx.emoji2.text.FontRequestEmojiCompatConfig$FontRequestMetadataLoader.createMetadata(FontRequestEmojiCompatConfig.java:381)
                                                                                                    	at androidx.emoji2.text.FontRequestEmojiCompatConfig$FontRequestMetadataLoader$$ExternalSyntheticLambda0.run(Unknown Source:2)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012) 
```

### Expected Result

There are no memory leaks.

### Actual Result

There are memory leaks.

**Comment by markushi** [comment]
Hey @AntonVoronkin, thanks for reporting this issue!
This is most likely due to our File I/O instrumentation feature, which wraps uses of `FileInputStream`. This also means the root cause is not the sentry SDK but rather the wrapped implementation, in your case `androidx.core.graphics.TypefaceCompatUtil.java`.

Could you try to try an app build without Sentry instrumentation enabled? Even if disabled you should still experience the StrictMode crash.

`app/build.gradle`
````kotlin
import io.sentry.android.gradle.extensions.InstrumentationFeature
sentry {
    // other config...
    
    tracingInstrumentation {
      enabled.set(false)
    }
}
````

**Comment by AntonVoronkin** [comment]
I completely removed sentry (including gradle file), but the problem remained.

**Comment by AntonVoronkin** [comment]
I'm sorry, yesterday I got too caught up and gave the wrong answer. If the sentry is removed completely, the issue does NOT occur.
I'm sorry, yesterday I got too caught up and gave the wrong answer. If the sentry is removed completely, the issue does NOT occur. @romtsn

**Comment by romtsn** [comment]
@AntonVoronkin alright we'll investigate on our side and come back, thanks

**Comment by stefanosiano** [comment]
There is a PR with some improvement related to Closeable resources.
However, we have to investigate the native layer, yet: removing it makes this issue disappear.

**Comment by stefanosiano** [comment]
Note: there are no specific steps to reproduce this issue.
Just bundle sentry-native inside, and after a while you should get it

**Comment by romtsn** [comment]
@stefanosiano maybe it's worth a try to reproduce this again with the recent fix in sentry-native?

**Comment by markushi** [comment]
Let's try without even packaging the NDK

**Comment by markushi** [comment]
Let's retry with sentry-java 8.0.0 and it's included NDK changes.

**Comment by drewski-vshred** [comment]
Still running into this issue in the latest sentry-java 8.3.0. The exception is as follows:

```bash
Caused by: android.os.strictmode.DiskReadViolation
      	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1658)
      	at libcore.io.BlockGuardOs.access(BlockGuardOs.java:74)
      	at libcore.io.ForwardingOs.access(ForwardingOs.java:128)
      	at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:8663)
      	at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:332)
      	at java.io.File.exists(File.java:829)
      	at android.app.ContextImpl.ensureExternalDirsExistOrFilter(ContextImpl.java:3595)
      	at android.app.ContextImpl.getExternalFilesDirs(ContextImpl.java:872)
      	at android.app.ContextImpl.getExternalFilesDir(ContextImpl.java:861)
      	at android.content.ContextWrapper.getExternalFilesDir(ContextWrapper.java:311)
      	at io.sentry.android.core.DeviceInfoUtil.setDeviceIO(DeviceInfoUtil.java:230)
      	at io.sentry.android.core.DeviceInfoUtil.collectDeviceInformation(DeviceInfoUtil.java:151)
      	at io.sentry.android.core.DefaultAndroidEventProcessor.setDevice(DefaultAndroidEventProcessor.java:172)
      	at io.sentry.android.core.DefaultAndroidEventProcessor.setCommons(DefaultAndroidEventProcessor.java:129)
      	at io.sentry.android.core.DefaultAndroidEventProcessor.process(DefaultAndroidEventProcessor.java:77)
      	at io.sentry.SentryClient.processEvent(SentryClient.java:458)
      	at io.sentry.SentryClient.captureEvent(SentryClient.java:141)
      	at io.sentry.Scopes.captureExceptionInternal(Scopes.java:296)
      	at io.sentry.Scopes.captureException(Scopes.java:262)
      	at io.sentry.IScopes.captureException(IScopes.java:148)
      	at io.sentry.Sentry.captureException(Sentry.java:742)
        at com.ExampleApp.initialize(ExampleApp.kt:51)
      	at com.ExampleApp.onCreate(ExampleApp.kt:37)
      	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1277)
      	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7667)
      	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
      	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2410)
      	at android.os.Handler.dispatchMessage(Handler.java:106)
      	at android.os.Looper.loopOnce(Looper.java:226) 
      	at android.os.Looper.loop(Looper.java:313) 
      	at android.app.ActivityThread.main(ActivityThread.java:8810) 
      	at java.lang.reflect.Method.invoke(Native Method) 
      	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604) 
      	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067) 
```

In my build.gradle.kts, I have also configured

```Gradle
sentry {
        tracingInstrumentation {
            enabled.set(false)
        }
    }
```

Looks like the code is doing disk IO operations on the main thread, which is generally frowned upon.

```kotlin
import io.sentry.Sentry

try {
  aMethodThatMightFail()
} catch (e: Exception) {
  Sentry.captureException(e)
}
```

However, if the call is wrapped within a coroutine, the error does not occur

```kotlin
import io.sentry.Sentry

try {
  aMethodThatMightFail()
} catch (e: Exception) {
  CoroutineScope(Dispatchers.IO).launch {
    Sentry.captureException(e)
  }
}
```

Calling `Sentry.captureException(e)` should be **main safe** by default though, so that a coroutine is not required.

**Comment by markushi** [comment]
@drewski-vshred the issue you're seeing is a different one, see this GH issue, and in particular this comment for more details: https://github.com/getsentry/sentry-java/issues/4211#issuecomment-2684642037
