### ISSUE TITLE
java.lang.reflect.InaccessibleObjectException when initializing Java Agent with Java 21

### ISSUE THREAD

**Issue by njlaw** [getsentry/sentry-java#3082]
### Integration

sentry-opentelemetry-agent

### Java Version

21

### Version

7.0.0

#### Environment

OS: Ubuntu 22.04
Linux: 6.2.0-37-generic #38~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov  2 18:01:13 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
JVM: OpenJDK 64-Bit Server VM Corretto-21.0.1.12.1 (build 21.0.1+12-LTS, mixed mode, sharing)

#### Minimal Reproduction

1. Use any Java application.

    MyApplication.java:

    ```java
    public class MyApplication {
      public static void main(String[] args) {
        System.out.println("MyApplication");
      }
    }
    ```

2. Run:

    ```
    > javac MyApplication.java
    > java -javaagent:sentry-opentelemetry-agent-7.0.0.jar MyApplication
    ````

#### Proposed Solution

I get exactly the same error with Java 21 and the upstream OpenTelemetry Java agent 1.23.0, but the upstream 1.32.0 starts without any issues.  I suspect that [updating the upstream agent version](https://github.com/getsentry/sentry-java/blob/1f3652d529c2bd977c6e04f64b9cdb50d19a0358/buildSrc/src/main/java/Config.kt#L154) would resolve this exception with Java 21, but I am not sure what other compatibility issues that may introduce with the Sentry customizations.

### Expected Result

```
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
[otel.javaagent 2023-12-04 21:04:35:201 +0000] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: sentry-7.0.0-otel-1.23.0
MyApplication
[otel.javaagent 2023-12-04 21:04:36:332 +0000] [OkHttp http://localhost:4317/...] ERROR io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter - Failed to export metrics. The request could not be executed. Full error message: Failed to connect to localhost/127.0.0.1:4317
```

### Actual Result

```
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
[otel.javaagent 2023-12-04 21:00:07:833 +0000] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: sentry-7.0.0-otel-1.23.0
OpenTelemetry Javaagent failed to start
java.lang.ExceptionInInitializerError
	at io.opentelemetry.javaagent.tooling.muzzle.AgentTooling.<clinit>(AgentTooling.java:22)
	at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:139)
	at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:94)
	at io.opentelemetry.javaagent.tooling.AgentStarterImpl.start(AgentStarterImpl.java:78)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.initialize(AgentInitializer.java:35)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.startAgent(OpenTelemetryAgent.java:57)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.premain(OpenTelemetryAgent.java:45)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:560)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:572)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.findLoadedClass(java.lang.String) accessible: module java.base does not "opens java.lang" to unnamed module @6a38e57f
	at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:391)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:367)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:315)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:203)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:197)
	at io.opentelemetry.javaagent.tooling.muzzle.AgentCachingPoolStrategy.getFindLoadedClassMethod(AgentCachingPoolStrategy.java:114)
	at io.opentelemetry.javaagent.tooling.muzzle.AgentCachingPoolStrategy.<clinit>(AgentCachingPoolStrategy.java:57)
	... 11 more
MyApplication
[otel.javaagent 2023-12-04 21:00:08:201 +0000] [OkHttp http://localhost:4317/...] ERROR io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter - Failed to export metrics. The request could not be executed. Full error message: Failed to connect to localhost/127.0.0.1:4317
```

**Comment by adinauer** [comment]
Thanks @njlaw for opening this issue. We'll investigate and possibly bump the dependency.

**Comment by njlaw** [comment]
Thank you!  Just for reference, the here's a link to the upstream issue: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/7694  Sorry, I should have included this in the original report.

**Comment by adinauer** [comment]
@njlaw we've just released https://github.com/getsentry/sentry-java/releases/tag/7.2.0 which has a newer OTEL version. Any feedback is welcome.

**Comment by njlaw** [comment]
@adinauer Thank you!
