### ISSUE TITLE
Android ANR

### ISSUE THREAD

**Issue by zhou934381967** [getsentry/sentry-java#3125]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

1.7.36

### Proguard

Enabled

### Version

6.27.0

### Steps to Reproduce

Direct operation

### Expected Result

No ANR

### Actual Result

Android client App after using Sentry, recently appeared around 1000 ANR, mon. com.oceanwing.common.application.BaseApplication.initSentry. Help us analyze this question, what is the cause。SDK Version v6.27.0.
<img width="759" alt="截屏2023-12-29 15 11 56" src="https://github.com/getsentry/sentry-java/assets/13718172/ca283b11-ecb8-42f0-84a5-90b1e976ce78">
<img width="591" alt="截屏2023-12-29 14 52 06" src="https://github.com/getsentry/sentry-java/assets/13718172/5c72639e-ac04-4251-9b54-6bf2e27fb8eb">

**Comment by romtsn** [comment]
hi, could you please provide the complete stacktrace (i.e. expand it in the stacktrace viewer on Firebase Crashlytics), so we know which line of the Sentry SDK is causing this exactly?

**Comment by zhou934381967** [comment]
main (runnable):tid=1 systid=26431 
       at io.sentry.UncaughtExceptionHandlerIntegration.<init>(UncaughtExceptionHandlerIntegration.java:34)
       at io.sentry.SentryOptions.<init>(SentryOptions.java:2236)
       at io.sentry.SentryOptions.<init>(SentryOptions.java:2220)
       at io.sentry.android.core.SentryAndroidOptions.<init>(SentryAndroidOptions.java:206)
       at java.lang.reflect.Constructor.newInstance0(Native method)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
       at io.sentry.OptionsContainer.createInstance(OptionsContainer.java:24)
       at io.sentry.Sentry.init(Sentry.java:145)
       at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:89)
       at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:70)
       at com.oceanwing.common.application.BaseApplication.initSentry(BaseApplication.java:192)
       at com.oceanwing.common.application.BaseApplication.onCreate(BaseApplication.java)
       at com.oceanwing.soundcore.application.SoundCoreApplication.onCreate(SoundCoreApplication.java:95)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1266)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7373)
       at android.app.ActivityThread.-$$Nest$mhandleBindApplication(unavailable)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2397)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:223)
       at android.os.Looper.loop(Looper.java:324)
       at android.app.ActivityThread.main(ActivityThread.java:8595)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1061)

**Comment by romtsn** [comment]
@zhou934381967 this line shouldn't really cause ANRs. Is this the complete stacktrace? Because it differs from the one you posted on a screenshot (the topmost frame is `libc.so at _rt_sigprocmask + 8` there).

Also, when do you initialize Sentry? After Crashlytics and everything else or before?

**Comment by zhou934381967** [comment]
io.sentry.Scope.createBreadcrumbsList (Scope.java:654)
io.sentry.Scope.<init> (Scope.java:86)
io.sentry.Hub.createRootStackItem (Hub.java:69)
io.sentry.Hub.<init> (Hub.java:36)
io.sentry.Sentry.init (Sentry.java:218)
io.sentry.Sentry.init (Sentry.java:147)
io.sentry.android.core.SentryAndroid.init (SentryAndroid.java:89)
io.sentry.android.core.SentryAndroid.init (SentryAndroid.java:70)
com.oceanwing.common.application.BaseApplication.initSentry (BaseApplication.java:191)
com.oceanwing.common.application.BaseApplication.onCreate (BaseApplication.java)
com.oceanwing.soundcore.application.SoundCoreApplication.onCreate (SoundCoreApplication.java:95)
android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1211)
android.app.ActivityThread.handleBindApplication (ActivityThread.java:7506)
android.app.ActivityThread.access$1700 (ActivityThread.java:310)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2281)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loopOnce (Looper.java:226)
android.os.Looper.loop (Looper.java:313)
android.app.ActivityThread.main (ActivityThread.java:8663)
java.lang.reflect.Method.invoke (Native method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:567)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1135)

**Comment by zhou934381967** [comment]
It is the same problem, but the place of reporting is different. This is the complete stack information; Initialize when you just start the app。

main (native):tid=1 systid=7552 
#00 pc 0xe0bb8 libc.so (__ioctl + 8) (BuildId: 449f781894033dce6346794a1ee593e0)
#01 pc 0x97a3c libc.so (ioctl + 160) (BuildId: 449f781894033dce6346794a1ee593e0)
#02 pc 0x5c3dc libbinder.so (android::IPCThreadState::talkWithDriver + 284) (BuildId: 457154777950b42da3b8980272b05a0f)
#03 pc 0x5d670 libbinder.so (android::IPCThreadState::waitForResponse + 120) (BuildId: 457154777950b42da3b8980272b05a0f)
#04 pc 0x5d380 libbinder.so (android::IPCThreadState::transact + 224) (BuildId: 457154777950b42da3b8980272b05a0f)
#05 pc 0x54a6c libbinder.so (android::BpBinder::transact + 232) (BuildId: 457154777950b42da3b8980272b05a0f)
#06 pc 0x17c3c8 libandroid_runtime.so (android_os_BinderProxy_transact + 156) (BuildId: 3dc162ee82056ac87107686c01178ba5)
       at android.os.BinderProxy.transactNative(Native method)
       at android.os.BinderProxy.transact(BinderProxy.java:646)
       at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5755)
       at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1826)
       at android.app.ContextImpl.registerReceiver(ContextImpl.java:1760)
       at android.app.ContextImpl.registerReceiver(ContextImpl.java:1748)
       at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:757)
       at io.sentry.android.core.SystemEventsBreadcrumbsIntegration.register(SystemEventsBreadcrumbsIntegration.java:102)
       at io.sentry.Sentry.init(Sentry.java:237)
       at io.sentry.Sentry.init(Sentry.java:147)
       at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:89)
       at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:70)
       at com.oceanwing.common.application.BaseApplication.initSentry(BaseApplication.java:191)
       at com.oceanwing.common.application.BaseApplication.onCreate(BaseApplication.java)
       at com.oceanwing.soundcore.application.SoundCoreApplication.onCreate(SoundCoreApplication.java:95)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1287)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7127)
       at android.app.ActivityThread.-$$Nest$mhandleBindApplication(unavailable)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2220)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:211)
       at android.os.Looper.loop(Looper.java:300)
       at android.app.ActivityThread.main(ActivityThread.java:8296)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by romtsn** [comment]
But this stacktrace is different. This particular problem has already been fixed in the latest version, so you could update to 7.1.0 and it should stop appearing.
