### ISSUE TITLE
Can not exclude SentryWebfluxAutoConfiguration on Spring Boot 3.*

### ISSUE THREAD

**Issue by akiten-io** [getsentry/sentry-java#3206]
### Integration

sentry-spring-boot

### Java Version

17

### Version

6.34.0

### Steps to Reproduce

Any Projects that use `Spring Boot 3.*` can be affected this problem

application.yaml
```yaml
sentry:
  dsn: <<samledsn>>
```

main.kt
```kt
@SpringBootApplication(exclude = [SentryWebfluxAutoConfiguration::class])
class SampleApplication

fun main(args: Array<String>) {
    runApplication<SampleApplication>(*args)
}
```

FYI) 
following commit on spring boot repository causes this issue 
https://github.com/spring-projects/spring-boot/commit/08022ba86efa294f77574bda07851901b6c2b520

### Expected Result

SentryWebfluxAutoConfiguration can be excluded from auto configured classes

### Actual Result

```
java.lang.IllegalStateException: The following classes could not be excluded because they are not auto-configuration classes:
	- io.sentry.spring.boot.SentryWebfluxAutoConfiguration

	at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.handleInvalidExcludes(AutoConfigurationImportSelector.java:211) ~[spring-boot-autoconfigure-3.2.2.jar:3.2.2]
	at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.checkExcludedClasses(AutoConfigurationImportSelector.java:197) ~[spring-boot-autoconfigure-3.2.2.jar:3.2.2]
	at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.getAutoConfigurationEntry(AutoConfigurationImportSelector.java:129) ~[spring-boot-autoconfigure-3.2.2.jar:3.2.2]
	at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector$AutoConfigurationGroup.process(AutoConfigurationImportSelector.java:430) ~[spring-boot-autoconfigure-3.2.2.jar:3.2.2]
	at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGrouping.getImports(ConfigurationClassParser.java:813) ~[spring-context-6.1.3.jar:6.1.3]
	at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGroupingHandler.processGroupImports(ConfigurationClassParser.java:743) ~[spring-context-6.1.3.jar:6.1.3]
	at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorHandler.process(ConfigurationClassParser.java:714) ~[spring-context-6.1.3.jar:6.1.3]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:183) ~[spring-context-6.1.3.jar:6.1.3]
```

**Comment by adinauer** [comment]
Hello @akiten-io thanks for the PR and opening this issue. Will take a look at the PR.
