### ISSUE TITLE
Sentry for Java silently fails when using ProGuard

### ISSUE THREAD

**Issue by sproctor** [getsentry/sentry-java#3340]
### Integration

sentry

### Java Version

17

### Version

7.8.0

### Steps to Reproduce

1. build with proguard (ie Compose for Desktop gradle task proguardReleaseJars)
2. Crash app
3. Nothing is sent

Adding ProGuard rules from Android fixes this. It's never mentioned that they might be necessary. Better would be to crash on init when whatever is causing the failure is missing.

### Expected Result

Crash report to be sent to sentry, obviously.

### Actual Result

Crash is silently ignored.

**Comment by romtsn** [comment]
hi @sproctor, sorry you're having troubles, what rules did you add to make it work? We're not using proguard on JVM so were not simply aware of this issue.

**Comment by sproctor** [comment]
This is what I used:

```
-keep class io.sentry.** { *; }
-keepclassmembers enum io.sentry.** { *; }
```

**Comment by romtsn** [comment]
hm, these should not be needed for the sdk to work, could you perhaps share a reproducible project? Or enabled debug logs and share the output?
```kotlin
Sentry.init { it.isDebug = true }
```

**Comment by sproctor** [comment]
Stack trace:
```
INFO: Uncaught exception received.
DEBUG: Capturing event: 79ba499d0803417594513f3c39037588
DEBUG: Extracted 163 modules from resources.
INFO: Session is null on scope.withSession
ERROR: Error while capturing event with id: 79ba499d0803417594513f3c39037588
java.lang.AbstractMethodError: Receiver class io.a.k.k$$Lambda$230/0x00000008007769a0 does not define or inherit an implementation of the resolved method 'abstract void accept$56afaa06(b.b.b.i.bR)' of interface io.a.an.
	at io.a.am.a(SourceFile:933)
	at io.a.k.k.a(SourceFile:77)
	at io.a.ax.a(SourceFile:216)
	at io.a.r.a(SourceFile:120)
	at io.a.r.a(SourceFile:90)
	at io.a.aq.a(SourceFile:525)
	at io.a.s.a(SourceFile:30)
	at io.a.bJ.uncaughtException(SourceFile:109)
	at java.base/java.lang.ThreadGroup.uncaughtException(Unknown Source)
	at java.base/java.lang.ThreadGroup.uncaughtException(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.processException(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

Relevant mappings
```
androidx.compose.foundation.text.TextDelegate -> b.b.b.i.br:
# {"fileName":"TextDelegate.kt","id":"sourceFile"}
io.sentry.util.TracingUtils -> io.a.k.k:
# {"fileName":"TracingUtils.java","id":"sourceFile"}
    77:77:androidx.compose.foundation.text.TextFieldKeyInputKt maybeUpdateBaggage$4d1dbfc4(io.sentry.IScope,io.sentry.SentryOptions) -> a
    79:88:void lambda$maybeUpdateBaggage$3$6f99b2d6(io.sentry.SentryOptions,io.sentry.IScope,androidx.compose.foundation.text.TextFieldKeyInputKt) -> a
io.sentry.Scope$IWithPropagationContext -> io.a.an:
# {"fileName":"Scope.java","id":"sourceFile"}
    void accept$56afaa06(androidx.compose.foundation.text.TextFieldKeyInputKt) -> accept$56afaa06
io.sentry.Scope -> io.a.am:
# {"fileName":"Scope.java","id":"sourceFile"}
    io.sentry.SentryLevel level -> a
io.sentry.util.TracingUtils -> io.a.k.k:
# {"fileName":"TracingUtils.java","id":"sourceFile"}
    77:77:androidx.compose.foundation.text.TextFieldKeyInputKt maybeUpdateBaggage$4d1dbfc4(io.sentry.IScope,io.sentry.SentryOptions) -> a
    79:88:void lambda$maybeUpdateBaggage$3$6f99b2d6(io.sentry.SentryOptions,io.sentry.IScope,androidx.compose.foundation.text.TextFieldKeyInputKt) -> a
io.sentry.SentryClient -> io.a.ax:
# {"fileName":"SentryClient.java","id":"sourceFile"}
    io.sentry.SentryOptions options -> a
io.sentry.Hub -> io.a.r:
# {"fileName":"Hub.java","id":"sourceFile"}
    io.sentry.protocol.SentryId lastEventId -> a
io.sentry.Sentry -> io.a.aq:
# {"fileName":"Sentry.java","id":"sourceFile"}
    java.lang.ThreadLocal currentHub -> a
io.sentry.HubAdapter -> io.a.s:
# {"fileName":"HubAdapter.java","id":"sourceFile"}
    io.sentry.HubAdapter INSTANCE -> a
io.sentry.UncaughtExceptionHandlerIntegration -> io.a.bJ:
# {"fileName":"UncaughtExceptionHandlerIntegration.java","id":"sourceFile"}
    92:141:void uncaughtException(java.lang.Thread,java.lang.Throwable) -> uncaughtException
    1147:1150:java.lang.Throwable getUnhandledThrowable(java.lang.Thread,java.lang.Throwable):147:150 -> uncaughtException
    1147:1150:void uncaughtException(java.lang.Thread,java.lang.Throwable):98 -> uncaughtException
    2049:2051:io.sentry.Hint io.sentry.util.HintUtils.createWithTypeCheckHint(java.lang.Object):49:51 -> uncaughtException
    2049:2051:void uncaughtException(java.lang.Thread,java.lang.Throwable):107 -> uncaughtException
    2055:2056:void io.sentry.util.HintUtils.setTypeCheckHint(io.sentry.Hint,java.lang.Object):55:56 -> uncaughtException
    2055:2056:io.sentry.Hint io.sentry.util.HintUtils.createWithTypeCheckHint(java.lang.Object):50 -> uncaughtException
    2055:2056:void uncaughtException(java.lang.Thread,java.lang.Throwable):107 -> uncaughtException
    3045:3045:io.sentry.hints.EventDropReason io.sentry.util.HintUtils.getEventDropReason(io.sentry.Hint):45:45 -> uncaughtException
    3045:3045:void uncaughtException(java.lang.Thread,java.lang.Throwable):111 -> uncaughtException
```

**Comment by kahest** [comment]
@sproctor thanks for the additional details, we need to investigate this more an will follow up

**Comment by projectdelta6** [comment]
I've just had this same error on a project after updating the sentry lib to v8.1.0, adding the progaurd rules did not help, so I had to roll back to the previous known working version for the Sentry lib: v7.19.0 and then it works again 🤷‍♂

**Comment by projectdelta6** [comment]
Hi @romtsn no the app just crashes on startup with this error:
```
io.sentry.auto-init read: true
... (some other unrelated logs) ...
FATAL EXCEPTION: main
Process: my.app.package, PID: 11239
java.lang.AbstractMethodError: abstract method "void io.sentry.Integration.register(io.sentry.IScopes, io.sentry.SentryOptions)"
	at io.sentry.Sentry.init(Sentry.java:343)
	at io.sentry.Sentry.init(Sentry.java:215)
	at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:97)
	at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:69)
	at io.sentry.android.core.SentryInitProvider.onCreate(SentryInitProvider.java:25)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2494)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2464)
	at io.sentry.android.core.SentryInitProvider.attachInfo(SentryInitProvider.java:43)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7602)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7125)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7009)
	at android.app.ActivityThread.access$1700(ActivityThread.java:274)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2098)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8068)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

That is if I use Sentry lib version 8.1.0 and sentry gradle plugin version 4.14.1
I did set `debug = true` but I don't see any additional log info
if I revert sentry lib to v7.19.0 and sentry gradle plugin to v14.13.0 then the app builds and runs fine including sending reports to sentry. (I'm not sure is the sentry gradle plugin is affecting anything here?)

**Comment by lcian** [comment]
@projectdelta6 if you are using our Android Gradle Plugin, you should not include the Sentry lib in your dependencies, it will be added with the correct version by the plugin.

If you want to use `8.1.0` you need to use version `5.1.0` of the plugin, otherwise if you add the plugin on say `4.14.1` and the lib on `8.1.0` those will not be compatible and you might run into issues.

You can refer to the changelog here https://github.com/getsentry/sentry-android-gradle-plugin/blob/main/CHANGELOG.md to see which version of the plugin maps to which version of the SDK.

Does this solve the problem?

**Comment by projectdelta6** [comment]
Ah I see, yes fixing my versions to `8.1.0` and `5.1.0` fixed the crash, my issue then is that I do need to library import because I am sending custom sentry events in my Log wrapper using `Sentry.captureEvent(...)` which becomes unavailable if I remove the library and have only the plugin... is there something else that I'm missing?

**Comment by projectdelta6** [comment]
I should add that is in a multi module app project where the Log wrapper is in a shared library module which is used but 2 other (app and instant app) modules, I have added the sentry plugin on all 3 modules but `Sentry.captureEvent(...)` is not available without the sentry lib inport in the shared module

**Comment by romtsn** [comment]
yeah that's currently a limitation of our gradle plugin that it cannot auto-install sentry dependency to other modules. I'd suggest to add the dependency yourself to the module where you have the Log wrapper, and then set the gradle plugin to use the same version that you added manually as follows:

```
sentry {
  autoInstallation.sentryVersion = "<your_version>"
}
```

**Comment by lbloder** [comment]
We will add a section describing how to use Proguard with Sentry in the JVM environment.

Unfortunately proguard can't automatically take rules from jars `META-INF/proguard` directory. Only R8 can do that, which is not yet supported on KMP for Desktop. 

We will close this for now and revisit embedding proguard rules once R8 for desktop [drops](https://youtrack.jetbrains.com/issue/CMP-5121) or support is added to [proguard](https://github.com/Guardsquare/proguard/issues/337).
