### ISSUE TITLE
Crash from FOREIGN KEY constraint failed

### ISSUE THREAD

**Issue by stevie-patreon** [getsentry/sentry-java#3600]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

8.5.0

### Proguard

Enabled

### Version

7.8.0

### Steps to Reproduce

unknown

### Expected Result

unknown

### Actual Result

```
Fatal Exception: android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY[787])
       at android.database.sqlite.SQLiteConnection.nativeExecute(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:1033)
       at android.database.sqlite.SQLiteSession.endTransactionUnchecked(SQLiteSession.java:439)
       at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:403)
       at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:990)
       at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.endTransaction(FrameworkSQLiteDatabase.kt:75)
       at io.sentry.android.sqlite.SentrySupportSQLiteDatabase.endTransaction(SentrySupportSQLiteDatabase.kt:3)
       at androidx.room.RoomDatabase.internalEndTransaction(RoomDatabase.kt:553)
       at androidx.room.RoomDatabase.endTransaction(RoomDatabase.kt:543)
       at androidx.room.RoomDatabaseKt$withTransaction$transactionBlock$1.invokeSuspend(RoomDatabaseExt.kt:68)
       at androidx.room.RoomDatabaseKt$withTransaction$transactionBlock$1.invoke(RoomDatabaseExt.kt:1)
```

**Comment by stevie-patreon** [comment]
Version for com.android.tools.build:gradle -> 8.5.0
Version for io.sentry.sentry-android -> 7.8.0
Version for io.sentry.android.gradle -> 4.7.1
Version for io.sentry.kotlin.compiler.gradle -> 4.7.1

**Comment by stevie-patreon** [comment]
We're getting reports of lots of crashes through our Crashlytics integration, with the stack trace above

**Comment by romtsn** [comment]
Hi @stevie-patreon are there any other stackframes, or is this the full stacktrace? I suspect the problem lies elsewhere, because our class doesn't have to do anything with `endTransaction`, you can see that we're not even overriding it but just delegating to the original SQLiteDatabase: https://github.com/getsentry/sentry-java/blob/main/sentry-android-sqlite/src/main/java/io/sentry/android/sqlite/SentrySupportSQLiteDatabase.kt

**Comment by stevie-patreon** [comment]
Ah, I see. I think I misunderstood that the sentry db in the stacktrace meant that this was an internal db of sentry's that was crashing. If that's not the case, then you can close this

**Comment by romtsn** [comment]
yeah, we don't have any database usages in the SDK (and any 3rd-party deps fwiw, unless it's an integration like sqlite here), our stackframe just happened to be there due to [auto-instrumentation](https://docs.sentry.io/platforms/android/integrations/room-and-sqlite/#auto-installation-with-the-sentry-android-gradle-plugin).
