### ISSUE TITLE
setup with java/android does not work properly

### ISSUE THREAD

**Issue by thisames** [getsentry/sentry-java#3624]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

8.4.0

### Proguard

Enabled

### Version

7.13.0

### Steps to Reproduce

1. just do a setup with kotlin/java
```java
  @Override
  public void onCreate() {
    strictMode();
    super.onCreate();

     SentryAndroid.init(
        this,
        options -> {
          options.setDsn("https://examplePublicKey@o0.ingest.sentry.io/0");
          /*
          use options, for example, to add a beforeSend callback:

          options.setBeforeSend((event, hint) -> {
            process event
          });
           */
        });

  }
```

### Expected Result

init with the options settings sitting correctly.

### Actual Result

no option is setted in configuration. returning a FATAL EXCEPTION

FATAL EXCEPTION: main
                                                                                                    Process: com.phonereplay.posthogtesting, PID: 11389
                                                                                                    java.lang.RuntimeException: Unable to get provider io.sentry.android.core.SentryInitProvider: java.lang.IllegalArgumentException: DSN is required. Use empty string or set enabled to false in SentryOptions to disable SDK.
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:7770)
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7276)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6983)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2236)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
                                                                                                    Caused by: java.lang.IllegalArgumentException: DSN is required. Use empty string or set enabled to false in SentryOptions to disable SDK.
                                                                                                    	at io.sentry.Sentry.initConfigurations(Sentry.java:378)
                                                                                                    	at io.sentry.Sentry.init(Sentry.java:230)
                                                                                                    	at io.sentry.Sentry.init(Sentry.java:167)
                                                                                                    	at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:93)
                                                                                                    	at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:64)
                                                                                                    	at io.sentry.android.core.SentryInitProvider.onCreate(SentryInitProvider.java:25)
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2619)
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2589)
                                                                                                    	at io.sentry.android.core.SentryInitProvider.attachInfo(SentryInitProvider.java:43)
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:7765)

**Comment by thisames** [comment]
the problem is probably happening because the implementation of ManifestMetadataReader is having a collateral effect with the configuration with kotlin/android

More precisely, I think the problem is in `isAutoInit`.

https://github.com/getsentry/sentry-java/blob/d4b1f82d2bdf3415427ba550509483bbf210d787/sentry-android-core/src/main/java/io/sentry/android/core/ManifestMetadataReader.java#L525-L539

when
`boolean autoInit = true;`
the function ends up becoming redundant, causing `autoinit` to always be `true`.

I just set `autoInit` to `false` and everything went back to working as it should.

I tested it on the samples present in the repository

Can I analyze the cases more deeply and prepare a PR to resolve this?

**Comment by romtsn** [comment]
hey, sorry you're having troubles. we mention this in the docs that if you want to initialize the SDK in code, you'd have to disable auto-init in the manifest: https://docs.sentry.io/platforms/android/configuration/manual-init/#manual-initialization

**Comment by thisames** [comment]
> hey, sorry you're having troubles. we mention this in the docs that if you want to initialize the SDK in code, you'd have to disable auto-init in the manifest: https://docs.sentry.io/platforms/android/configuration/manual-init/#manual-initialization

sorry for my inattention
