### ISSUE TITLE
Crash due to android.database.sqlite.SQLiteFullException - database or disk is full (code 13 SQLITE_FULL)

### ISSUE THREAD

**Issue by maximkir-fl** [getsentry/sentry-java#3638]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

8.5.0

### Proguard

Enabled

### Version

7.11.0

### Steps to Reproduce

Device:

![Image](https://github.com/user-attachments/assets/17ff4c12-c549-49c3-b536-679a37b43501)

```kotlin
Fatal Exception: android.database.sqlite.SQLiteFullException: database or disk is full (code 13 SQLITE_FULL)
       at android.database.sqlite.SQLiteConnection.nativeExecute(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:709)
       at android.database.sqlite.SQLiteSession.endTransactionUnchecked(SQLiteSession.java:439)
       at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:403)
       at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:589)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:422)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
       at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableOrReadableDatabase(FrameworkSQLiteOpenHelper.kt:231)
       at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.innerGetDatabase(FrameworkSQLiteOpenHelper.kt:222)
       at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getSupportDatabase(FrameworkSQLiteOpenHelper.kt:151)
       at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.kt:104)
       at io.sentry.android.sqlite.SentrySupportSQLiteOpenHelper$sentryWritableDatabase$2.invoke(SentrySupportSQLiteOpenHelper.java:40)
       at io.sentry.android.sqlite.SentrySupportSQLiteOpenHelper$sentryWritableDatabase$2.invoke(SentrySupportSQLiteOpenHelper.java:39)
       at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
       at io.sentry.android.sqlite.SentrySupportSQLiteOpenHelper.getSentryWritableDatabase(SentrySupportSQLiteOpenHelper.kt:39)
       at io.sentry.android.sqlite.SentrySupportSQLiteOpenHelper.getWritableDatabase(SentrySupportSQLiteOpenHelper.kt:48)
       at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:629)
       at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:448)
       at androidx.work.impl.model.SystemIdInfoDao_Impl.getWorkSpecIds(SystemIdInfoDao_Impl.java:165)
       at androidx.work.impl.background.systemjob.SystemJobScheduler.reconcileJobs(SystemJobScheduler.java:310)
       at androidx.work.impl.utils.ForceStopRunnable.cleanUp(ForceStopRunnable.java:289)
       at androidx.work.impl.utils.ForceStopRunnable.forceStopRunnable(ForceStopRunnable.java:252)
       at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:135)
       at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)
```

### Expected Result

NOP on full DB error.

### Actual Result

Background crash.

**Comment by markushi** [comment]
Our Sentry SDK is not using any database, we just wrap any existing database calls using instrumentation. In this case this means `SQLiteFullException` is caused by a database managed within your app code.
If you still feel like this issue is on the sentry side, please let us know and we'll re-open this issue.

**Comment by romtsn** [comment]
@maximkir-fl the stacktrace shows that your app uses DB, but indirectly (probably through `WorkManager`). You can certainly disable auto-instrumentation as [follows](https://docs.sentry.io/platforms/android/integrations/room-and-sqlite/#configure), but the crash will not go away.
