### ISSUE TITLE
 getKernelVersion() method causes crash with  java.io.FileNotFoundException: /proc/version (Permission denied)

### ISSUE THREAD

**Issue by MaTriXy** [getsentry/sentry-java#472]
Method getKernelVersion()
Causes **FileNotFoundException** on various devices.
(Permission denied) actually. 

I would suggest that prior to reading from proc like in this [PR](https://github.com/getsentry/sentry-java/commit/052cf38d60fe77b06f0222d4a344eab50edd3d16)
might you try first check access to the file.

**Comment by pnemonic78** [comment]
```
io.sentry.android.event.helper.AndroidEventBuilderHelper: Exception while attempting to read kernel information
java.io.FileNotFoundException: /proc/version (Permission denied)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(FileInputStream.java:200)
at java.io.FileInputStream.(FileInputStream.java:150)
at java.io.FileInputStream.(FileInputStream.java:103)
at java.io.FileReader.(FileReader.java:58)
at io.sentry.android.event.helper.AndroidEventBuilderHelper.getKernelVersion(AndroidEventBuilderHelper.java:331)
at io.sentry.android.event.helper.AndroidEventBuilderHelper.(AndroidEventBuilderHelper.java:43)
at io.sentry.android.AndroidSentryClientFactory.createSentryClient(AndroidSentryClientFactory.java:68)
at io.sentry.SentryClientFactory.sentryClient(SentryClientFactory.java:55)
at io.sentry.Sentry.init(Sentry.java:80)
at MySdk.a(MySdk.java:2035)
at MyContentProvider.onCreate(MyContentProvider.java:21)
at android.content.ContentProvider.attachInfo(ContentProvider.java:1912)
at android.content.ContentProvider.attachInfo(ContentProvider.java:1887)
at android.app.ActivityThread.installProvider(ActivityThread.java:6284)
at android.app.ActivityThread.installContentProviders(ActivityThread.java:5850)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5771)
at android.app.ActivityThread.-wrap1(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6540)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by benjamingr** [comment]
Related https://github.com/getsentry/sentry-java/commit/052cf38d60fe77b06f0222d4a344eab50edd3d16 

@JeremR @bretthoerner

**Comment by bretthoerner** [comment]
Two questions,

1. This is caught and simply logged, right? So it's annoying but it doesn't break the SDK does it? Or am I reading incorrectly?
2. Do y'all know of a fallback we can use, or if this file is unreadable do we just not know the kernel version?

**Comment by benjamingr** [comment]
> This is caught and simply logged, right? So it's annoying but it doesn't break the SDK does it? Or am I reading incorrectly? (I'm going to fix regardless, of course)

An embedder of us complained about a crash, but we read the code a thousand times and are now convinced that the crash is probably unrelated.

>  Do y'all know of a fallback we can use, or if this file is unreadable do we just not know the kernel version?

What about `System.getProperty("os.version");`?

**Comment by bretthoerner** [comment]
> What about `System.getProperty("os.version");`?

Oh, good idea.

**Comment by benjamingr** [comment]
@bretthoerner if you add a `CONTRIBUTING.md` with instructions on how to add code to the sentry client and test it - I wouldn't mind fixing these sort of issues in the future and coming with a PR rather than an issue.

**Comment by bretthoerner** [comment]
Cool, I'll work on a `CONTRIBUTING.md`. I did start a tiny PR to track along with this, too: #474

**Comment by JeremR** [comment]
Sorry for introducing this issue, my bad I didn't check for access :(

Do you have an idea this issue appears on a specific Android version or on a specific brand or platform (msm, mtk, x86, ...) ?

**Comment by bretthoerner** [comment]
I didn't even realize `/proc` could be locked down in that way, so it's not your fault. I'm curious how good the values are for `os.version`, though.

**Comment by benjamingr** [comment]
> Do you have an idea this issue appears on a specific Android version or on a specific brand or platform (msm, mtk, x86, ...) ?

Sorry, we got it from an embedder of our SDK who happened to get the error in crashlytics. I have no idea where the error originated - I've asked for additional details - I'll post as I have them.

**Comment by benjamingr** [comment]
Hey, do you have an ETA on a version fixing this?

**Comment by bretthoerner** [comment]
Do you mind reviewing #474? If it looks good I can cut a bugfix release.

Though I'm still confused how this exception (which is caught) is getting into Crashlytics. They must be hooking in the `Log` system, I guess?

**Comment by bretthoerner** [comment]
Pushing out `1.3.1` to Maven Central now.

**Comment by benjamingr** [comment]
Thank you for the quick and professional response - inspires confidence :)
