### ISSUE TITLE
Uncaught ConnectionException.

### ISSUE THREAD

**Issue by cbuonocore-toasttab** [getsentry/sentry-java#491]
Had an uncaught sentry ConnectionException propagate during use of Sentry.record(). 

Issue occurred on sentry-android 1.2.2. Didn't see any existing issues reported with this.

Appreciate any clarification.

Partial Stack trace below:

`E/io.sentry.connection.AsyncConnection: An exception occurred while sending the event to Sentry.io.sentry.connection.ConnectionException: An exception occurred while submitting the event to the Sentry server.

**Comment by bretthoerner** [comment]
Was there a stacktrace logged? I don't have any known unhandled exceptions, so a full log/traceback would help.

Just to clarify, this went uncaught and bubbled up into your app itself (crashing it)?

**Comment by cbuonocore-toasttab** [comment]
This would be a fatal error if left uncaught.

```
E/io.sentry.connection.AsyncConnection: An exception occurred while sending the event to Sentry.io.sentry.connection.ConnectionException: An exception occurred while submitting the event to the Sentry server.
                                                                                        at io.sentry.connection.HttpConnection.doSend(HttpConnection.java:182) ~[na:0.0]
                                                                                        at io.sentry.connection.AbstractConnection.send(AbstractConnection.java:71) ~[na:0.0]
                                                                                        at io.sentry.connection.BufferedConnection.send(BufferedConnection.java:102) ~[na:0.0]
                                                                                        at io.sentry.connection.AsyncConnection$EventSubmitter.run(AsyncConnection.java:171) ~[na:0.0]
                                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) ~[na:0.0]
                                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) ~[na:0.0]
                                                                                        at java.lang.Thread.run(Thread.java:841) ~[na:0.0]
                                                                                      Caused by: java.net.UnknownHostException: Unable to resolve host "sentry.io": No address associated with hostname
                                                                                        at java.net.InetAddress.lookupHostByName(InetAddress.java:424) ~[na:0.0]
                                                                                        at java.net.InetAddress.getAllByNameImpl(InetAddress.java:236) ~[na:0.0]
                                                                                        at java.net.InetAddress.getAllByName(InetAddress.java:214) ~[na:0.0]
                                                                                        at com.android.okhttp.internal.Dns$1.getAllByName(Dns.java:28) ~[na:0.0]
                                                                                        at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:216) ~[na:0.0]
                                                                                        at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:122) ~[na:0.0]
                                                                                        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:292) ~[na:0.0]
                                                                                        at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255) ~[na:0.0]
                                                                                        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206) ~[na:0.0]
                                                                                        at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345) ~[na:0.0]
                                                                                        at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:89) ~[na:0.0]
                                                                                        at com.android.okhttp.internal.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:161) ~[na:0.0]
                                                                                        at io.sentry.connection.HttpConnection.doSend(HttpConnection.java:153) ~[na:0.0]
                                                                                        ... 6 common frames omitted
                                                                                      Caused by: libcore.io.GaiException: getaddrinfo failed: EAI_NODATA (No address associated with hostname)
                                                                                        at libcore.io.Posix.getaddrinfo(Native Method) ~[na:0.0]
                                                                                        at libcore.io.ForwardingOs.getaddrinfo(ForwardingOs.java:61) ~[na:0.0]
                                                                                        at java.net.InetAddress.lookupHostByName(InetAddress.java:405) ~[na:0.0]
                                                                                        ... 18 common frames omitted
```

**Comment by bretthoerner** [comment]
Hmm, I don't see how it bubbled up as a fatal exception that you had to catch.

It's just an error log: https://github.com/getsentry/sentry-java/blob/master/sentry/src/main/java/io/sentry/connection/AsyncConnection.java#L175

When the device's network is unavailable the send will fail, but the event remains on disk to be retried later.

**Comment by cbuonocore-toasttab** [comment]
Hey Brett, seems right - must have been sent the logged exception. Can close this for now. Thanks for the reply.

**Comment by bretthoerner** [comment]
Hmm, can you not dynamically configure the IntelliJ appender to ignore `io.sentry.*`? We have a number of error logs since they are meant for user applications -- there may be a bunch that would effect your users that they don't care about.

**Comment by nbransby** [comment]
Possibly I haven't looked yet TBH I know very little about how sl4j works

**Comment by nbransby** [comment]
Thanks for the pointer I believe this does the trick (kotlin)
```
            val logger = org.apache.log4j.Logger.getRootLogger()
            logger.getAppender("DIALOG").addFilter(object : Filter() {
                override fun decide(event: LoggingEvent?) = 
                    if(event?.loggerName?.startsWith("#io.sentry.") == true) DENY else NEUTRAL
            })
```
