### ISSUE TITLE
java.nio.file.Path may not be available on Android?

### ISSUE THREAD

**Issue by bretthoerner** [getsentry/sentry-java#493]
Via: https://github.com/getsentry/sentry/issues/5939

```
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/nio/file/Path;
                                                                            at io.sentry.marshaller.json.SentryJsonGenerator.writeObject(SentryJsonGenerator.java:75)
                                                                            at io.sentry.marshaller.json.SentryJsonGenerator.writeObject(SentryJsonGenerator.java:60)
                                                                            at com.fasterxml.jackson.core.JsonGenerator.writeObjectField(JsonGenerator.java:1662)
                                                                            at io.sentry.marshaller.json.JsonMarshaller.writeContexts(JsonMarshaller.java:317)
                                                                            at io.sentry.marshaller.json.JsonMarshaller.writeContent(JsonMarshaller.java:195)
                                                                            at io.sentry.marshaller.json.JsonMarshaller.marshall(JsonMarshaller.java:157)
                                                                            at io.sentry.connection.HttpConnection.doSend(HttpConnection.java:155)
                                                                            at io.sentry.connection.AbstractConnection.send(AbstractConnection.java:71)
                                                                            at io.sentry.connection.BufferedConnection.send(BufferedConnection.java:102)
                                                                            at io.sentry.connection.AsyncConnection$EventSubmitter.run(AsyncConnection.java:171)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                            at java.lang.Thread.run(Thread.java:761)
```

Definitely confusing: https://developer.android.com/reference/java/nio/file/Path.html

I'm going to try this on Android locally right now.

**Comment by bretthoerner** [comment]
https://github.com/getsentry/sentry-java/commit/f9f04c29b2f8267183ed621b7474a0fd76da67c2

@jrjohnson1231 I'm releasing 1.5.1

**Comment by jrjohnson1231** [comment]
Thanks for fixing this so quickly!
