### ISSUE TITLE
Android SDK: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/nio/file/Path;

### ISSUE THREAD

**Issue by bjhexn** [getsentry/sentry-java#506]
Android SDK version：compile 'io.sentry:sentry-android:1.5.0' 

How can i resolve it ?

09-07 19:51:03.389 8930-9451/com.xx.xx E/AndroidRuntime: FATAL EXCEPTION: sentry-pool-1-thread-1
                                                                           Process: com.xx.xx, PID: 8930
                                                                           java.lang.NoClassDefFoundError: Failed resolution of: Ljava/nio/file/Path;
                                                                               at io.sentry.marshaller.json.SentryJsonGenerator.writeObject(SentryJsonGenerator.java:75)
                                                                               at io.sentry.marshaller.json.SentryJsonGenerator.writeObject(SentryJsonGenerator.java:60)
                                                                               at com.fasterxml.jackson.core.JsonGenerator.writeObjectField(JsonGenerator.java:1662)
                                                                               at io.sentry.marshaller.json.JsonMarshaller.writeContexts(JsonMarshaller.java:317)
                                                                               at io.sentry.marshaller.json.JsonMarshaller.writeContent(JsonMarshaller.java:195)
                                                                               at io.sentry.marshaller.json.JsonMarshaller.marshall(JsonMarshaller.java:157)
                                                                               at io.sentry.connection.HttpConnection.doSend(HttpConnection.java:155)
                                                                               at io.sentry.connection.AbstractConnection.send(AbstractConnection.java:71)
                                                                               at io.sentry.connection.BufferedConnection.send(BufferedConnection.java:102)
                                                                               at io.sentry.connection.AsyncConnection$EventSubmitter.run(AsyncConnection.java:171)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                               at java.lang.Thread.run(Thread.java:818)
                                                                            Caused by: java.lang.ClassNotFoundException: Didn't find class "java.nio.file.Path" on path: DexPathList[[zip file "/data/app/com.sankuai.caipiao.machine-2/base.apk"],nativeLibraryDirectories=[/data/app/com.sankuai.caipiao.machine-2/lib/arm, /data/app/com.sankuai.caipiao.machine-2/base.apk!/lib/armeabi, /vendor/lib, /system/lib]]
                                                                               at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                               at io.sentry.marshaller.json.SentryJsonGenerator.writeObject(SentryJsonGenerator.java:75) 
                                                                               at io.sentry.marshaller.json.SentryJsonGenerator.writeObject(SentryJsonGenerator.java:60) 
                                                                               at com.fasterxml.jackson.core.JsonGenerator.writeObjectField(JsonGenerator.java:1662) 
                                                                               at io.sentry.marshaller.json.JsonMarshaller.writeContexts(JsonMarshaller.java:317) 
                                                                               at io.sentry.marshaller.json.JsonMarshaller.writeContent(JsonMarshaller.java:195) 
                                                                               at io.sentry.marshaller.json.JsonMarshaller.marshall(JsonMarshaller.java:157) 
                                                                               at io.sentry.connection.HttpConnection.doSend(HttpConnection.java:155) 
                                                                               at io.sentry.connection.AbstractConnection.send(AbstractConnection.java:71) 
                                                                               at io.sentry.connection.BufferedConnection.send(BufferedConnection.java:102) 
                                                                               at io.sentry.connection.AsyncConnection$EventSubmitter.run(AsyncConnection.java:171) 
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                               at java.lang.Thread.run(Thread.java:818) 
                                                                           	Suppressed: java.lang.ClassNotFoundException: java.nio.file.Path
                                                                               at java.lang.Class.classForName(Native Method)
                                                                               at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                               at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                               		... 14 more

**Comment by bretthoerner** [comment]
This was a bug in 1.5.0, please upgrade to 1.5.1 or later.

**Comment by bjhexn** [comment]
It's OK  Thanks bretthoerner!
