### ISSUE TITLE
connection problem

### ISSUE THREAD

**Issue by arielesc** [getsentry/sentry-java#523]
I try to use Sentry for the first time, i tried some basic exceptions errors but i cant see them on my project in Sentry. I get this error: 
io.sentry.connection.AsyncConnection     : An exception occurred while sending the event to Sentry.

and that is my simple code:
package com.springBoot.springboot;

import java.util.Arrays;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Bean;

import io.sentry.Sentry;

@SpringBootApplication
public class Application {

	

	@Bean
	public CommandLineRunner commandLineRunner(ApplicationContext ctx) {
		return args -> {
			Sentry.init("https://fbc0bfe9a3a24bb09dce61166386f8d8:f7538704c66649fcb5be5f3f3e659591@sentry.io/233687");

			try {
				int[] arr = {1 , 2 , 3};
				arr[4] = 10;
				 System.out.println("Hello World");
				
			} catch (Exception e) {
				Sentry.capture(e);
			}
		};
	}
	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}
}

any help? Thanks

**Comment by bretthoerner** [comment]
Is anything else logged along with the `io.sentry.connection.AsyncConnection`? There is usually a cause associated with it that provides more information.

**Comment by arielesc** [comment]
yes their is:

Caused by: java.net.UnknownHostException: sentry.io

can you help me?
Thanks!

**Comment by arielesc** [comment]
I made a new project on the Sentry website, then i checked what is his dsn and i puted on ,y code as i showd below. i just want to see the basic error with Sentry, what am i missing?

**Comment by bretthoerner** [comment]
`Caused by: java.net.UnknownHostException`

Seems like for some reason the machine you're running this on can't resolve DNS?

Can you `ping sentry.io` on that machine?

**Comment by arielesc** [comment]
How can i check it?

**Comment by bretthoerner** [comment]
Are you running your Spring test from the command line? Just try typing `ping sentry.io` there.

**Comment by arielesc** [comment]
I run it on my cmd:
"Ping request could not find host sentry.io. please check the name and try again".

**Comment by arielesc** [comment]
Maybe you right, so how can i fix it?
Thanks!

**Comment by bretthoerner** [comment]
What about `ping 35.188.42.15`?

**Comment by arielesc** [comment]
![image](https://user-images.githubusercontent.com/33019286/31892511-dfa82428-b811-11e7-958b-c953f326d998.png)

**Comment by bretthoerner** [comment]
It seems like that machine is firewalled from the public internet. Your network administrator would have to allow it to reach out to `sentry.io`.

**Comment by arielesc** [comment]
So if i try with another network? it will be ok?

**Comment by bretthoerner** [comment]
So long as the network isn't configured to block access out to the public internet (or at least to `sentry.io`) it should work.

For example, if you can reach https://sentry.io/ from your browser then you should be able to run it from your local machine. If you can't reach it... you'll need an admin to allow access outside of your network.

**Comment by bretthoerner** [comment]
I don't see any problems with your code so when the network issue is fixed it should work fine.

**Comment by arielesc** [comment]
ok i will try now with another network, however i can reach to  https://sentry.io/  with that one, so its wird.

**Comment by bretthoerner** [comment]
Oh, that doesn't make any sense then.

I wonder if your JVM is somehow configured to disallow this? Maybe something to do with Java Security Policy? https://docs.oracle.com/cd/E19118-01/n1.sprovsys41/817-4820/6mkaodgb5/index.html

I'd ask someone you work with about what kind of security setup they have for Java?

**Comment by arielesc** [comment]
ok, now i have no more error message, and i can ping sentry.io on my machine, but now what? i still dont see nothing on my project in my website.

**Comment by arielesc** [comment]
![image](https://user-images.githubusercontent.com/33019286/31893244-bcad4802-b813-11e7-999d-b687e52eee04.png)

**Comment by arielesc** [comment]
and that is my commends, no error:
![image](https://user-images.githubusercontent.com/33019286/31893374-0ecd0da2-b814-11e7-8504-f36a2968565a.png)

**Comment by bretthoerner** [comment]
Can you change your code to print something beforehand to ensure that path is actually running?

**Comment by arielesc** [comment]
you mean print something before making an error?

**Comment by bretthoerner** [comment]
Oh, I see Sentry now. I wonder why Sentry is logging twice there. And you're sure the DSN is correct? Can you go to Sentry and copy paste it again to be sure?

**Comment by arielesc** [comment]
yes i already did it, and still nothing.

**Comment by bretthoerner** [comment]
Can you add `?async=false` to the DSN? And add a print after `Sentry.capture(e);`? I'm curious if it is hanging trying to communicate still.

**Comment by arielesc** [comment]
ok, i think it is working now, i found the event on Sentry:
![image](https://user-images.githubusercontent.com/33019286/31894294-ad5837c4-b816-11e7-9dc2-3564884fd9a6.png)

**Comment by bretthoerner** [comment]
Great! What was the issue?

**Comment by arielesc** [comment]
The main problem was the network you told me, then i just didn check on the right place in the Sentry, but now i think that is all ok! you save my day! thanks a lot!.

**Comment by bretthoerner** [comment]
Anytime, good luck.

**Comment by ckrgithub** [comment]
@arielesc Hi! I have a similar problem. my log:
`
2022-06-16 18:08:35.858 Sentry: Envelope submission failed
    java.lang.IllegalStateException: Sending the event failed.
        at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.flush(AsyncHttpTransport.java:274)
        at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.run(AsyncHttpTransport.java:197)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
     Caused by: java.net.ConnectException: Failed to connect to /127.0.0.1:9000
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:147)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
        at io.sentry.transport.HttpConnection.createConnection(HttpConnection.java:145)
        at io.sentry.transport.HttpConnection.send(HttpConnection.java:150)
        at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.flush(AsyncHttpTransport.java:236)
        at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.run(AsyncHttpTransport.java:197) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:920) `
How do you  deal with it ?
