### ISSUE TITLE
ConnectionException?

### ISSUE THREAD

**Issue by postace** [getsentry/sentry-java#535]
My company account has exhausted this month's event capacity. So in the logger, it shows a lot of error message like this:

```
2017-11-14 16:10:30,150 WARN An exception due to the connection occurred, a lockdown will be initiated.
com.getsentry.raven.connection.ConnectionException: {"error_name":"rate_limit","error":"Creation of this event was denied due to rate limiting"}
	at com.getsentry.raven.connection.HttpConnection.doSend(HttpConnection.java:132)
	at com.getsentry.raven.connection.AbstractConnection.send(AbstractConnection.java:78)
	at com.getsentry.raven.connection.AsyncConnection$EventSubmitter.run(AsyncConnection.java:144)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Server returned HTTP response code: 429 for URL: https://sentry.io/api/216321/store/
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at com.getsentry.raven.connection.HttpConnection.doSend(HttpConnection.java:124)
	... 5 common frames omitted

```

How can I get rid of these?

**Comment by bretthoerner** [comment]
These are greatly reduces in newer versions of the Java SDK, because it respects the `Retry-After` header that is returned. Upgrade guide is here: https://docs.sentry.io/clients/java/migration/

If you don't want to see these ever, you can disable the entire `HttpConnection` logger in whichever slf4j logger backend you use. There isn't a way to just disable that one error currently. (I think the `Retry-After` logic helped most people)

**Comment by postace** [comment]
Thank for your comment. I'll try and feedback as soon as possible

**Comment by postace** [comment]
Voila, upgrade sentry succeed. Thank @bretthoerner for your amazing support!
