### ISSUE TITLE
Can't find resource when using Sentry JAR on Android

### ISSUE THREAD

**Issue by davkutalek** [getsentry/sentry-java#537]
I am building an Android Library which depends on Sentry. For my debug build I downloaded the JAR files for Sentry and Sentry Android (plus slf4j and jackson-core) and include them in my build so that I don't have to put transitive dependencies in my apps. This was working fine until I upgraded to Android Studio 3.0, now I get the following runtime exception when calling `Sentry.init()`:

```
java.lang.ExceptionInInitializerError
      at io.sentry.connection.AbstractConnection.<init>(AbstractConnection.java:44)
      at io.sentry.connection.HttpConnection.<init>(HttpConnection.java:86)
      at io.sentry.DefaultSentryClientFactory.createHttpConnection(DefaultSentryClientFactory.java:419)
      at io.sentry.DefaultSentryClientFactory.createConnection(DefaultSentryClientFactory.java:322)
      at io.sentry.DefaultSentryClientFactory.createSentryClient(DefaultSentryClientFactory.java:235)
      at io.sentry.android.AndroidSentryClientFactory.createSentryClient(AndroidSentryClientFactory.java:75)
      at io.sentry.SentryClientFactory.sentryClient(SentryClientFactory.java:64)
      at io.sentry.Sentry.init(Sentry.java:81)
      at com.hover.sdk.utils.Utils.addSentry(Utils.java:148)
      at com.hover.sdk.onboarding.HoverIntegrationActivity.onCreate(HoverIntegrationActivity.java:58)
      at android.app.Activity.performCreate(Activity.java:6251)
      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2370)
      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2477)
      at android.app.ActivityThread.-wrap11(ActivityThread.java)
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1345)
      at android.os.Handler.dispatchMessage(Handler.java:102)
      at android.os.Looper.loop(Looper.java:148)
      at android.app.ActivityThread.main(ActivityThread.java:5452)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:762)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
Caused by: java.util.MissingResourceException: Can't find resource for bundle 'sentry-build_en_US', key ''
      at java.util.ResourceBundle.missingResourceException(ResourceBundle.java:238)
      at java.util.ResourceBundle.getBundle(ResourceBundle.java:230)
      at java.util.ResourceBundle.getBundle(ResourceBundle.java:139)
      at io.sentry.environment.SentryEnvironment.<clinit>(SentryEnvironment.java:23)
      at io.sentry.connection.AbstractConnection.<init>(AbstractConnection.java:44) 
      at io.sentry.connection.HttpConnection.<init>(HttpConnection.java:86) 
      at io.sentry.DefaultSentryClientFactory.createHttpConnection(DefaultSentryClientFactory.java:419) 
      at io.sentry.DefaultSentryClientFactory.createConnection(DefaultSentryClientFactory.java:322) 
      at io.sentry.DefaultSentryClientFactory.createSentryClient(DefaultSentryClientFactory.java:235) 
      at io.sentry.android.AndroidSentryClientFactory.createSentryClient(AndroidSentryClientFactory.java:75) 
      at io.sentry.SentryClientFactory.sentryClient(SentryClientFactory.java:64) 
      at io.sentry.Sentry.init(Sentry.java:81) 
      at com.hover.sdk.utils.Utils.addSentry(Utils.java:148) 
      at com.hover.sdk.onboarding.HoverIntegrationActivity.onCreate(HoverIntegrationActivity.java:58) 
      at android.app.Activity.performCreate(Activity.java:6251) 
      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110) 
      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2370) 
      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2477) 
      at android.app.ActivityThread.-wrap11(ActivityThread.java) 
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1345) 
      at android.os.Handler.dispatchMessage(Handler.java:102) 
      at android.os.Looper.loop(Looper.java:148) 
      at android.app.ActivityThread.main(ActivityThread.java:5452) 
      at java.lang.reflect.Method.invoke(Native Method) 
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:762) 
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652) 
 
```

This happens with Sentry 1.3.0 and 1.6.3.

**Comment by bretthoerner** [comment]
Weird, including `sentry-android` "normally" definitely works in Android Studio 3. I'm not sure off the top of my head why using the jars manually would cause an issue here: https://github.com/getsentry/sentry-java/blob/b548f1849dc297a45efe4c5777b515cf01356488/sentry/src/main/java/io/sentry/environment/SentryEnvironment.java#L23

**Comment by davkutalek** [comment]
Yeah, my release version uses Sentry from Maven with no issues

**Comment by bretthoerner** [comment]
Can you run this on the `sentry.jar` you're including manually?

`jar tf sentry.jar | grep sentry-build.properties`

**Comment by davkutalek** [comment]
It is found in the sentry.jar, but not in the final artifact (which is an aar). It is unclear to me if jar tf is supposed to work on an aar

**Comment by bretthoerner** [comment]
Hmm, I'd rather not catch this and not know the library version. I'm not finding any help with respect to AARs and jar resources though...

**Comment by marandaneto** [comment]
@davkutalek hey, did you manage to get it working? `AAR` works like maven dependencies, so it requires the `transitive` dependencies to work.

if you want a fat `AAR`, you could place sentry-android and all its transitive dependencies into `libs` folder.

**Comment by davkutalek** [comment]
The fat aar using the libs folder is what I was doing until that android studio/gradle update broke it. I haven't looked at this in a long time, it is possible it is working again. We ended up just setting debug dependencies in our apps manually. It is not ideal, but it isn't a huge problem.

**Comment by marandaneto** [comment]
I see, yeah, it is a pretty old issue, I'm tracking all issues Android related because we have a new Android SDK (Beta still) and we are likely to deprecate this one when we get to a stable version.

**Comment by davkutalek** [comment]
Awesome, will definitely try it out. Does it require the sentry-ndk dependency? Size is really important to us and it looks like new SDK compares favorably, especially since it uses GSON, but the NDK part is huge.

**Comment by marandaneto** [comment]
@davkutalek no, it's not required, you can depend on `sentry-android-core` and it's NDK free :)
You may have a look at https://docs.sentry.io/platforms/android/#advanced-usage

**Comment by marandaneto** [comment]
@davkutalek closing this issue, if you see that is still happening, let us know :)
