### ISSUE TITLE
Invalid Tag in properties kills results in NPE on Sentry.getContext()

### ISSUE THREAD

**Issue by dmclain** [getsentry/sentry-java#553]
Our deploy automation resulted in a lightly deformed tags value in our properties file

```
java.lang.IllegalArgumentException: Invalid tags entry: kube_app:
at io.sentry.util.Util.parseCsv(Util.java:39)
at io.sentry.util.Util.parseTags(Util.java:53)
at io.sentry.DefaultSentryClientFactory.getTags(DefaultSentryClientFactory.java:761)
at io.sentry.DefaultSentryClientFactory.configureSentryClient(DefaultSentryClientFactory.java:278)
at io.sentry.DefaultSentryClientFactory.createSentryClient(DefaultSentryClientFactory.java:247)
at io.sentry.SentryClientFactory.sentryClient(SentryClientFactory.java:64)
at io.sentry.Sentry.init(Sentry.java:81)
at io.sentry.Sentry.init(Sentry.java:44)
at io.sentry.Sentry.getStoredClient(Sentry.java:102)
at io.sentry.servlet.SentryServletRequestListener.requestDestroyed(SentryServletRequestListener.java:32)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1141)
```

Because the sentryClient failed to configure, our code to set the user via `Sentry.getContext().setUser(userBuilder.build());` exploded with a NullPointerException on every request.

**Comment by bretthoerner** [comment]
So first, I guess this specific issue could be fixed by going with a blank string for the tag value, or something?

The larger problem is a doozy, though. There are two main options here:

1. No matter what, if an error occurs in `Sentry.init` we always return/install a client that won't blow up and will noop or miss some of the user's attempted configuration. Users will either get no or partial data and eventually be sad/mad.
2. (current) We let things blow up as they do in an attempt to be noisy early and often so the user sees/fixes the configuration. Users are immediately sad/mad and fix their config.

It's tough since we're almost always initialized async from startup (e.g. first web request in this example).

**Comment by dmclain** [comment]
Letting things blow up during init seems fine to me, but when the docs encourage using `Sentry.getContext()` in the course of normal usage for breadcrumbs/user information, it means failing to initialize Sentry can cause the entire application to fail. A no-op client would be worse than a partially configured client, but it's a ton better than `null`

If the init method logged the same `IllegalArgumentException: Invalid tags` stacktrace, then as a Sentry user I'm frustrated for myself for making typos, but I'm way less mad than when instrumentation causes requests to fail when they would have otherwise succeeded.

**Comment by bretthoerner** [comment]
🤔 When you're right, you're right.
