### ISSUE TITLE
Invalid DSN, the following properties aren't set '[secret key]'

### ISSUE THREAD

**Issue by egel** [getsentry/sentry-java#568]
I come across of getting this issue while integrating my Android app (see error below).

I also find that almost identical question which has been already solved by the client for react native: https://github.com/getsentry/react-native-sentry/issues/224

> Additionally: Is there any good reason why we should set the `secret key` in the full "DSN" URL and not use "DSN (Public)"?

```
03-20 13:07:38.014 2043-2043/de.example.project E/AndroidRuntime: FATAL EXCEPTION: main
                                                              Process: de.example.project, PID: 2043
                                                              java.lang.RuntimeException: Unable to start activity ComponentInfo{de.example.project/de.example.project.MainActivity}: io.sentry.dsn.InvalidDsnException: Invalid DSN, the following properties aren't set '[secret key]'
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
                                                                  at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                  at android.os.Looper.loop(Looper.java:164)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                                                               Caused by: io.sentry.dsn.InvalidDsnException: Invalid DSN, the following properties aren't set '[secret key]'
                                                                  at io.sentry.dsn.Dsn.validate(Dsn.java:212)
                                                                  at io.sentry.dsn.Dsn.<init>(Dsn.java:66)
                                                                  at io.sentry.dsn.Dsn.<init>(Dsn.java:41)
                                                                  at io.sentry.SentryClientFactory.resolveDsn(SentryClientFactory.java:73)
                                                                  at io.sentry.SentryClientFactory.sentryClient(SentryClientFactory.java:42)
                                                                  at io.sentry.Sentry.init(Sentry.java:81)
                                                                  at de.example.project.MainActivity.onCreate(MainActivity.java:65)
                                                                  at android.app.Activity.performCreate(Activity.java:7009)
                                                                  at android.app.Activity.performCreate(Activity.java:7000)
                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
                                                                  at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
                                                                  at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                  at android.os.Looper.loop(Looper.java:164) 
                                                                  at android.app.ActivityThread.main(ActivityThread.java:6494) 
                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 

```

**Comment by bretthoerner** [comment]
Hey @egel, you should just use the normal DSN from your project settings page, not the public one. There isn't anything private about the DSN, it doesn't grant the user access to anything other than the ability to write events (which they need).
