### ISSUE TITLE
Sentry-java and Wildfly not working

### ISSUE THREAD

**Issue by rikatz** [getsentry/sentry-java#570]
I'm trying to use the log4j appender directly with Wildfly logging subsystem. 

I've configured Wildfly as the following:

* Install modules sentry-log4j-1.7.2.jar in modules/system/layers/base/io/sentry/log4j/main/.
   * Created the 'module.xml' as the following:

```
<module xmlns="urn:jboss:module:1.1" name="io.sentry.log4j">
    <resources>
        <resource-root path="sentry-log4j-1.7.2.jar"/>
    </resources>
    <dependencies>
        <module name="org.apache.log4j" />
        <module name="org.slf4j" />
        <module name="javax.api" />
        <module name="org.jboss.logmanager" />
        <module name="io.sentry" />
    </dependencies>
</module>
```

* Install modules sentry-1.7.2.jar in modules/system/layers/base/io/sentry/main/.
   * Created the 'module.xml' as the following:
```
<module xmlns="urn:jboss:module:1.1" name="io.sentry">
    <resources>
        <resource-root path="sentry-1.7.2.jar"/>
    </resources>
    <dependencies>
        <module name="org.apache.log4j" />
        <module name="org.slf4j" />
        <module name="javax.api" />
        <module name="org.jboss.logmanager" />
    </dependencies>
</module>
```

* Configured standalone.xml as the following:

```
          <custom-handler name="SENTRY" class="io.sentry.log4j.SentryAppender" module="io.sentry.log4j">
                <level name="INFO"/>
                <formatter>
                    <named-formatter name="PATTERN"/>
                </formatter>
            </custom-handler>
[...]
            <root-logger>
                <level name="INFO"/>
                <handlers>
                    <handler name="CONSOLE"/>
                    <handler name="FILE"/>
                    <handler name="SENTRY"/>
                </handlers>
            </root-logger>

```

When starting Jboss with the DSN configured, the following NullPointer happens:

```
$ SENTRY_DSN="http://xxxxx@sentry.lab//2" ./bin/standalone.sh 
=========================================================================

  JBoss Bootstrap Environment

  JBOSS_HOME: /wildfly/wildfly-10.1.0.Final

  JAVA: java

  JAVA_OPTS:  -server -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true

=========================================================================

17:43:39,921 INFO  [org.jboss.modules] (main) JBoss Modules version 1.5.2.Final
17:43:40,120 ERROR [stderr] (main) log4j:ERROR An exception occurred while creating a new event in Sentry
17:43:40,120 ERROR [stderr] (main) java.lang.NullPointerException
17:43:40,121 ERROR [stderr] (main) 	at io.sentry.log4j.SentryAppender.createEventBuilder(SentryAppender.java:131)
17:43:40,121 ERROR [stderr] (main) 	at io.sentry.log4j.SentryAppender.append(SentryAppender.java:84)
17:43:40,121 ERROR [stderr] (main) 	at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
17:43:40,122 ERROR [stderr] (main) 	at org.jboss.as.logging.logmanager.Log4jAppenderHandler.doPublish(Log4jAppenderHandler.java:144)
17:43:40,122 ERROR [stderr] (main) 	at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:76)
17:43:40,122 ERROR [stderr] (main) 	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:314)
17:43:40,122 ERROR [stderr] (main) 	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:322)
17:43:40,123 ERROR [stderr] (main) 	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:322)
17:43:40,123 ERROR [stderr] (main) 	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:322)
17:43:40,123 ERROR [stderr] (main) 	at org.jboss.logmanager.Logger.logRaw(Logger.java:850)
17:43:40,123 ERROR [stderr] (main) 	at org.jboss.logmanager.Logger.log(Logger.java:802)
17:43:40,124 ERROR [stderr] (main) 	at org.jboss.logging.JBossLogManagerLogger.doLogf(JBossLogManagerLogger.java:53)
17:43:40,124 ERROR [stderr] (main) 	at org.jboss.logging.Logger.logf(Logger.java:2398)
17:43:40,124 ERROR [stderr] (main) 	at org.jboss.msc.service.ServiceLogger_$logger.greeting(ServiceLogger_$logger.java:65)
17:43:40,124 ERROR [stderr] (main) 	at org.jboss.msc.service.ServiceContainerImpl.<clinit>(ServiceContainerImpl.java:93)
17:43:40,125 ERROR [stderr] (main) 	at org.jboss.msc.service.ServiceContainer$Factory.create(ServiceContainer.java:258)
17:43:40,125 ERROR [stderr] (main) 	at org.jboss.as.server.BootstrapImpl$ShutdownHook.register(BootstrapImpl.java:214)
17:43:40,125 ERROR [stderr] (main) 	at org.jboss.as.server.BootstrapImpl$ShutdownHook.access$100(BootstrapImpl.java:204)
17:43:40,125 ERROR [stderr] (main) 	at org.jboss.as.server.BootstrapImpl.<init>(BootstrapImpl.java:63)
17:43:40,125 ERROR [stderr] (main) 	at org.jboss.as.server.Bootstrap$Factory.newInstance(Bootstrap.java:262)
17:43:40,126 ERROR [stderr] (main) 	at org.jboss.as.server.Main.main(Main.java:100)
17:43:40,126 ERROR [stderr] (main) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
17:43:40,126 ERROR [stderr] (main) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
17:43:40,126 ERROR [stderr] (main) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
17:43:40,127 ERROR [stderr] (main) 	at java.lang.reflect.Method.invoke(Method.java:498)
17:43:40,127 ERROR [stderr] (main) 	at org.jboss.modules.Module.run(Module.java:330)
17:43:40,127 ERROR [stderr] (main) 	at org.jboss.modules.Main.main(Main.java:505)
```

Thanks!

**Comment by bretthoerner** [comment]
Hey, I had someone write in about Wildfly issues recently,

"I found that the Sentry module stopped loading because it was not able to find a module for the javax.net.ssl.HostnameVerifier dependency, so I simply downloaded the jar for this and added it to my module resources and now it works."

https://github.com/fallard84/sentry-jboss-module

So I think the issue is the missing dependency(/ies) is causing Sentry to not initialize properly. You will also need `com.fasterxml.jackson.core:jackson-core` and `org.slf4j:slf4j-api` if you don't have them already.

**Comment by rikatz** [comment]
Nice @bretthoerner, will try here! Thanks!

**Comment by rikatz** [comment]
It worked here, the problem was the missing libraries.

I'll make better docs here for my environment!!

Thanks
