### ISSUE TITLE
Sentry-Android java.util.zip.ZipException: File too short to be a zip file: 0

### ISSUE THREAD

**Issue by mpp-doric** [getsentry/sentry-java#578]
Hi, 

We have observed the below failure when Sentry buffering is attempted.

```
4-16 16:18:11.595 15649-15649/? D/io.sentry.android.AndroidSentryClientFactory: Sentry init with ctx='com.<removed>@da43380' and dsn='Dsn{uri=https://sentry.io/}' 
04-16 16:18:11.598 15649-15649/? E/System: Unable to open zip file: /data/user/0/com.<removed>/dataout/site.raw.zip 
04-16 16:18:11.599 15649-15649/? E/System: java.util.zip.ZipException: File too short to be a zip file: 0 
        at java.util.zip.ZipFile.<init>(ZipFile.java:208) 
        at java.util.zip.ZipFile.<init>(ZipFile.java:147) 
        at java.util.jar.JarFile.<init>(JarFile.java:161) 
        at java.util.jar.JarFile.<init>(JarFile.java:98) 
        at libcore.io.ClassPathURLStreamHandler.<init>(ClassPathURLStreamHandler.java:47)
        at dalvik.system.DexPathList$Element.maybeInit(DexPathList.java:530) 
        at dalvik.system.DexPathList$Element.findResource(DexPathList.java:566) 
        at dalvik.system.DexPathList.findResource(DexPathList.java:438) 
        at dalvik.system.BaseDexClassLoader.findResource(BaseDexClassLoader.java:74)
        at java.lang.ClassLoader.getResource(ClassLoader.java:793) 
        at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:977) 
        at io.sentry.config.Lookup.getInputStream(Unknown Source) 
        at io.sentry.config.Lookup.<clinit>(Unknown Source) 
        at io.sentry.config.Lookup.lookup(Unknown Source) 
        at io.sentry.DefaultSentryClientFactory.getProxyHost(Unknown Source) 
        at io.sentry.DefaultSentryClientFactory.createHttpConnection(Unknown Source) 
        at io.sentry.DefaultSentryClientFactory.createConnection(Unknown Source) 
        at io.sentry.DefaultSentryClientFactory.createSentryClient(Unknown Source) 
        at io.sentry.android.AndroidSentryClientFactory.createSentryClient(Unknown Source) 
        at io.sentry.SentryClientFactory.sentryClient(Unknown Source) 
        at io.sentry.Sentry.init(Unknown Source) 
        at llllll.ooooho.bннн043Dн043D043D(Unknown Source) 
        at llllll.ooooho.b043Dнн043Dн043D043D(Unknown Source) 
        at com.<removed>.onCreate(Unknown Source) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5970)
        at android.app.ActivityThread.-wrap3(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1710) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6776) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408) 
04-16 16:18:11.645 15649-15649/? D/io.sentry.android.AndroidSentryClientFactory: Using buffer dir: /data/user/0/com.<removed>/cache/sentry-buffered-events
```

**Comment by bretthoerner** [comment]
Hmm, that doesn't seem like buffering. That's just creating the Sentry client, and the `Lookup` class should be doing a `getInputStream` on the `sentry.properties` file.

https://github.com/getsentry/sentry-java/blob/f3d66780871d95aa54b6d3c0bd1f992e9f25f144/sentry/src/main/java/io/sentry/config/Lookup.java#L37

https://github.com/getsentry/sentry-java/blob/f3d66780871d95aa54b6d3c0bd1f992e9f25f144/sentry/src/main/java/io/sentry/config/Lookup.java#L57-L69

Very odd, I haven't seen this before. Is Android's `DexPathList` crawling every zip-like file seeing if it's a JAR? Is your `site.raw.zip` a valid zip (or jar)?

**Comment by bretthoerner** [comment]
Is there any way you could try it without that zip on the classpath?

**Comment by doridori** [comment]
Thanks for the prompt reply - yes it looks like thats what its doing re crawling. The `site.raw` file is apk asset which is output from an obfuscation tool we are using. In the apk is it not a `.zip` however, just a `.raw`

**Comment by doridori** [comment]
I have tried it previously without that file present and all seems to work as expected.

**Comment by bretthoerner** [comment]
Interesting. Well this isn't Sentry code doing the crawling, it seems like Android really doesn't expect `.zip` extension files on the classpath to not be real zips?

I guess we can try to capture this, but it won't help if you ever try to use `sentry.properties` for configuration, since this exception might be thrown before the file is found.

Is it possible to include the file (assuming you need it) but with a different extension, like `.raw`?

**Comment by mpp-doric** [comment]
Hey, well, it _does_ have a `raw` extension, but the tool-injected code may create this zip as part of working with the file when the application starts, at which point this issue likely becomes a race-condition.

I will chase this up with the tool authors and ask why the create a fake zip. They do a lot of shoddy things IMO.

Thanks for the (speedy) help :)

BTW we dont use a sentry properties file at present, but may do when we finish the Sentry config in the near future.

**Comment by bretthoerner** [comment]
Cool, let me know. It does look like we just capture and log this: https://github.com/getsentry/sentry-java/blob/f3d66780871d95aa54b6d3c0bd1f992e9f25f144/sentry/src/main/java/io/sentry/config/Lookup.java#L45-L47

So it shouldn't prevent Sentry from working or effect the application in production. Have you noticed otherwise?

**Comment by mpp-doric** [comment]
Thats fantastic thanks - you answered the question I was just about to type.

We have had reports of crashing, but I am guessing that the developer who reported this to me has copied out the insignificant part of the log output. 

Thanks again
