### ISSUE TITLE
Two different projects were specified

### ISSUE THREAD

**Issue by liuqu11** [getsentry/sentry-java#587]
Hey Brett, There has been a lot of failed information now.

`2018-05-24  11:58:18[ERROR][sentry-pool-1-thread-1]-An exception occurred while sending the event to Sentry.
io.sentry.connection.ConnectionException: {"error":"Two different projects were specified"}
        at io.sentry.connection.HttpConnection.doSend(HttpConnection.java:216) ~[sentry-1.7.2.jar:na]
        at io.sentry.connection.AbstractConnection.send(AbstractConnection.java:75) ~[sentry-1.7.2.jar:na]
        at io.sentry.connection.AsyncConnection$EventSubmitter.run(AsyncConnection.java:185) ~[sentry-1.7.2.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_71]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_71]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: http://172.26.1.111:8888/api/41/store/
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1626) ~[na:1.7.0_71]
        at io.sentry.connection.HttpConnection.doSend(HttpConnection.java:172) ~[sentry-1.7.2.jar:na]
        ... 5 common frames omitted
|90822GM2YgUnZIIWbCdF4OE561m74NU9|--2018-05-24  11:58:18[ERROR][sentry-pool-1-thread-3]-An exception occurred while sending the event to Sentry.
io.sentry.connection.ConnectionException: {"error":"Two different projects were specified"}
        at io.sentry.connection.HttpConnection.doSend(HttpConnection.java:216) ~[sentry-1.7.2.jar:na]
        at io.sentry.connection.AbstractConnection.send(AbstractConnection.java:75) ~[sentry-1.7.2.jar:na]
        at io.sentry.connection.AsyncConnection$EventSubmitter.run(AsyncConnection.java:185) ~[sentry-1.7.2.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_71]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_71]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: http://172.26.1.111:8888/api/41/store/
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1626) ~[na:1.7.0_71]
        at io.sentry.connection.HttpConnection.doSend(HttpConnection.java:172) ~[sentry-1.7.2.jar:na]
        ... 5 common frames omitted
`

**Comment by bretthoerner** [comment]
Did this start happening after an upgrade? What was the old version and what is the new version?

Where did you get the client DSN you are using? Can you go into the Sentry project settings and verify you are using the current client DSN? It sounds like something is incorrect there.

**Comment by liuqu11** [comment]
Ok，I find，My DSN error
Thank you very much
