### ISSUE TITLE
Possible issue with Sentry Java 1.3.0 preventing graceful shutdown

### ISSUE THREAD

**Issue by bradical** [getsentry/sentry-java#588]
I'm having an issue that I believe may be related to Sentry where I'm unable to shutdown Tomcat successfully using the start/stop commands below. But, interestingly, after the shutdown fails, I run a manual `kill <pid>` which immediately seems to end the process and sends the following to the log (which lead me to Sentry):

```
2018-05-24 13:51:16,944 INFO  [AsyncConnection] : Automatic shutdown of the async connection
2018-05-24 13:51:16,945 INFO  [AsyncConnection] : Gracefully shutdown sentry threads.
2018-05-24 13:51:16,945 INFO  [AsyncConnection] : Shutdown finished
```

Also interesting that the thread dump before I run `kill` doesn't seem to include anything related to Sentry and yet this AsyncConnection is still shutdown after I run `kill`.

Any ideas?

## Start/Stop

Start:
```
$ CATALINA_PID=/path/to/pid;path/to/tomcat/bin/startup.sh start
Using CATALINA_BASE:   /path/to/tomcat
Using CATALINA_HOME:   /path/to/tomcat
Using CATALINA_TMPDIR: /path/to/tomcat/temp
Using JRE_HOME:        /path/to/jdk1.8.0_121/jre
Using CLASSPATH:       /path/to/tomcat/bin/bootstrap.jar:/path/to/tomcat/bin/tomcat-juli.jar
Using CATALINA_PID:    /path/to/pid
Existing PID file found during start.
Removing/clearing stale PID file.
Tomcat started.
```

Stop:

```
$ CATALINA_PID=/path/to/pid; path/to/tomcat/shutdown.sh stop 45
Using CATALINA_BASE:   /path/to/tomcat
Using CATALINA_HOME:   /path/to/tomcat
Using CATALINA_TMPDIR: /path/to/tomcat/temp
Using JRE_HOME:        /path/to/jdk1.8.0_121/jre
Using CLASSPATH:       /path/to/tomcat/bin/bootstrap.jar:/path/to/tomcat/bin/tomcat-juli.jar
Using CATALINA_PID:    /path/to/pid
Tomcat did not stop in time.
PID file was not removed.
To aid diagnostics a thread dump has been written to standard out.
```

## Context

For context, I'm using:

- sentry-1.3.0.jar
- sentry-log4j-1.3.0.jar

and the following log4j init:

```
log4j.rootLogger=INFO, console, Sentry
log4j.appender.Sentry=io.sentry.log4j.SentryAppender
log4j.appender.Sentry.threshold=WARN
```

with additional properties:

```
Xms8g -Xmx8g -Djava.awt.headless=true -Dfile.encoding=UTF-8 -DgoogleTagManager.enabled=true -Daccessibility.url=https://tenon.io/api/ -Daccessibility.token=18c8cdaf730ba3085f4e949112b84ecf -Dsentry.dsn=<dsn_url> -Dsentry.servername=<server_name> -Dsentry.environment=development -Dsentry.factory=com.hannonhill.cascade.sentry.SentryClientFactory
```

And the custom SentryClientFactory is just:

```java
public class SentryClientFactory extends DefaultSentryClientFactory
{
    @Override
    public SentryClient createSentryClient(Dsn dsn) {
        SentryClient sentryClient = super.createSentryClient(dsn);

        sentryClient.setRelease(SystemVersions.APP_VERSION);
        sentryClient.addBuilderHelper(new CascadeThreadLocalBuilderHelper(sentryClient));

        return sentryClient;
    }
}
```

## Thread dump before `kill`

Here's the thread dump:

```
2018-05-24 13:48:58
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.121-b13 mixed mode):

"DestroyJavaVM" #84 prio=5 os_prio=0 tid=0x00007f09b05d9800 nid=0x1a8d waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Timer-1" #65 daemon prio=5 os_prio=0 tid=0x00007f09b14d7800 nid=0x1ad8 in Object.wait() [0x00007f097b4f3000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.util.TimerThread.mainLoop(Timer.java:552)
	- locked <0x00000007b58a0ea8> (a java.util.TaskQueue)
	at java.util.TimerThread.run(Timer.java:505)

"DefaultQuartzScheduler_QuartzSchedulerThread" #64 prio=5 os_prio=0 tid=0x00007f09b14d5800 nid=0x1ad7 in Object.wait() [0x00007f097b5f4000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:245)
	- locked <0x00000007b58a13c0> (a java.lang.Object)

"DefaultQuartzScheduler_Worker-10" #63 prio=5 os_prio=0 tid=0x00007f09b14d4000 nid=0x1ad6 in Object.wait() [0x00007f097b6f5000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:543)
	- locked <0x00000007b5736e38> (a org.quartz.simpl.SimpleThreadPool$WorkerThread)

"DefaultQuartzScheduler_Worker-9" #62 prio=5 os_prio=0 tid=0x00007f09b1a24800 nid=0x1ad5 in Object.wait() [0x00007f097b7f6000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:543)
	- locked <0x00000007b5736b68> (a org.quartz.simpl.SimpleThreadPool$WorkerThread)

"DefaultQuartzScheduler_Worker-8" #61 prio=5 os_prio=0 tid=0x00007f09b1a22800 nid=0x1ad4 in Object.wait() [0x00007f097b8f7000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:543)
	- locked <0x00000007b5736898> (a org.quartz.simpl.SimpleThreadPool$WorkerThread)

"DefaultQuartzScheduler_Worker-7" #60 prio=5 os_prio=0 tid=0x00007f09b1a20800 nid=0x1ad3 in Object.wait() [0x00007f097b9f8000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:543)
	- locked <0x00000007b57365c8> (a org.quartz.simpl.SimpleThreadPool$WorkerThread)

"DefaultQuartzScheduler_Worker-6" #59 prio=5 os_prio=0 tid=0x00007f09b1a1e800 nid=0x1ad2 in Object.wait() [0x00007f097baf9000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:543)
	- locked <0x00000007b57362f8> (a org.quartz.simpl.SimpleThreadPool$WorkerThread)

"DefaultQuartzScheduler_Worker-5" #58 prio=5 os_prio=0 tid=0x00007f09b1a1a800 nid=0x1ad1 in Object.wait() [0x00007f097bbfa000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:543)
	- locked <0x00000007b5736028> (a org.quartz.simpl.SimpleThreadPool$WorkerThread)

"DefaultQuartzScheduler_Worker-4" #57 prio=5 os_prio=0 tid=0x00007f09b1a18000 nid=0x1ad0 in Object.wait() [0x00007f097bcfb000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:543)
	- locked <0x00000007b5735d58> (a org.quartz.simpl.SimpleThreadPool$WorkerThread)

"DefaultQuartzScheduler_Worker-3" #56 prio=5 os_prio=0 tid=0x00007f09b1a17000 nid=0x1acf in Object.wait() [0x00007f097bdfc000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:543)
	- locked <0x00000007b5735460> (a org.quartz.simpl.SimpleThreadPool$WorkerThread)

"DefaultQuartzScheduler_Worker-2" #55 prio=5 os_prio=0 tid=0x00007f09b1a1c000 nid=0x1ace in Object.wait() [0x00007f097befd000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:543)
	- locked <0x00000007b5735a70> (a org.quartz.simpl.SimpleThreadPool$WorkerThread)

"DefaultQuartzScheduler_Worker-1" #54 prio=5 os_prio=0 tid=0x00007f09b01ed800 nid=0x1acd in Object.wait() [0x00007f097bffe000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:543)
	- locked <0x00000007b57357a0> (a org.quartz.simpl.SimpleThreadPool$WorkerThread)

"Abandoned connection cleanup thread" #27 daemon prio=5 os_prio=0 tid=0x00007f09b1d86800 nid=0x1ab1 in Object.wait() [0x00007f09835eb000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x00000005c1e179c8> (a java.lang.ref.ReferenceQueue$Lock)
	at com.mysql.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:41)

"Attach Listener" #20 daemon prio=9 os_prio=0 tid=0x00007f0948001000 nid=0x1aaa runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"GC Daemon" #14 daemon prio=2 os_prio=0 tid=0x00007f09b0459800 nid=0x1aa2 in Object.wait() [0x00007f0990e56000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000005c003f5a0> (a sun.misc.GC$LatencyLock)
	at sun.misc.GC$Daemon.run(GC.java:117)
	- locked <0x00000005c003f5a0> (a sun.misc.GC$LatencyLock)

"FileHandlerLogFilesCleaner-1" #13 daemon prio=5 os_prio=0 tid=0x00007f09b01fe800 nid=0x1aa1 waiting on condition [0x00007f0991819000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000005c0045c38> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

"AsyncFileHandlerWriter-1229416514" #12 daemon prio=5 os_prio=0 tid=0x00007f09b018b800 nid=0x1aa0 waiting on condition [0x00007f099191a000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000005c0037838> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.LinkedBlockingDeque.pollFirst(LinkedBlockingDeque.java:522)
	at java.util.concurrent.LinkedBlockingDeque.poll(LinkedBlockingDeque.java:684)
	at org.apache.juli.AsyncFileHandler$LoggerThread.run(AsyncFileHandler.java:160)

"Service Thread" #9 daemon prio=9 os_prio=0 tid=0x00007f09b00cb000 nid=0x1a9e runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread3" #8 daemon prio=9 os_prio=0 tid=0x00007f09b00c8000 nid=0x1a9d waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread2" #7 daemon prio=9 os_prio=0 tid=0x00007f09b00c6000 nid=0x1a9c waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #6 daemon prio=9 os_prio=0 tid=0x00007f09b00c4000 nid=0x1a9b waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=0 tid=0x00007f09b00c1000 nid=0x1a9a waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 tid=0x00007f09b00bf800 nid=0x1a99 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=0 tid=0x00007f09b008c800 nid=0x1a98 in Object.wait() [0x00007f0992122000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x00000005c00409b8> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" #2 daemon prio=10 os_prio=0 tid=0x00007f09b0088000 nid=0x1a97 in Object.wait() [0x00007f0992223000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	- locked <0x00000005c0045d38> (a java.lang.ref.Reference$Lock)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"VM Thread" os_prio=0 tid=0x00007f09b0080000 nid=0x1a96 runnable

"GC task thread#0 (ParallelGC)" os_prio=0 tid=0x00007f09b001f000 nid=0x1a8e runnable

"GC task thread#1 (ParallelGC)" os_prio=0 tid=0x00007f09b0020800 nid=0x1a8f runnable

"GC task thread#2 (ParallelGC)" os_prio=0 tid=0x00007f09b0022800 nid=0x1a90 runnable

"GC task thread#3 (ParallelGC)" os_prio=0 tid=0x00007f09b0024800 nid=0x1a91 runnable

"GC task thread#4 (ParallelGC)" os_prio=0 tid=0x00007f09b0026000 nid=0x1a92 runnable

"GC task thread#5 (ParallelGC)" os_prio=0 tid=0x00007f09b0028000 nid=0x1a93 runnable

"GC task thread#6 (ParallelGC)" os_prio=0 tid=0x00007f09b002a000 nid=0x1a94 runnable

"GC task thread#7 (ParallelGC)" os_prio=0 tid=0x00007f09b002b800 nid=0x1a95 runnable

"VM Periodic Task Thread" os_prio=0 tid=0x00007f09b00ce000 nid=0x1a9f waiting on condition

JNI global references: 431

Heap
 PSYoungGen      total 2616832K, used 378386K [0x0000000715580000, 0x00000007c0000000, 0x00000007c0000000)
  eden space 2435072K, 14% used [0x0000000715580000,0x000000072ad7e658,0x00000007a9f80000)
  from space 181760K, 14% used [0x00000007b4e80000,0x00000007b6806598,0x00000007c0000000)
  to   space 179200K, 0% used [0x00000007a9f80000,0x00000007a9f80000,0x00000007b4e80000)
 ParOldGen       total 5592576K, used 115132K [0x00000005c0000000, 0x0000000715580000, 0x0000000715580000)
  object space 5592576K, 2% used [0x00000005c0000000,0x00000005c706f1f8,0x0000000715580000)
 Metaspace       used 110356K, capacity 111396K, committed 111564K, reserved 1153024K
  class space    used 8677K, capacity 8951K, committed 8960K, reserved 1048576K
```

**Comment by bretthoerner** [comment]
Hey @bradical, my hunch is that this isn't Sentry related.

The `AsyncConnection` registers a JVM shutdown hook to ensure in-flight requests finish sending before exiting, but it seems like no requests were in-flight (they'd definitely show up in the threads).

To rule it out you could try `-Dsentry.async.gracefulshutdown=false` or even `-Dsentry.async=false` (which will send exceptions from the thread that does logging). I would only recommend trying these temporarily.

**Comment by bradical** [comment]
Happy to try that out. What do you make of the fact that that is the only logging that registers after I run a `kill`? Also, should I expect to see anything Sentry or AsyncConnection related in the Thread dump immediately before that? I was little surprised that I didn't.

**Comment by bretthoerner** [comment]
AsyncConnection uses a ThreadPoolExecutor and only has live threads when something is actually being sent, otherwise they are killed. So the lack of them in the trace should imply nothing was attempting to be sent.

As for why it's the only/last thing that logs, I feel like that may be luck just based on it being the only shutdown hook? Not sure there...

I'm curious if those options change anything.

I'm also curios what signal (or something else?) `path/to/tomcat/shutdown.sh` sends when you tell it to `stop`. Whatever it's doing isn't doing what `SIGTERM` is doing. On a hunch I would wonder about any non-daemon threads in the system? We set all Sentry threads to be daemon threads: https://github.com/getsentry/sentry-java/blob/bb5a31f9d9d4d21f40e4bd2002f0b5d4fa45b392/sentry/src/main/java/io/sentry/DefaultSentryClientFactory.java#L924

**Comment by bradical** [comment]
Adding `-Dsentry.async.gracefulshutdown=false` and `-Dsentry.async=false` didn't seem to have any effect. The process still didn't stop on `catalina.sh stop`. 

I'm not seeing the AsyncConnection logging anymore presumably because it was disabled with that param right?

`path/to/tomcat/shutdown.sh` comes from Tomcat's stop script: `catalina.sh`. Looks like it's:

```
        kill -0 `cat "$CATALINA_PID"` >/dev/null 2>&1
```

I will poke around for other threads. You would think I would see one that might be holding it up in the thread dump, no?

**Comment by bretthoerner** [comment]
Yeah, those options disable the hook so you won't see logging. A last ditch effort to prove it's not Sentry would be to disable to logger/integration entirely.

But yeah, if it's not stopping I would assume one of those threads in the dump you pasted it hanging the process. But I'm still curious what signal (or otherwise) a `stop` actually sends.

**Comment by bradical** [comment]
Script's coming from Tomcat. https://github.com/apache/tomcat/blob/cb28d39ea7d1e99aa5308b6383289197e7b53069/bin/catalina.sh#L503

**Comment by bretthoerner** [comment]
Interesting, I think that specific line is just to verify the PID exists. From `man killl`:

> If signal is 0, then no actual signal is sent, but error checking is still performed.

The others I see are `-3` (`SIGQUIT`) and `-15` (`SIGTERM`) which is the default for `kill`.

I think 3 is just being used to dump the stack. It... seems to me like it sends `SIGTERM` which is exactly what you send. It's almost like something is waiting for the second?

**Comment by maciejwalkowiak** [comment]
This issue should not happen in new Java SDK v3. Closing for now, please comment if it's still causing troubles.
