### ISSUE TITLE
Crashes on instantiation when running on API Level 19 / Samsung SM-T230NU

### ISSUE THREAD

**Issue by dlo** [getsentry/sentry-java#599]
When I run the Sentry.init function, the following crash occurs on application launch. For now, I have to disable the Sentry logger on these devices.

```
08-24 05:05:40.264 13539-13539/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ticketbud.ticketbud, PID: 13539
    java.lang.NoClassDefFoundError: org.slf4j.helpers.SubstituteLoggerFactory
        at org.slf4j.LoggerFactory.<clinit>(LoggerFactory.java:86)
        at io.sentry.Sentry.<clinit>(Sentry.java:18)
        at com.ticketbud.scanner.eventmanager.App.onCreate(App.kt:14)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4730)
        at android.app.ActivityThread.access$1600(ActivityThread.java:175)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:146)
        at android.app.ActivityThread.main(ActivityThread.java:5602)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
        at dalvik.system.NativeStart.main(Native Method)
```

Happy to send over any other info.

**Comment by bretthoerner** [comment]
Interesting, what version of slf4j is being used in the project?

**Comment by SPGB** [comment]
I had a similar error (Failed to load class org.slf4j.impl.StaticLoggerBinder). Resolved by adding:
`implementation 'org.slf4j:slf4j-nop:1.7.25'`
to my build.gradle. Maybe this should be an upstream dependency since otherwise SentryUncaughtExceptionHandler crashes for me.
