### ISSUE TITLE
Run error throw io.sentry.connection.ConnectionException in java 11

### ISSUE THREAD

**Issue by EarnestLee** [getsentry/sentry-java#616]
io.sentry.connection.ConnectionException: An exception occurred while submitting the event to the Sentry server.
	at io.sentry.connection.HttpConnection.doSend(HttpConnection.java:216) ~[sentry-1.7.10.jar!/:na]
	at io.sentry.connection.AbstractConnection.send(AbstractConnection.java:76) ~[sentry-1.7.10.jar!/:na]
	at io.sentry.connection.AsyncConnection$EventSubmitter.run(AsyncConnection.java:185) ~[sentry-1.7.10.jar!/:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) ~[na:na]
	at java.base/java.net.Socket.connect(Socket.java:591) ~[na:na]
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474) ~[na:na]
	at java.base/sun.net.www.http.HttpClient$1.run(HttpClient.java:526) ~[na:na]
	at java.base/sun.net.www.http.HttpClient$1.run(HttpClient.java:524) ~[na:na]
	at java.base/java.security.AccessController.doPrivileged(Native Method) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.privilegedOpenServer(HttpClient.java:523) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:564) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1242) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1181) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1075) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1009) ~[na:na]
	at io.sentry.connection.HttpConnection.doSend(HttpConnection.java:168) ~[sentry-1.7.10.jar!/:na]
	... 5 common frames omitted

**Comment by bretthoerner** [comment]
* Are you using `sentry.io` or self hosted?
* Was anything else logged?
* Could you enable DEBUG logging and post any `io.sentry.*` logs?
* Can you provide any more context?

**Comment by EarnestLee** [comment]
ok,i will provide to you later
