### ISSUE TITLE
Java Agent Feedback

### ISSUE THREAD

**Issue by bretthoerner** [getsentry/sentry-java#617]
I'd like to collect any production experience / feedback about the experimental Java agent here.

**Comment by erikvanzijst** [comment]
Have the shared objects been published to maven, or do I manually need to bundle the .so's in my application?

**Comment by bretthoerner** [comment]
They haven't been published, is that actually possible? I thought the JVM needed to be launched with the agent available from startup. I'm not sure I can activate/use an agent from the classpath.

**Comment by erikvanzijst** [comment]
I've never done it (my JNI experience predates maven), but can't you bundle the so's inside the jar? The jars might become architecture-dependent, but this post seems to suggest that approach: https://stackoverflow.com/a/10096522

**Comment by bretthoerner** [comment]
The agent isn't a JNI library, it uses the JVM-TI which requires it be loaded when the JVM is bootstrapping: https://docs.oracle.com/javase/8/docs/platform/jvmti/jvmti.html

This is, sadly, the only way I know of to get at arbitrary local variables on the stack.

**Comment by erikvanzijst** [comment]
> The agent isn't a JNI library, it uses the JVM-TI

Ah, TIL.

**Comment by bretthoerner** [comment]
The root works fine, and it's worth noting that can be provided in a number of ways (if it helps):

https://docs.sentry.io/clients/java/config/#id2
https://docs.sentry.io/clients/java/config/#in-application-stack-frames

So you can provide it in a `sentry.properties` file on your CLASSPATH, or in the DSN, or however you prefer.

I also need to update the docs that Sentry needs to be initialized for the agent to work. So you need to call `Sentry.init();` at the start of your app, or else it will be lazily initialized on your first error (which won't include local variables) and then following errors *will* have locals. That's a rough edge for now I need to improve.

**Comment by bretthoerner** [comment]
Interesting, thanks for that bit, I didn't realize there was an extra dep on some distros.

**Comment by gionn** [comment]
Hi, I am trying with sentry-logback v1.7.12 on a large spring application running under docker openjdk:8u171-jre-alpine image  that normally takes 30 seconds for startup, with the agent is taking 10x more time and I don't see any context added to the stacktraces.

Any hints? Thanks.

**Comment by bretthoerner** [comment]
Hey @gionn, we have some known performance issues with the agent that we need to work out. #624 is one piece of that but we have more work to do around caching class references and only running the agent code after a Sentry client has been initialized. I'll bump this thread when we've made some progress. Thanks for trying the agent out!

**Comment by cocorossello** [comment]
Hi,

I'm trying to setup the agent in jdk 11 and tomcat, avoiding endorsed, also with sentry-logback. Is there any way to run the agent without the endorsed mechanism? It now throws a no class found error:

Event: 26.045 Thread 0x000002889307f800 Exception <a 'java/lang/NoClassDefFoundError'{0x00000000a97a15f8}: io/sentry/jvmti/FrameCache> (0x00000000a97a15f8) thrown at [t:/workspace/open/src/hotspot/share/classfile/systemDictionary.cpp, line 229]

I suppose it will work moving the sentry dependencies to an endorsed folder, but I would like to avoid that, because it gets messy (I would have to move sentry, slf4j, logback, jackson -because its used by an appender- and even servlet api because it's used by logback-classic.

**Comment by bretthoerner** [comment]
@cocorossello To be honest this hasn't come up before and I'm not sure. Have you tried with it all endorsed to verify that was the issue? My guess is agent tie-ins are going to require it...

That said, as noted above, we have some serious performance issues to address before it will probably be useful in a full blown Tomcat app. Hope to get time to work on this after some other projects.

**Comment by cocorossello** [comment]
I'll try again later then. Thanks!

**Comment by youness-teimoury** [comment]
Hi!
My application is on Java/Tomcat/Mac.
I followed the notes in https://github.com/getsentry/sentry-java/tree/master/agent to compile the agent on my Mac and use that. 
Then I set the agent as -agentpath:/tmp/libsentry_agent.dylib in my JVM parameters but I cannot see any object state attached to my exceptions.
I can see my logs in Sentry dashboard but they are not associated with object status.
I would appreciate of you could shed some light on that.

**Comment by youness-teimoury** [comment]
I also have a performance issue with sentry Java agent.
When the java agent is set on our machine, the response time becomes terribly slow.
Attached are some snapshots.
Agent set:
<img width="971" alt="with-agent" src="https://user-images.githubusercontent.com/3833974/47811100-dec48f00-dd3c-11e8-9c57-45e95aa4ddd0.png">
Agent not set:
<img width="1286" alt="without-agent" src="https://user-images.githubusercontent.com/3833974/47811108-e421d980-dd3c-11e8-98f4-5bf0a65d2ebc.png">

**Comment by m1schka** [comment]
I can also confirm my jvm is becoming extremely slow. It starts so slowly (spring application) that it doesn't pass the initial healthcheck in time, so it get's thrown away quite fast.
running on kubernetes 1.10 with an openjdk cent os base image

**Comment by rgriffith** [comment]
I am also running into performance issues after adding the agent. In addition to performance issues, the system was exhausting memory and killing the Java process entirely. 

For reference, the application was allocated 4G and total system memory is about 8G (c5.xlarge AWS EC2). Let me know if you need additional details and I would be happy to share.

**Comment by ostrya** [comment]
Hi, I am trying to use the agent with a Spring Boot app, but I get no additional context. When I enable trace logging on the agent, I see:
`TRACE [Sentry Agent]: Unable to locate Sentry class.`

When I add `if( env->ExceptionOccurred() ) { env->ExceptionDescribe(); }` to agent.cpp:20, I can additionally see:

```
Exception in thread "main" java.lang.NoClassDefFoundError: io/sentry/Sentry
at java.lang.ClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at org.springframework.boot.loader.jar.JarURLConnection.getInputStream(JarURLConnection.java:163)
at sun.misc.URLClassPath$Loader.getResource(Unknown Source)
at sun.misc.URLClassPath.getResource(Unknown Source)
at java.net.URLClassLoader$1.run(Unknown Source)
at java.net.URLClassLoader$1.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93)
at java.lang.ClassLoader.loadClass(Unknown Source)
at java.lang.Class.getDeclaredConstructors0(Native Method)
at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
at java.lang.Class.getConstructor0(Unknown Source)
at java.lang.Class.newInstance(Unknown Source)
at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:61)
at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:45)
at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:34)
at ch.qos.logback.core.pattern.parser.Compiler.createConverter(Compiler.java:104)
at ch.qos.logback.core.pattern.parser.Compiler.compile(Compiler.java:63)
at ch.qos.logback.core.pattern.parser.Parser.compile(Parser.java:87)
at ch.qos.logback.core.pattern.PatternLayoutBase.start(PatternLayoutBase.java:84)
at ch.qos.logback.classic.encoder.PatternLayoutEncoder.start(PatternLayoutEncoder.java:28)
at ch.qos.logback.core.joran.action.NestedComplexPropertyIA.end(NestedComplexPropertyIA.java:161)
at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:309)
at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:193)
at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:179)
at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
at org.springframework.boot.logging.logback.LogbackLoggingSystem.configureByResourceUrl(LogbackLoggingSystem.java:180)
at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:152)
at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithSpecificConfig(AbstractLoggingSystem.java:67)
at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:57)
at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:117)
at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:298)
at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:266)
at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:229)
at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:202)
at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:75)
at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:347)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
at com.example.MyApplication.main(MyApplication.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
```

**Comment by bretthoerner** [comment]
Have you configured `stacktrace.app.packages` as noted here https://docs.sentry.io/clients/java/agent/ ?

Please note the agent is rather slow and buggy still, we have some work to do here.

**Comment by ostrya** [comment]
Yes, I did configure this, and the stacktraces in the issue view are properly distinguishing app and library calls.

And I can confirm a drop of response time by a factor of 4-5.

I suspect that the agent somehow does not work well with Spring Boot's LaunchedURLClassLoader.

**Comment by deeTEEcee** [comment]
is there any future possibility of adding those stacktrace variables to the logger as well?
