### ISSUE TITLE
java.lang.NoSuchMethodError: sun.security.ssl.SSLSessionImpl.<init>

### ISSUE THREAD

**Issue by vlad-shtark** [getsentry/sentry-java#700]
java.lang.NoSuchMethodError: sun.security.ssl.SSLSessionImpl.<init>(Lsun/security/ssl/ProtocolVersion;Lsun/security/ssl/CipherSuite;Ljava/util/Collection;Lsun/security/ssl/SessionId;Ljava/lang/String;I)V
	at sun.security.ssl.ClientHandshaker.serverHello(ClientHandshaker.java:709)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:209)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:984)

-----
The stacktrace suggests that a constructor of SSLSessionImpl with 7 arguments was looked up and could not be found. 
In fact, starting with 8u191 the signature of SSLSessionImpl has changed and now the constructor requires 8 arguments. 

The best guess is that the submitter somehow got the classes from different JDK versions loaded: ClientHandshaker from an older release (so it calls 7-arg SSLSessionImpl constructor), but SSLSessionImpl from a newer release (so it only has 8-arg constructor). 

-- Please recompile project for java 8 with latesst JDK/JRE --

**Comment by vlad-shtark** [comment]
solution :
in glassfish5\glassfish\modules\endorsed replace grizzly-npn-bootstrap.jar to new, from http://central.maven.org/maven2/org/glassfish/grizzly/grizzly-npn-bootstrap  (grizzly-npn-bootstrap-1.8.1)
