### ISSUE TITLE
Android: Troubles with new DSN

### ISSUE THREAD

**Issue by dron247** [getsentry/sentry-java#718]
Hi. I spotted an issue. When I'm trying to use new DSN it shows me such thing(I implemented custom client factory):
```
019-05-24 10:57:03.675 18068-18068/xxx.dev E/XxAndroidSentryClientFactory: java.lang.IllegalStateException: dsn.secretKey must not be null
        at xxx.util.sentry.XxAndroidSentryClientFactory.createHttpConnection(XxAndroidSentryClientFactory.kt:52)
        at io.sentry.DefaultSentryClientFactory.createConnection(DefaultSentryClientFactory.java:327)
        at io.sentry.DefaultSentryClientFactory.createSentryClient(DefaultSentryClientFactory.java:236)
        at io.sentry.android.AndroidSentryClientFactory.createSentryClient(AndroidSentryClientFactory.java:75)
        at io.sentry.SentryClientFactory.sentryClient(SentryClientFactory.java:64)
        at io.sentry.Sentry.init(Sentry.java:81)
        at xxx.XxApplication.initializeErrorReporter(XxApplication:49)
        at xxx.XxApplication.onCreate(XxApplication.kt:21)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5918)
        at android.app.ActivityThread.access$1100(ActivityThread.java:202)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1665)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:198)
        at android.app.ActivityThread.main(ActivityThread.java:6729)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
Bu everything okay with legacy DSN. We are using 1.7.25

**Comment by justacodefan** [comment]
Can you confirm which version of the SDK you're using? Upgrading to the latest version will no longer require you to specify a `secretKey` as Sentry no longer requires it.

**Comment by dron247** [comment]
1.7.25 which i've got from documentation couple of days earlier

**Comment by justacodefan** [comment]
The latest Sentry Java SDK release is 1.7.22

**Comment by dron247** [comment]
sorry, i'm talking about android artifact version

**Comment by justacodefan** [comment]
I need to know which version of the Sentry SDK you're using; as in, the code present in this repository or listed in https://github.com/getsentry/sentry-java/releases. It should be in your build.gradle file. If you're not using `1.7.22`, please upgrade to that version.

**Comment by dron247** [comment]
ohh, i missed that, 1.7.25 it's slf4j version

**Comment by dron247** [comment]
anyway, please update documentation

**Comment by justacodefan** [comment]
That documentation page is not incorrect; it merely lists an older version of the SDK. Closing this issue for now.
