### ISSUE TITLE
Lazy initialisation of Http Connection

### ISSUE THREAD

**Issue by remcomokveld** [getsentry/sentry-java#760]
Initializing Sentry on Android will cause a StrictMode violation when done on the main thread. 

Creating the http connection happens on the main thread which is an expensive operation. This will cause the first frame drawn by an application to be delayed. for no reason. The connection only gets used in a later state, so it can also be created in a later state.

```
2019-09-02 10:56:23.635 6651-6651/ D/StrictMode: StrictMode policy violation; ~duration=216 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
        at java.io.UnixFileSystem.getLastModifiedTime(UnixFileSystem.java:258)
        at java.io.File.lastModified(File.java:939)
        at java.util.zip.ZipFile.<init>(ZipFile.java:238)
        at java.util.zip.ZipFile.<init>(ZipFile.java:152)
        at java.util.jar.JarFile.<init>(JarFile.java:160)
        at java.util.jar.JarFile.<init>(JarFile.java:97)
        at libcore.io.ClassPathURLStreamHandler.<init>(ClassPathURLStreamHandler.java:47)
        at dalvik.system.DexPathList$Element.maybeInit(DexPathList.java:702)
        at dalvik.system.DexPathList$Element.findResource(DexPathList.java:729)
        at dalvik.system.DexPathList.findResource(DexPathList.java:508)
        at dalvik.system.BaseDexClassLoader.findResource(BaseDexClassLoader.java:169)
        at java.lang.ClassLoader.getResource(ClassLoader.java:793)
        at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:987)
        at io.sentry.config.ContextClassLoaderResourceLoader.getInputStream(ContextClassLoaderResourceLoader.java:16)
        at io.sentry.config.CompoundResourceLoader.getInputStream(CompoundResourceLoader.java:35)
        at io.sentry.config.provider.ResourceLoaderConfigurationProvider.loadProperties(ResourceLoaderConfigurationProvider.java:38)
        at io.sentry.config.provider.ResourceLoaderConfigurationProvider.<init>(ResourceLoaderConfigurationProvider.java:28)
        at io.sentry.config.provider.LocatorBasedConfigurationProvider.<init>(LocatorBasedConfigurationProvider.java:24)
        at io.sentry.config.Lookup.getDefaultLowPriorityConfigurationProviders(Lookup.java:104)
        at io.sentry.config.Lookup.<init>(Lookup.java:55)
        at io.sentry.config.Lookup.getDeprecatedInstance(Lookup.java:117)
        at io.sentry.config.Lookup.lookup(Lookup.java:154)
        at io.sentry.DefaultSentryClientFactory.getProxyHost(DefaultSentryClientFactory.java:703)
        at io.sentry.DefaultSentryClientFactory.createHttpConnection(DefaultSentryClientFactory.java:412)
        at io.sentry.DefaultSentryClientFactory.createConnection(DefaultSentryClientFactory.java:335)
        at io.sentry.DefaultSentryClientFactory.createSentryClient(DefaultSentryClientFactory.java:244)
        at io.sentry.android.AndroidSentryClientFactory.createSentryClient(AndroidSentryClientFactory.java:98)
        at io.sentry.SentryClientFactory.sentryClient(SentryClientFactory.java:64)
```

**Comment by ninniuz** [comment]
As per the stracktrace the real problem is the amount of time it takes to extract and read the `sentry.properties` file from the app resources.
Can I suggest you move your `sentry.properties` file (if any) from the `resources` folder to the app's `assets` and you init Sentry through `SentryOptions`?
E.g.
```
Sentry.init(SentryOptions().apply {
    dsn = sentryDsn
    resourceLoader = AndroidAssetsResourceLoader(context)
    sentryClientFactory = AndroidSentryClientFactory(context)
})
```

`AndroidAssetsResourceLoader` will take care of retrieving the file from the assets, which is way faster than extracting it from resources via the `ClassLoader` (some reference [here](https://github.com/getsentry/sentry-java/issues/708))

**Comment by remcomokveld** [comment]
Just tried that, but still getting this violation.

I do not have a `sentry.properties` file. So is the `AndroidAssetsResourceLoader` maybe falling back to `ClassLoader` if it can't find anything in assets?

In any case. To have as little impact as possible I feel like Sentry's init method should really be doing nothing more than storing the `SentryOptions` in memory, and possibly register a global exception handler, and all other work should be considered deferrable and be done on a background thread.

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.

https://github.com/getsentry/sentry-android which is sentry-android v2.0 uses AndroidManifest metadata for its configurations.

Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
