### ISSUE TITLE
Stack trace isn't being de-obfuscated for andorid. R8 code shrinker.

### ISSUE THREAD

**Issue by CarsonRedeye** [getsentry/sentry-java#785]
Mapping files are uploading correctly via the sentry-gradle-plugin. I can see them under Debug Files in sentry settings. However I can only see a stack trace like this:

`java.lang.NumberFormatException: For input string: "bucket_3017"
    at java.lang.Long.parseLong(Long.java:594)
    at java.lang.Long.parseLong(Long.java:636)
    at c.a.a.e.b0.g.b.a(SourceFile:96)
    at co.redacted.presentation.search.qrcode.b.a(SourceFile:26)
    at co.redacted.presentation.search.qrcode.b.a(SourceFile:3)
    at co.redacted.presentation.search.qrcode.b$g.a(SourceFile:2)
    at co.redacted.presentation.search.qrcode.b$g.a(SourceFile:1)
    at g.b.b0.d.f.onSuccess(SourceFile:2)
    at g.b.b0.e.f.d$a.onSuccess(SourceFile:1)
    at g.b.b0.e.f.e$a.onSuccess(SourceFile:2)
    at g.b.b0.e.f.p$a.onSuccess(SourceFile:1)
    at g.b.b0.e.e.z$a.onComplete(SourceFile:6)
    at n.v.a.a$a.onComplete(SourceFile:2)
    at n.v.a.c.b(SourceFile:9)
    at g.b.m.a(SourceFile:54)
    at n.v.a.a.b(SourceFile:1)
    at g.b.m.a(SourceFile:54)
    at g.b.b0.e.e.z.b(SourceFile:1)
    at g.b.s.a(SourceFile:32)
    at g.b.b0.e.f.p$a.run(SourceFile:1)
    at g.b.r$a.run(SourceFile:2)
    at g.b.b0.g.k.run(SourceFile:2)
    at g.b.b0.g.k.call(SourceFile:1)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:764)`

If I download that same mapping file from sentry and use Analyze Stack Track in Android studio, and apply Proguard Unscrambler it works correctly. My suspicion is that changes to the mapping file with new versions of Android Studio/R8 shrinker are causing sentry.io to fail with it's deobfuscation.

I'm using 'io.sentry:sentry-android-gradle-plugin:1.7.21' and 'io.sentry:sentry-android:1.7.21'

**Comment by bruno-garcia** [comment]
@CarsonRedeye are you using sentry.io? If so, do you have an example event that didn't get demangled?

**Comment by CarsonRedeye** [comment]
Do you want the id of the event? Here it is 2141289252a948698a1b33b8af161378

**Comment by bruno-garcia** [comment]
The whole link would do, please.

**Comment by CarsonRedeye** [comment]
https://sentry.io/organizations/redeye-apps/issues/1290081906/events/8836d27f51974369a9a6e014be2102f2/

**Comment by marandaneto** [comment]
@CarsonRedeye hey, did you manage to get it working? there were a few fixes since `1.7.21`, if not, do you mind testing the latest one `1.7.29` and if it doesn't work, please write down the AGP and Gradle version, thanks.

**Comment by marandaneto** [comment]
@CarsonRedeye closing this issue, if you see that is still happening, let us know :)

**Comment by chpasha** [comment]
I'm experiencing the same (or similar) issue with plugin version 1.7.29 and sentry version 1.7.30. The problem is that not all source files names are rendered correctly
this is how the raw stacktrace looks like
```
java.lang.RuntimeException: Test exception
    at d.a.f.f.s0.t.r(SourceFile:1)
    at de.tomcom.tim.activity.bewertung.BewertungLoader.a(SourceFile:19)
    at d.a.f.f.s0.b0.a(SourceFile:2)
    at d.a.f.f.s0.b0$b.run(SourceFile:1)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6077)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```
now the deobfuscated version in sentry 
```

java.lang.RuntimeException: Test exception
    at de.tomcom.tim.activity.bewertung.BewertungActivity.onBewertungLoaded(SourceFile:1)
    at de.tomcom.tim.activity.bewertung.BewertungLoader.onBewertungLoaded(SourceFile:19)
    at de.tomcom.tim.activity.bewertung.BewertungLoader_.access$101(SourceFile:2)
    at de.tomcom.tim.activity.bewertung.BewertungLoader_$2.run(SourceFile:1)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6077)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

and finally the stacktrace deobfuscated with proguard retrace
```

java.lang.RuntimeException: Test exception
    at de.tomcom.tim.activity.bewertung.BewertungActivity.onBewertungLoaded(BewertungActivity.java:244)
    at de.tomcom.tim.activity.bewertung.BewertungLoader.onBewertungLoaded(BewertungLoader.java:348)
    at de.tomcom.tim.activity.bewertung.BewertungLoader_.access$101(BewertungLoader_.java:21)
    at de.tomcom.tim.activity.bewertung.BewertungLoader_$2.run(BewertungLoader_.java:86)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6077)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

as you can see, the most important last frames are not rendered correctly

**Comment by marandaneto** [comment]
@chpasha hey, could you elaborate a bit more?
AGP, Gradle, build-tools, proguard or R8, build type/flavors? that would help, thanks.

**Comment by chpasha** [comment]
Hi, sorry.
We have self-hosted Sentry 10.1.0.dev0
Android Gradle Plugin 3.5.3 (so it's R8)
Gradle 5.6.2
Build tools 29.0.2
Build type/flavours: debug/release (the code is ofbuscated only for release), flavors production/dev differ only in additional arguments for annotation processing

**Comment by marandaneto** [comment]
@chpasha thanks, we will be looking into it

**Comment by marandaneto** [comment]
@jan-auer can you give us a hand on that? it might be something on https://github.com/getsentry/symbolicator

See:
<img width="988" alt="screenshot_2020-02-12_at_17 55 08" src="https://user-images.githubusercontent.com/5731772/74422760-66111580-4e4f-11ea-8631-1feaa87ceb01.png">

Thanks!

**Comment by jan-auer** [comment]
R8 is handled in the [Java plugin](https://github.com/getsentry/sentry/blob/f96d1fc138155ec51b2f35a0be0355cf908a83fd/src/sentry/lang/java/plugin.py) in Sentry and runs through [rust-proguard](https://github.com/getsentry/rust-proguard). If you have an offending proguard mapping and crash, we could fix it there.

**Comment by chpasha** [comment]
I could send you a mapping file privately and the unobfuscated stacktrace is already in the ticket.

**Comment by chpasha** [comment]
I'm migrating the second project which is significantly smaller than the previous one and it has exactly the same problem like the first one. I wonder if the problem could be reproduced with a trivial hello world app - will try this tomorrow if I have time

**Comment by marandaneto** [comment]
@chpasha it would be very helpful if you have a reproducible repo, thanks for that.

**Comment by TobiasReich** [comment]
**We have the same issue for our project.**

The gradle plugin adds the sentry-debug-meta.properties file to the Android assets folder.
The mapping file is also uploaded to the (self hosted) project but yet nothing is mapped.
Does this have to be configured somehow?

**Comment by cmdrsabre** [comment]
> **We have the same issue for our project.**
> 
> The gradle plugin adds the sentry-debug-meta.properties file to the Android assets folder.
> The mapping file is also uploaded to the (self hosted) project but yet nothing is mapped.
> Does this have to be configured somehow?

same here :-(

**Comment by marandaneto** [comment]
hey @TobiasReich and @cmdrsabre thanks for that.
Is nothing demangled at all or just a few lines like stated before? please elaborate it a bit more.

Some info would be helpful, like:
Gradle + AGP + Sentry plugin versions.

Also, a sample repo would be very helpful, thanks.
