### ISSUE TITLE
Crashes not detected

### ISSUE THREAD

**Issue by sebastianhealthiq** [getsentry/sentry-java#808]
Hi I followed the setup docs for Android and did theses steps:

1. Added support libs to app gradle
2. created an Application subclass and added this code:
```
class MainApplication : Application() {

    override fun onCreate() {
        super.onCreate()
        Sentry.init(
            "https://xxxxx@sentry.io/xxxx",
            AndroidSentryClientFactory(this)
        )
    }
}
```

Then I created a test crash case in an activity that gets launched when you click a button in the app:
```
val info: TextView = findViewById(R.id.email)
 info.text = "Crash"
```
(R.id.email doesn't exist in that view)

Then I started the app and triggered the crash, here are the logs:
```
2020-01-09 18:18:47.903 12906-12906/com.xxx.xxx D/io.sentry.android.AndroidSentryClientFactory: Construction of Android Sentry from Android Application.
2020-01-09 18:18:47.905 12906-12906/com.xxx.xxx D/io.sentry.android.AndroidSentryClientFactory: Sentry init with ctx='com.xxx.xxx.MainApplication@abd970b'
2020-01-09 18:18:47.918 12906-12906/com.xxx.xxx D/io.sentry.android.AndroidSentryClientFactory: Using buffer dir: /data/user/0/com.xxx.xxx/cache/sentry-buffered-events
2020-01-09 18:18:47.925 12906-12906/com.xxx.xxx D/io.sentry.android.AndroidSentryClientFactory: ANR is='false'
....
....
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xxxx.xxx, PID: 12685
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxx.xxx/com.xxxx.xxx.ui.policy.PolicyActivity}: java.lang.IllegalStateException: findViewById(R.id.email) must not be null
```

I opened the app up again to give sentry some time to upload the crash and tried triggering the crash a few more times. An hour later with normal app testing I still don't see the crash reported in sentry.

Did I miss a set up step or is this type of crash not detected by Sentry?

**Comment by marandaneto** [comment]
Hey @sebastianhealthiq thanks for your question.

Have you added the _MainApplication_ in the _AndroidManifest_ file?
Like:
```
<application
    android:name=".MainApplication"
    ...>
```

Have you added the _INTERNET_ permission in the _AndroidManifest_ file?
Like:
`
<uses-permission android:name="android.permission.INTERNET" />
`

If so, what's the version of your SDK? _io.sentry:sentry-android_

Do you have _Proguard_ or _R8_ enabled? if so, have you integrated our _Gradle Plugin_ to easily merge the Proguard rules? _io.sentry:sentry-android-gradle-plugin_

Do you mind sharing the full stack trace? you may hide sensitive data.

Thanks :)

**Comment by sebastianhealthiq** [comment]
Thanks for you help.

Yes the MainApplication and internet permission is setup in the manifest file (I have successful requests for other features and if I set a breakpoint on the sentry init code it gets hit)

The sdk is 1.7.27
```
implementation 'io.sentry:sentry-android:1.7.27'
implementation 'org.slf4j:slf4j-nop:1.7.25'
```

I have not setup Proguard or R8 yet.

Here's the full verbose stack trace: 
```
2020-01-10 13:00:54.785 21665-21665/? I/om.xxxxxx: Late-enabling -Xcheck:jni
2020-01-10 13:00:54.819 21665-21665/? E/om.xxxxxx: Unknown bits set in runtime_flags: 0x8000
2020-01-10 13:00:55.256 21665-21665/? D/io.sentry.android.AndroidSentryClientFactory: Construction of Android Sentry from Android Application.
2020-01-10 13:00:55.258 21665-21665/? D/io.sentry.android.AndroidSentryClientFactory: Sentry init with ctx='com.xxxxxxq.MainApplication@abd970b'
2020-01-10 13:00:55.272 21665-21665/? D/io.sentry.android.AndroidSentryClientFactory: Using buffer dir: /data/user/0/com.xxxxxxq/cache/sentry-buffered-events
2020-01-10 13:00:55.278 21665-21665/? D/io.sentry.android.AndroidSentryClientFactory: ANR is='false'
2020-01-10 13:00:55.275 21665-21665/? W/om.xxxxxxq: type=1400 audit(0.0:6334): avc: denied { read } for name="version" dev="proc" ino=4026532124 scontext=u:r:untrusted_app:s0:c176,c256,c512,c768 tcontext=u:object_r:proc_version:s0 tclass=file permissive=0
2020-01-10 13:00:55.299 21665-21704/? I/AWSKeyValueStore: Detected Android API Level = 29
2020-01-10 13:00:55.299 21665-21704/? I/AWSKeyValueStore: Creating the AWSKeyValueStore with key for sharedPreferencesForData = com.amazonaws.mobile.client
2020-01-10 13:00:55.302 21665-21704/? I/AWSKeyValueStore: Detected Android API Level = 29
2020-01-10 13:00:55.302 21665-21704/? I/AWSKeyValueStore: Creating the AWSKeyValueStore with key for sharedPreferencesForData = com.amazonaws.android.auth
2020-01-10 13:00:55.302 21665-21704/? D/AWSMobileClient: Using the SignInProviderConfig from `awsconfiguration.json`.
2020-01-10 13:00:55.330 21665-21704/? W/LogFactory: Truncating log tag length as it exceed 23, the limit imposed by Android on certain API Levels
2020-01-10 13:00:55.332 21665-21704/? I/AWSKeyValueStore: Detected Android API Level = 29
2020-01-10 13:00:55.332 21665-21704/? I/AWSKeyValueStore: Creating the AWSKeyValueStore with key for sharedPreferencesForData = com.amazonaws.android.auth
2020-01-10 13:00:55.334 21665-21704/? E/AWSKeyValueStore: com.amazonaws.internal.keyvaluestore.KeyNotFoundException: Error occurred while accessing AndroidKeyStore to retrieve the key for keyAlias: com.amazonaws.android.auth.aesKeyStoreAlias
2020-01-10 13:00:55.334 21665-21704/? I/AWSKeyValueStore: Deleting the encryption key identified by the keyAlias: com.amazonaws.android.auth.aesKeyStoreAlias
2020-01-10 13:00:55.335 21665-21704/? E/AWSKeyValueStore: Error in retrieving the decryption key used to decrypt the data from the persistent store. Returning null for the requested dataKey = us-east-1_9D4yOBgNT.identityId
2020-01-10 13:00:55.335 21665-21704/? D/CognitoCachingCredentialsProvider: Loading credentials from SharedPreferences
2020-01-10 13:00:55.336 21665-21704/? E/AWSKeyValueStore: com.amazonaws.internal.keyvaluestore.KeyNotFoundException: Error occurred while accessing AndroidKeyStore to retrieve the key for keyAlias: com.amazonaws.android.auth.aesKeyStoreAlias
2020-01-10 13:00:55.336 21665-21704/? I/AWSKeyValueStore: Deleting the encryption key identified by the keyAlias: com.amazonaws.android.auth.aesKeyStoreAlias
2020-01-10 13:00:55.338 21665-21704/? E/AWSKeyValueStore: Error in retrieving the decryption key used to decrypt the data from the persistent store. Returning null for the requested dataKey = us-east-1_9D4yOBgNT.expirationDate
2020-01-10 13:00:55.338 21665-21704/? D/CognitoCachingCredentialsProvider: No valid credentials found in SharedPreferences
2020-01-10 13:00:55.339 21665-21704/? W/LogFactory: Truncating log tag length as it exceed 23, the limit imposed by Android on certain API Levels
2020-01-10 13:00:55.364 21665-21704/? I/AWSKeyValueStore: Detected Android API Level = 29
2020-01-10 13:00:55.364 21665-21704/? I/AWSKeyValueStore: Creating the AWSKeyValueStore with key for sharedPreferencesForData = CognitoIdentityProviderCache
2020-01-10 13:00:55.365 21665-21665/? W/om.xxxxxx: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
2020-01-10 13:00:55.366 21665-21665/? W/om.xxxxxx: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
2020-01-10 13:00:55.367 21665-21704/? D/AWSMobileClient: getHostedUIJSON: Failed to read config
    java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONObject com.amazonaws.mobile.config.AWSConfiguration.optJsonObject(java.lang.String)' on a null object reference
        at com.amazonaws.mobile.client.AWSMobileClient.getHostedUIJSONFromJSON(AWSMobileClient.java:636)
        at com.amazonaws.mobile.client.AWSMobileClient.getHostedUIJSON(AWSMobileClient.java:655)
        at com.amazonaws.mobile.client.AWSMobileClient$2.run(AWSMobileClient.java:569)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
        at java.lang.Thread.run(Thread.java:919)
2020-01-10 13:00:55.368 21665-21704/? E/AWSKeyValueStore: com.amazonaws.internal.keyvaluestore.KeyNotFoundException: Error occurred while accessing AndroidKeyStore to retrieve the key for keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
2020-01-10 13:00:55.368 21665-21704/? I/AWSKeyValueStore: Deleting the encryption key identified by the keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
2020-01-10 13:00:55.369 21665-21704/? E/AWSKeyValueStore: Error in retrieving the decryption key used to decrypt the data from the persistent store. Returning null for the requested dataKey = provider
2020-01-10 13:00:55.370 21665-21704/? E/AWSKeyValueStore: com.amazonaws.internal.keyvaluestore.KeyNotFoundException: Error occurred while accessing AndroidKeyStore to retrieve the key for keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
2020-01-10 13:00:55.370 21665-21704/? I/AWSKeyValueStore: Deleting the encryption key identified by the keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
2020-01-10 13:00:55.371 21665-21704/? E/AWSKeyValueStore: Error in retrieving the decryption key used to decrypt the data from the persistent store. Returning null for the requested dataKey = token
2020-01-10 13:00:55.371 21665-21704/? E/AWSKeyValueStore: com.amazonaws.internal.keyvaluestore.KeyNotFoundException: Error occurred while accessing AndroidKeyStore to retrieve the key for keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
2020-01-10 13:00:55.371 21665-21704/? I/AWSKeyValueStore: Deleting the encryption key identified by the keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
2020-01-10 13:00:55.372 21665-21704/? E/AWSKeyValueStore: Error in retrieving the decryption key used to decrypt the data from the persistent store. Returning null for the requested dataKey = signInMode
2020-01-10 13:00:55.373 21665-21704/? E/AWSKeyValueStore: com.amazonaws.internal.keyvaluestore.KeyNotFoundException: Error occurred while accessing AndroidKeyStore to retrieve the key for keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
2020-01-10 13:00:55.373 21665-21704/? I/AWSKeyValueStore: Deleting the encryption key identified by the keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
2020-01-10 13:00:55.374 21665-21704/? E/AWSKeyValueStore: Error in retrieving the decryption key used to decrypt the data from the persistent store. Returning null for the requested dataKey = cognitoIdentityId
2020-01-10 13:00:55.374 21665-21704/? E/AWSKeyValueStore: com.amazonaws.internal.keyvaluestore.KeyNotFoundException: Error occurred while accessing AndroidKeyStore to retrieve the key for keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
2020-01-10 13:00:55.374 21665-21704/? I/AWSKeyValueStore: Deleting the encryption key identified by the keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
2020-01-10 13:00:55.375 21665-21704/? E/AWSKeyValueStore: Error in retrieving the decryption key used to decrypt the data from the persistent store. Returning null for the requested dataKey = isFederationEnabled
2020-01-10 13:00:55.375 21665-21704/? D/AWSMobileClient: Inspecting user state details
2020-01-10 13:00:55.375 21665-21704/? I/INIT: onResult: SIGNED_OUT
2020-01-10 13:00:55.400 21665-21665/? W/om.xxxxxx: Accessing hidden method Landroid/graphics/FontFamily;-><init>()V (greylist, reflection, allowed)
2020-01-10 13:00:55.400 21665-21665/? W/om.xxxxxx: Accessing hidden method Landroid/graphics/FontFamily;->addFontFromAssetManager(Landroid/content/res/AssetManager;Ljava/lang/String;IZIII[Landroid/graphics/fonts/FontVariationAxis;)Z (greylist, reflection, allowed)
2020-01-10 13:00:55.400 21665-21665/? W/om.xxxxxx: Accessing hidden method Landroid/graphics/FontFamily;->addFontFromBuffer(Ljava/nio/ByteBuffer;I[Landroid/graphics/fonts/FontVariationAxis;II)Z (greylist, reflection, allowed)
2020-01-10 13:00:55.400 21665-21665/? W/om.xxxxxx: Accessing hidden method Landroid/graphics/FontFamily;->freeze()Z (greylist, reflection, allowed)
2020-01-10 13:00:55.400 21665-21665/? W/om.xxxxxx: Accessing hidden method Landroid/graphics/FontFamily;->abortCreation()V (greylist, reflection, allowed)
2020-01-10 13:00:55.400 21665-21665/? W/om.xxxxxx: Accessing hidden method Landroid/graphics/Typeface;->createFromFamiliesWithDefault([Landroid/graphics/FontFamily;Ljava/lang/String;II)Landroid/graphics/Typeface; (greylist, reflection, allowed)
2020-01-10 13:00:55.425 21665-21665/? D/Session: ******** loaded authUser
2020-01-10 13:00:55.458 21665-21665/? D/Session: ******** KEY_POLICIES: loaded 1
2020-01-10 13:00:55.458 21665-21665/? D/Session: ******** loaded authUser
2020-01-10 13:00:55.458 21665-21665/? D/PolicyProvider: fetching policies for user: 318470
2020-01-10 13:00:55.482 21665-21665/? D/HiqApiClient: GET policies
2020-01-10 13:00:55.485 21665-21665/? D/Session: ******** KEY_DOCUMENTS: loaded 1
2020-01-10 13:00:55.485 21665-21665/? D/Session: ******** loaded authUser
2020-01-10 13:00:55.485 21665-21665/? D/DocumentProvider: fetching documents for user: User(uniqueId=318470, salesforceId=0031900000aVXDuAAO, firstName=shuo, lastName=Jiao, email=, mobilePhone=14026134513, age=26, dob=1994-01-01, gender=male, weight=0, height=0).uniqueId
2020-01-10 13:00:55.486 21665-21665/? D/HiqApiClient: GET documents
2020-01-10 13:00:55.488 21665-21665/? D/MainActivity: APP_STATE: logged in
2020-01-10 13:00:55.493 21665-21665/? D/MainActivity: onResume
2020-01-10 13:00:55.496 21665-21718/? D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2020-01-10 13:00:55.570 21665-21665/? D/HomeRecyclerViewAdapter: setData: 0
2020-01-10 13:00:55.573 21665-21665/? D/HomeFragment: policies updated
2020-01-10 13:00:55.573 21665-21665/? D/HomeRecyclerViewAdapter: setData: 1
2020-01-10 13:00:55.585 21665-21665/? D/DocsFragment: docs updated
2020-01-10 13:00:55.585 21665-21665/? D/DocsRecyclerViewAdapter: setData: 1
2020-01-10 13:00:55.600 21665-21707/? I/Adreno: QUALCOMM build                   : bc00834, I609ab310b2
    Build Date                       : 04/11/19
    OpenGL ES Shader Compiler Version: EV031.26.07.00
    Local Branch                     : 
    Remote Branch                    : 
    Remote Branch                    : 
    Reconstruct Branch               : 
2020-01-10 13:00:55.600 21665-21707/? I/Adreno: Build Config                     : S L 8.0.6 AArch64
2020-01-10 13:00:55.603 21665-21707/? I/Adreno: PFP: 0x005ff110, ME: 0x005ff066
2020-01-10 13:00:55.741 21665-21707/? W/Gralloc3: mapper 3.x is not supported
2020-01-10 13:00:55.755 21665-21665/? W/om.xxxxxx: Accessing hidden field Landroid/view/View;->mAccessibilityDelegate:Landroid/view/View$AccessibilityDelegate; (greylist, reflection, allowed)
2020-01-10 13:00:56.825 21665-21665/com.xxxxxxq D/PolicyProvider: response is: {....}
2020-01-10 13:00:56.853 21665-21665/com.xxxxxxq D/PolicyProvider: found policy: Policy(....)
2020-01-10 13:00:56.854 21665-21665/com.xxxxxxq D/PolicyProvider: found policies: 1
2020-01-10 13:00:56.854 21665-21665/com.xxxxxxq D/Session: ++++++++ KEY_POLICIES: saving
2020-01-10 13:00:56.863 21665-21665/com.xxxxxxq D/HomeFragment: policies updated
2020-01-10 13:00:56.863 21665-21665/com.xxxxxxq D/HomeRecyclerViewAdapter: setData: 1
2020-01-10 13:00:57.222 21665-21665/? D/DocumentProvider: response is: {.....}
2020-01-10 13:00:57.225 21665-21665/? D/DocumentProvider: found document: Document(.....)
2020-01-10 13:00:57.225 21665-21665/? D/DocumentProvider: found document: 1
2020-01-10 13:00:57.225 21665-21665/? D/Session: ++++++++ KEY_DOCUMENTS: saving
2020-01-10 13:00:57.227 21665-21665/? D/DocsFragment: docs updated
2020-01-10 13:00:57.227 21665-21665/? D/DocsRecyclerViewAdapter: setData: 1
2020-01-10 13:01:01.283 21665-21665/? D/MainActivity: touched home fragment item: 0, 0
2020-01-10 13:01:01.299 21665-21665/? W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@ebf1af9
2020-01-10 13:01:01.379 21665-21665/? D/PolicyActivity: received policy: Policy(.....)
2020-01-10 13:01:01.381 21665-21665/? D/Session: ******** loaded authUser
2020-01-10 13:01:01.381 21665-21665/? D/ActionItemProvider: fetching action items for policy: 00619000008nO32AAE
2020-01-10 13:01:01.382 21665-21665/? D/HiqApiClient: GET action items for policy: 00619000008nO32AAE
2020-01-10 13:01:01.383 21665-21665/? D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2020-01-10 13:01:01.384 21665-21665/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xxxxxxq, PID: 21665
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxxxxxq/com.xxxxxxq.ui.policy.PolicyActivity}: java.lang.IllegalStateException: findViewById(R.id.email) must not be null
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalStateException: findViewById(R.id.email) must not be null
        at com.xxxxxxq.ui.policy.PolicyActivity.updateWithPolicy(PolicyActivity.kt:101)
        at com.xxxxxxq.ui.policy.PolicyActivity.onCreate(PolicyActivity.kt:67)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
2020-01-10 13:01:01.389 21665-21665/? D/io.sentry.android.event.helper.AndroidEventBuilderHelper: Proguard UUIDs file not found.
2020-01-10 13:01:01.444 21665-21665/? I/Process: Sending signal. PID: 21665 SIG: 9
```

**Comment by marandaneto** [comment]
@sebastianhealthiq thanks for the stack trace.

Would you mind testing the latest version? `io.sentry:sentry-android:1.7.29`
there were a few fixes on the last versions, so let's hope to be one of them, as the stack trace doesn't say much, no errors at all.

Are you using a valid `DSN?`? it could be found here: https://sentry.io/settings/{org}/projects/{project}/keys/

Are you checking the right project? issues may be seen here:
https://sentry.io/organizations/{org}/issues/?project={project_id}

Please let us know :)

**Comment by sebastianhealthiq** [comment]
Ah I was using the wrong DSN key - the docs defaulted to a different android project with a similar name so I didn't notice. I see the crash logging now!

**Comment by marandaneto** [comment]
@sebastianhealthiq perfect :)
