### ISSUE TITLE
Sentry android does not sent crashes and logs to server

### ISSUE THREAD

**Issue by hrsalehi** [getsentry/sentry-java#969]
_Platform:_
- [X]  Android ->  API 29, compileSdkVersion/targetSdkVersion also 29
_IDE:_
- [X]  Android Studio -> 4.0.1
_Build system:_
- [X]  Gradle -> 6.1.1
_Android Gradle Plugin:_
- [X]  Yes -> 4.0.0
_Sentry Android Gradle Plugin:_
- [X]  Yes -> 4.0.0\
_Platform installed with:_
- [x] JCenter
The version of the SDK:
**3.0.0**
_Sentry server
Sentry 20.8.0.dev0992c6f6
---
I have the following issue:
When first running project to check if Sentry is initialized or not the following logs comes in logcat:
<pre>
2020-10-07 16:32:29.195 28839-28839/ir.emdad.apps.sana.android.irkpos D/Sentry: Auto-init: true
2020-10-07 16:32:29.195 28839-28839/ir.emdad.apps.sana.android.irkpos I/Sentry: Retrieving auto-init from AndroidManifest.xml
2020-10-07 16:32:29.259 28839-28953/ir.emdad.apps.sana.android.irkpos I/Sentry: sentry-debug-meta.properties file was not found.
2020-10-07 16:32:29.282 28839-28953/ir.emdad.apps.sana.android.irkpos D/Sentry: SU doesn't exist.
    java.io.IOException: Cannot run program "/system/xbin/which": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
        at java.lang.Runtime.exec(Runtime.java:698)
        at java.lang.Runtime.exec(Runtime.java:563)
        at io.sentry.android.core.util.RootChecker.checkSUExist(RootChecker.java:135)
        at io.sentry.android.core.util.RootChecker.isDeviceRooted(RootChecker.java:90)
        at io.sentry.android.core.DefaultAndroidEventProcessor.loadContextData(DefaultAndroidEventProcessor.java:114)
        at io.sentry.android.core.DefaultAndroidEventProcessor.lambda$new$0$DefaultAndroidEventProcessor(DefaultAndroidEventProcessor.java:102)
        at io.sentry.android.core.-$$Lambda$DefaultAndroidEventProcessor$ZsPdDrAaOs30gov_5eSNgy_KYe8.call(Unknown Source:2)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
        at java.lang.ProcessImpl.start(ProcessImpl.java:141)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        at java.lang.Runtime.exec(Runtime.java:698) 
        at java.lang.Runtime.exec(Runtime.java:563) 
        at io.sentry.android.core.util.RootChecker.checkSUExist(RootChecker.java:135) 
        at io.sentry.android.core.util.RootChecker.isDeviceRooted(RootChecker.java:90) 
        at io.sentry.android.core.DefaultAndroidEventProcessor.loadContextData(DefaultAndroidEventProcessor.java:114) 
        at io.sentry.android.core.DefaultAndroidEventProcessor.lambda$new$0$DefaultAndroidEventProcessor(DefaultAndroidEventProcessor.java:102) 
        at io.sentry.android.core.-$$Lambda$DefaultAndroidEventProcessor$ZsPdDrAaOs30gov_5eSNgy_KYe8.call(Unknown Source:2) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 

</pre>

and after that capturing an exception and after that throwing a runtime exception

```java

 try {  
            throw new Exception("This is a test.");
        } catch (Exception e) {
            Log.d("Sentry" ,"sentry exp");
            Sentry.captureException(e);
        }
        throw new RuntimeException("exp");

```
It first produced this log

<pre>
2020-10-07 16:41:27.336 28839-28839/ir.emdad.apps.sana.android.irkpos D/Sentry: sentry exp
2020-10-07 16:41:27.354 28839-32504/ir.emdad.apps.sana.android.irkpos I/System.out:     at io.sentry.transport.AsyncConnection$EnvelopeSender.flush(AsyncConnection.java:258)
2020-10-07 16:41:27.354 28839-32504/ir.emdad.apps.sana.android.irkpos I/System.out:     at io.sentry.transport.AsyncConnection$EnvelopeSender.run(AsyncConnection.java:212)
2020-10-07 16:41:27.355 28839-32504/ir.emdad.apps.sana.android.irkpos I/System.out:     at io.sentry.transport.HttpTransport.createConnection(HttpTransport.java:246)
2020-10-07 16:41:27.355 28839-32504/ir.emdad.apps.sana.android.irkpos I/System.out:     at io.sentry.transport.HttpTransport.send(HttpTransport.java:252)
2020-10-07 16:41:27.355 28839-32504/ir.emdad.apps.sana.android.irkpos I/System.out:     at io.sentry.transport.AsyncConnection$EnvelopeSender.flush(AsyncConnection.java:239)
2020-10-07 16:41:27.376 28839-32504/ir.emdad.apps.sana.android.irkpos I/System.out: DEBUG: io.sentry.UncaughtExceptionHandlerIntegration.UncaughtExceptionHint is not Retryable
2020-10-07 16:41:27.377 28839-32504/ir.emdad.apps.sana.android.irkpos I/System.out:     at io.sentry.transport.AsyncConnection$EnvelopeSender.flush(AsyncConnection.java:258)
2020-10-07 16:41:27.377 28839-32504/ir.emdad.apps.sana.android.irkpos I/System.out:     at io.sentry.transport.AsyncConnection$EnvelopeSender.run(AsyncConnection.java:212)
2020-10-07 16:41:27.377 28839-32504/ir.emdad.apps.sana.android.irkpos I/System.out:     at io.sentry.transport.HttpTransport.createConnection(HttpTransport.java:246)
2020-10-07 16:41:27.377 28839-32504/ir.emdad.apps.sana.android.irkpos I/System.out:     at io.sentry.transport.HttpTransport.send(HttpTransport.java:252)
2020-10-07 16:41:27.377 28839-32504/ir.emdad.apps.sana.android.irkpos I/System.out:     at io.sentry.transport.AsyncConnection$EnvelopeSender.flush(AsyncConnection.java:239)
</pre>

and then by running the app again
 <pre>
2020-10-07 16:52:39.033 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: Auto-init: true
2020-10-07 16:52:39.033 13673-13673/ir.emdad.apps.sana.android.irkpos I/Sentry: Retrieving auto-init from AndroidManifest.xml
2020-10-07 16:52:39.062 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: debug read: true
2020-10-07 16:52:39.063 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: anrEnabled read: true
2020-10-07 16:52:39.063 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: sessionTrackingEnabled read: true
2020-10-07 16:52:39.063 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: sampleRate read: -1.0
2020-10-07 16:52:39.063 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: anrReportInDebug read: false
2020-10-07 16:52:39.063 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: anrTimeoutIntervalMillis read: 5000
2020-10-07 16:52:39.063 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: DSN read: <MY DSN VALUE>
2020-10-07 16:52:39.064 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: NDK read: true
2020-10-07 16:52:39.064 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: ndkScopeSync read: false
2020-10-07 16:52:39.064 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: release read: null
2020-10-07 16:52:39.064 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: environment read: null
2020-10-07 16:52:39.064 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: sessionTrackingTimeoutIntervalMillis read: 5000
2020-10-07 16:52:39.064 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: enableActivityLifecycleBreadcrumbs read: true
2020-10-07 16:52:39.064 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: enableAppLifecycleBreadcrumbs read: true
2020-10-07 16:52:39.064 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: enableSystemEventBreadcrumbs read: true
2020-10-07 16:52:39.064 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: enableAppComponentBreadcrumbs read: true
2020-10-07 16:52:39.065 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: enableUncaughtExceptionHandler read: true
2020-10-07 16:52:39.065 13673-13673/ir.emdad.apps.sana.android.irkpos I/Sentry: Retrieving configuration from AndroidManifest.xml
2020-10-07 16:52:39.084 13673-13763/ir.emdad.apps.sana.android.irkpos I/Sentry: sentry-debug-meta.properties file was not found.
2020-10-07 16:52:39.085 13673-13673/ir.emdad.apps.sana.android.irkpos I/Sentry: Initializing SDK with DSN: '<MY DSN VALUE>'
2020-10-07 16:52:39.088 13673-13763/ir.emdad.apps.sana.android.irkpos D/Sentry: SU doesn't exist.
    java.io.IOException: Cannot run program "/system/xbin/which": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
        at java.lang.Runtime.exec(Runtime.java:698)
        at java.lang.Runtime.exec(Runtime.java:563)
        at io.sentry.android.core.util.RootChecker.checkSUExist(RootChecker.java:135)
        at io.sentry.android.core.util.RootChecker.isDeviceRooted(RootChecker.java:90)
        at io.sentry.android.core.DefaultAndroidEventProcessor.loadContextData(DefaultAndroidEventProcessor.java:114)
        at io.sentry.android.core.DefaultAndroidEventProcessor.lambda$new$0$DefaultAndroidEventProcessor(DefaultAndroidEventProcessor.java:102)
        at io.sentry.android.core.-$$Lambda$DefaultAndroidEventProcessor$ZsPdDrAaOs30gov_5eSNgy_KYe8.call(Unknown Source:2)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
        at java.lang.ProcessImpl.start(ProcessImpl.java:141)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        at java.lang.Runtime.exec(Runtime.java:698) 
        at java.lang.Runtime.exec(Runtime.java:563) 
        at io.sentry.android.core.util.RootChecker.checkSUExist(RootChecker.java:135) 
        at io.sentry.android.core.util.RootChecker.isDeviceRooted(RootChecker.java:90) 
        at io.sentry.android.core.DefaultAndroidEventProcessor.loadContextData(DefaultAndroidEventProcessor.java:114) 
        at io.sentry.android.core.DefaultAndroidEventProcessor.lambda$new$0$DefaultAndroidEventProcessor(DefaultAndroidEventProcessor.java:102) 
        at io.sentry.android.core.-$$Lambda$DefaultAndroidEventProcessor$ZsPdDrAaOs30gov_5eSNgy_KYe8.call(Unknown Source:2) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
2020-10-07 16:52:39.092 13673-13673/ir.emdad.apps.sana.android.irkpos I/Sentry: GlobalHubMode: 'true'
2020-10-07 16:52:39.102 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: UncaughtExceptionHandlerIntegration enabled: true
2020-10-07 16:52:39.102 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: default UncaughtExceptionHandler class='com.google.firebase.crashlytics.internal.common.CrashlyticsUncaughtExceptionHandler'
2020-10-07 16:52:39.102 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: UncaughtExceptionHandlerIntegration installed.
2020-10-07 16:52:39.104 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: SendCachedEventFireAndForgetIntegration installed.
2020-10-07 16:52:39.104 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: NdkIntegration enabled: true
2020-10-07 16:52:39.105 13673-13765/ir.emdad.apps.sana.android.irkpos D/Sentry: Started processing cached files from /data/user/0/ir.emdad.apps.sana.android.irkpos/cache/sentry
2020-10-07 16:52:39.105 13673-13765/ir.emdad.apps.sana.android.irkpos D/Sentry: Processing dir. /data/user/0/ir.emdad.apps.sana.android.irkpos/cache/sentry
2020-10-07 16:52:39.105 13673-13673/ir.emdad.apps.sana.android.irkpos I/sentry-native: using database path "/data/data/ir.emdad.apps.sana.android.irkpos/cache/sentry/.sentry-native"
2020-10-07 16:52:39.105 13673-13673/ir.emdad.apps.sana.android.irkpos D/sentry-native: starting backend
2020-10-07 16:52:39.105 13673-13765/ir.emdad.apps.sana.android.irkpos D/Sentry: Processing 0 items from cache dir /data/user/0/ir.emdad.apps.sana.android.irkpos/cache/sentry
2020-10-07 16:52:39.106 13673-13765/ir.emdad.apps.sana.android.irkpos D/Sentry: File /data/user/0/ir.emdad.apps.sana.android.irkpos/cache/sentry/outbox is not a File.
2020-10-07 16:52:39.106 13673-13765/ir.emdad.apps.sana.android.irkpos D/Sentry: File /data/user/0/ir.emdad.apps.sana.android.irkpos/cache/sentry/.sentry-native is not a File.
2020-10-07 16:52:39.106 13673-13765/ir.emdad.apps.sana.android.irkpos D/Sentry: Finished processing cached files from /data/user/0/ir.emdad.apps.sana.android.irkpos/cache/sentry
2020-10-07 16:52:39.107 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: NdkIntegration installed.
2020-10-07 16:52:39.107 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: Registering EnvelopeFileObserverIntegration for path: /data/user/0/ir.emdad.apps.sana.android.irkpos/cache/sentry/outbox
2020-10-07 16:52:39.109 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: EnvelopeFileObserverIntegration installed.
2020-10-07 16:52:39.109 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: SendCachedEventFireAndForgetIntegration installed.
2020-10-07 16:52:39.109 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: AnrIntegration enabled: true
2020-10-07 16:52:39.109 13673-13765/ir.emdad.apps.sana.android.irkpos D/Sentry: Started processing cached files from /data/user/0/ir.emdad.apps.sana.android.irkpos/cache/sentry/outbox
2020-10-07 16:52:39.109 13673-13765/ir.emdad.apps.sana.android.irkpos D/Sentry: Processing dir. /data/user/0/ir.emdad.apps.sana.android.irkpos/cache/sentry/outbox
2020-10-07 16:52:39.109 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: ANR timeout in milliseconds: 5000
2020-10-07 16:52:39.110 13673-13765/ir.emdad.apps.sana.android.irkpos D/Sentry: Processing 0 items from cache dir /data/user/0/ir.emdad.apps.sana.android.irkpos/cache/sentry/outbox
2020-10-07 16:52:39.110 13673-13765/ir.emdad.apps.sana.android.irkpos D/Sentry: Finished processing cached files from /data/user/0/ir.emdad.apps.sana.android.irkpos/cache/sentry/outbox
2020-10-07 16:52:39.110 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: AnrIntegration installed.
2020-10-07 16:52:39.110 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: enableSessionTracking enabled: true
2020-10-07 16:52:39.111 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: enableAppLifecycleBreadcrumbs enabled: true
2020-10-07 16:52:39.113 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: AppLifecycleIntegration installed.
2020-10-07 16:52:39.114 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: ActivityBreadcrumbsIntegration enabled: true
2020-10-07 16:52:39.114 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: ActivityBreadcrumbsIntegration installed.
2020-10-07 16:52:39.114 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: AppComponentsBreadcrumbsIntegration enabled: true
2020-10-07 16:52:39.114 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: AppComponentsBreadcrumbsIntegration installed.
2020-10-07 16:52:39.114 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: SystemEventsBreadcrumbsIntegration enabled: true
2020-10-07 16:52:39.116 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: SystemEventsBreadcrumbsIntegration installed.
2020-10-07 16:52:39.116 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: enableSystemEventsBreadcrumbs enabled: true
2020-10-07 16:52:39.122 13673-13673/ir.emdad.apps.sana.android.irkpos I/Sentry: TYPE_AMBIENT_TEMPERATURE is not available.
2020-10-07 16:52:39.122 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: enableSystemEventBreadcrumbs enabled: true
2020-10-07 16:52:39.129 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: UncaughtExceptionHandlerIntegration removed.
2020-10-07 16:52:39.129 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: EnvelopeFileObserverIntegration removed.
2020-10-07 16:52:39.129 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: AnrIntegration removed.
2020-10-07 16:52:39.130 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: AppLifecycleIntegration removed.
2020-10-07 16:52:39.130 13673-13769/ir.emdad.apps.sana.android.irkpos W/Sentry: Interrupted: null
2020-10-07 16:52:39.130 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: ActivityBreadcrumbsIntegration removed.
2020-10-07 16:52:39.130 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: AppComponentsBreadcrumbsIntegration removed.
2020-10-07 16:52:39.130 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: SystemEventsBreadcrumbsIntegration remove.
2020-10-07 16:52:39.130 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: TempSensorBreadcrumbsIntegration removed.
2020-10-07 16:52:39.131 13673-13673/ir.emdad.apps.sana.android.irkpos I/Sentry: Closing SentryClient.
2020-10-07 16:52:39.131 13673-13673/ir.emdad.apps.sana.android.irkpos D/Sentry: Shutting down

</pre>

Also my main build.gradle properties:
```
buildscript {
    ext.kotlin_version = '1.3.72'

    repositories {
        google()
        mavenCentral()
        jcenter()
        maven {
            url "https://jitpack.io"
        }
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.0.0'
        classpath 'com.google.gms:google-services:4.3.3'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.2.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'io.sentry:sentry-android-gradle-plugin:1.7.28'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        jcenter()
        maven { url 'https://maven.google.com' }
        maven {
            url  "http://dl.bintray.com/piasy/maven"
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```
and app build.gradle :
```
apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'  // Google Services plugin
apply plugin: 'com.google.firebase.crashlytics'
apply plugin: 'io.sentry.android.gradle'

android {
    flavorDimensions "default"
    productFlavors {

        flavorIRKPos {
            applicationIdSuffix ".irkpos"
            versionCode 12
            versionName "1.2.0"
        }
    }
    compileSdkVersion 29
    defaultConfig {
        applicationId "ir.emdad.apps.sana.android"
        minSdkVersion 16
        targetSdkVersion 29
        versionCode 39
        versionName "0.29.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true

    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }
    compileOptions {
        targetCompatibility 1.8
        sourceCompatibility 1.8
    }
}

repositories {
    maven {
        url "https://jitpack.io"
    }
    maven {
        url 'https://maven.google.com/'
        name 'Google'
    }
    maven { url 'https://maven.fabric.io/public' }
    mavenCentral()
}

buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
    }

    dependencies {
        classpath 'io.fabric.tools:gradle:1.+'
    }
}

dependencies {
    implementation 'com.google.code.gson:gson:2.8.5'
    implementation 'com.squareup.retrofit2:retrofit:2.5.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.5.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:4.6.0'
    implementation 'com.google.firebase:firebase-analytics:17.4.3'
    implementation 'com.google.firebase:firebase-core:17.4.3'
    implementation 'com.google.firebase:firebase-messaging:20.2.1'
    implementation 'com.google.firebase:firebase-crashlytics:17.1.0'
    testImplementation 'junit:junit:4.13'
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation 'com.onesignal:OneSignal:3.10.1'
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'com.google.android.gms:play-services-vision:20.1.0'
    implementation 'com.google.android.gms:play-services-maps:17.0.0'
    implementation 'com.google.android.gms:play-services-base:17.3.0'
    implementation 'com.google.android.gms:play-services-location:17.0.0'
    implementation 'com.google.android.gms:play-services-gcm:17.0.0'
    implementation 'com.annimon:stream:1.2.1'
...
    implementation 'io.sentry:sentry-android:3.0.0'
}

apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'

```
sentry.properties in main app folder
<pre>
defaults.project=<project value>
defaults.org=<org value>
auth.token=<my auth token>
</pre>

AndroidManifest.xml
```
<application>
        <meta-data android:name="io.sentry.dsn" android:value="<MY DSN VALUE>" />

        <!-- enable debug mode, it's disabled by default -->
        <meta-data android:name="io.sentry.debug" android:value="true" />

        <!-- enable release health, it's disabled by default -->
        <meta-data android:name="io.sentry.session-tracking.enable" android:value="true" />

        <!-- it's 30s by default, making it 5s for testing -->
        <meta-data android:name="io.sentry.session-tracking.timeout-interval-millis" android:value="5000" />


</application>
```

**Steps to reproduce:**
- setting up android sdk with official docs
- adding proguard configurations

**Expected result:**
- Logging exceptions on server successfully

**Comment by hrsalehi** [comment]
Also another log while sending logs are
<pre>
2020-10-07 18:13:50.657 22601-22877/ir.emdad.apps.sana.android.irkpos D/Sentry: Started processing cached files from /data/user/0/ir.emdad.apps.sana.android.irkpos/cache/sentry
2020-10-07 18:13:50.658 22601-22877/ir.emdad.apps.sana.android.irkpos D/Sentry: Processing dir. /data/user/0/ir.emdad.apps.sana.android.irkpos/cache/sentry
2020-10-07 18:13:50.658 22601-22877/ir.emdad.apps.sana.android.irkpos D/Sentry: Processing 0 items from cache dir /data/user/0/ir.emdad.apps.sana.android.irkpos/cache/sentry
2020-10-07 18:13:50.660 22601-22601/ir.emdad.apps.sana.android.irkpos D/Sentry: SystemEventsBreadcrumbsIntegration installed.
2020-10-07 18:13:50.660 22601-22877/ir.emdad.apps.sana.android.irkpos D/Sentry: File /data/user/0/ir.emdad.apps.sana.android.irkpos/cache/sentry/outbox is not a File.
2020-10-07 18:13:50.660 22601-22601/ir.emdad.apps.sana.android.irkpos D/Sentry: enableSystemEventsBreadcrumbs enabled: true
2020-10-07 18:13:50.660 22601-22877/ir.emdad.apps.sana.android.irkpos D/Sentry: File /data/user/0/ir.emdad.apps.sana.android.irkpos/cache/sentry/.sentry-native is not a File.
2020-10-07 18:13:50.660 22601-22877/ir.emdad.apps.sana.android.irkpos D/Sentry: Finished processing cached files from /data/user/0/ir.emdad.apps.sana.android.irkpos/cache/sentry
2020-10-07 18:13:50.660 22601-22877/ir.emdad.apps.sana.android.irkpos D/Sentry: Started processing cached files from /data/user/0/ir.emdad.apps.sana.android.irkpos/cache/sentry/outbox
2020-10-07 18:13:50.660 22601-22877/ir.emdad.apps.sana.android.irkpos D/Sentry: Processing dir. /data/user/0/ir.emdad.apps.sana.android.irkpos/cache/sentry/outbox
2020-10-07 18:13:50.661 22601-22877/ir.emdad.apps.sana.android.irkpos D/Sentry: Processing 0 items from cache dir /data/user/0/ir.emdad.apps.sana.android.irkpos/cache/sentry/outbox
2020-10-07 18:13:50.661 22601-22877/ir.emdad.apps.sana.android.irkpos D/Sentry: Finished processing cached files from /data/user/0/ir.emdad.apps.sana.android.irkpos/cache/sentry/outbox
2020-10-07 18:13:50.671 22601-22601/ir.emdad.apps.sana.android.irkpos I/Sentry: TYPE_AMBIENT_TEMPERATURE is not available.
2020-10-07 18:13:50.671 22601-22601/ir.emdad.apps.sana.android.irkpos D/Sentry: enableSystemEventBreadcrumbs enabled: true
2020-10-07 18:13:52.060 22601-23089/ir.emdad.apps.sana.android.irkpos D/Sentry: Adding Envelope to offline storage: /data/user/0/ir.emdad.apps.sana.android.irkpos/cache/sentry/062532d2-cc4a-4a7c-bd5c-c7bc1e721e37.envelope
2020-10-07 18:13:52.098 22601-23089/ir.emdad.apps.sana.android.irkpos D/Sentry: io.sentry.hints.SessionStartHint is not Retryable
2020-10-07 18:13:52.099 22601-23089/ir.emdad.apps.sana.android.irkpos E/Sentry: Envelope submission failed
    java.lang.IllegalStateException: Sending the event failed.
        at io.sentry.transport.AsyncConnection$EnvelopeSender.flush(AsyncConnection.java:258)
        at io.sentry.transport.AsyncConnection$EnvelopeSender.run(AsyncConnection.java:212)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.io.IOException: Cleartext HTTP traffic to 192.168.102.92 not permitted
        at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:124)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:480)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:135)
        at io.sentry.transport.HttpTransport.createConnection(HttpTransport.java:246)
        at io.sentry.transport.HttpTransport.send(HttpTransport.java:252)
        at io.sentry.transport.AsyncConnection$EnvelopeSender.flush(AsyncConnection.java:239)
        at io.sentry.transport.AsyncConnection$EnvelopeSender.run(AsyncConnection.java:212) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 

</pre>

**Comment by bruno-garcia** [comment]
The issue is in the stack trace:

`     Caused by: java.io.IOException: Cleartext HTTP traffic to 192.168.102.92 not permitted`

Does your DSN use `http://`?

**Comment by hrsalehi** [comment]
I just permitted cleartext traffic. I think the problem occures from the server and it is because server installation. I found out the DSN URL is a local IP and changed manually but now I receive error 502 from server.
Thank you very much I close this one and checks server configuration
