### ISSUE TITLE
android.os.strictmode.UntaggedSocketViolation: Untagged socket detected

### ISSUE THREAD

**Issue by ItsReddi** [getsentry/sentry-java#995]
_Platform:_
- [x]  Android
_Build system:_
- [x]  Gradle
_Proguard/R8:_
- [x]  Enabled

The version of the SDK:
**3.1.0**

---
I have the following issue:
With strictMode enabled we get policy violations.
```
StrictMode.setVmPolicy(new StrictMode.VmPolicy.Builder()
                    .detectAll()
                    .penaltyLog()
                    .penaltyDeath()
                    .build());
```

**Steps to reproduce:**
Enable Strictmode

**Actual result:**
```
2020-10-16 12:21:03.819 19512-19643/? D/StrictMode: StrictMode policy violation: android.os.strictmode.UntaggedSocketViolation: Untagged socket detected; use TrafficStats.setThreadSocketTag() to track all network usage
        at android.os.StrictMode.onUntaggedSocket(StrictMode.java:2124)
        at com.android.server.NetworkManagementSocketTagger.tag(NetworkManagementSocketTagger.java:82)
        at libcore.io.BlockGuardOs.tagSocket(BlockGuardOs.java:52)
        at libcore.io.BlockGuardOs.socket(BlockGuardOs.java:372)
        at libcore.io.ForwardingOs.socket(ForwardingOs.java:217)
        at libcore.io.IoBridge.socket(IoBridge.java:658)
        at java.net.PlainSocketImpl.socketCreate(PlainSocketImpl.java:128)
        at java.net.AbstractPlainSocketImpl.create(AbstractPlainSocketImpl.java:128)
        at java.net.Socket.createImpl(Socket.java:489)
        at java.net.Socket.getImpl(Socket.java:552)
        at java.net.Socket.setSoTimeout(Socket.java:1180)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:1405)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:1359)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:221)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:144)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:106)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:400)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:333)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:483)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:135)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
        at io.sentry.transport.HttpTransport.createConnection(HttpTransport.java:245)
        at io.sentry.transport.HttpTransport.send(HttpTransport.java:251)
        at io.sentry.transport.AsyncConnection$EnvelopeSender.flush(AsyncConnection.java:239)
        at io.sentry.transport.AsyncConnection$EnvelopeSender.run(AsyncConnection.java:212)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
2020-10-16 12:21:03.819 19512-19643/? W/System.err: StrictMode VmPolicy violation with POLICY_DEATH; shutting down.
```

**Expected result:**
- No policy restrictions
https://github.com/square/okhttp/issues/3537

**Comment by marandaneto** [comment]
dup #909

**Comment by ItsReddi** [comment]
Really duplicated?
909 raises another exception about a not closed resource and not about a non tagged socket.

**Comment by marandaneto** [comment]
the title is `Initializing Sentry triggers a StrictMode violation`
also, I state in the comments about the nontagged socket, which is actually an OkHttp issue, that has no side effects other than the warning.
